'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Namespace DatabaseTestApplication2

    Partial Public Class all_table_vw
        Public Property UID As Integer
        Public Property firstName As String
        Public Property lastName As String
        Public Property inquiryDate As Nullable(Of Date)
        Public Property streetAddress As String
        Public Property cityAddress As String
        Public Property zipAddress As String
        Public Property stateAddress As String
        Public Property countryAddress As String
        Public Property phoneNumber As String
        Public Property email As String
        Public Property gender As String
        Public Property birthdate As Nullable(Of Date)
        Public Property householdSize As Nullable(Of Integer)
        Public Property householdAMI As Nullable(Of Double)
        Public Property race As String
        Public Property maritalStatus As Nullable(Of SByte)
        Public Property notes As String
        Public Property coapplicantName As String
        Public Property dependentName As String
        Public Property applicantInfoMeeting As Nullable(Of Date)
        Public Property applicationChecklist1 As Nullable(Of Date)
        Public Property applicationChecklist2 As Nullable(Of Date)
        Public Property employmentVerified As Nullable(Of SByte)
        Public Property landlordReference As Nullable(Of SByte)
        Public Property previousLandlordReference As Nullable(Of SByte)
        Public Property backgroundCheck As Nullable(Of SByte)
        Public Property CCCBudget As Nullable(Of SByte)
        Public Property creditReportRun As Nullable(Of SByte)
        Public Property homeVisit As Nullable(Of Date)
        Public Property committeeDecision As Nullable(Of Date)
        Public Property committeeAccepted As Nullable(Of SByte)
        Public Property committeeReason As String
        Public Property boardVote As Nullable(Of Date)
        Public Property boardAccepted As Nullable(Of SByte)
        Public Property boardReason As String
        Public Property handbookReview As Nullable(Of Date)
        Public Property ApplicationSubmission As Nullable(Of Date)
        Public Property AdditionalDocuments As Nullable(Of Date)
        Public Property ApprovalSiteVisit As Nullable(Of Date)
        Public Property SiteVisitComplete As Nullable(Of Date)
        Public Property ScopeOfWork As Nullable(Of Date)
        Public Property ContractComplete As Nullable(Of Date)
        Public Property WorkComplete As Nullable(Of Date)
        Public Property IDDocuments As Nullable(Of SByte)
        Public Property IncomeVerified As Nullable(Of SByte)
        Public Property DeedOfTrust As Nullable(Of SByte)
        Public Property TaxBill As Nullable(Of SByte)
        Public Property Satisfaction As Nullable(Of SByte)
        Public Property CompletedApplication As Nullable(Of SByte)
        Public Property ParcelReport As Nullable(Of SByte)
        Public Property GISAssessment As Nullable(Of SByte)
        Public Property FundingSource As String
        Public Property sweatEquityDate As Nullable(Of Date)
        Public Property sweatEquityAmount As Nullable(Of Integer)
        Public Property monthlyDepositDate As Nullable(Of Date)
        Public Property monthlyDepositAmount As Nullable(Of Double)
        Public Property HUDHoursDate As Nullable(Of Date)
        Public Property HUDHoursComplete As Nullable(Of SByte)
        Public Property financeClassesDate As Nullable(Of Date)
        Public Property financeClassesComplete As Nullable(Of SByte)
        Public Property homebuyerEducationDate As Nullable(Of Date)
        Public Property homebuyerEducationAmount As Nullable(Of SByte)
        Public Property mortgage1Price As Nullable(Of Double)
        Public Property mortgage1Bank As String
        Public Property mortgage1Forgivable As Nullable(Of SByte)
        Public Property mortgage1OriginalBalance As Nullable(Of Double)
        Public Property mortgage1NumberOfYears As Nullable(Of Integer)
        Public Property mortgage2Price As Nullable(Of Double)
        Public Property mortgage2Bank As String
        Public Property mortgage2Forgivable As Nullable(Of SByte)
        Public Property mortgage2OriginalBalance As Nullable(Of Double)
        Public Property morgage2NumberOfYears As Nullable(Of Integer)
        Public Property mortgage3Price As Nullable(Of Double)
        Public Property mortgage3Bank As String
        Public Property mortgage3Forgivable As Nullable(Of SByte)
        Public Property mortgage3OriginalBalance As Nullable(Of Double)
        Public Property mortgage3NumberOfYears As Nullable(Of Integer)
        Public Property mortgage4Price As Nullable(Of Double)
        Public Property mortgage4Bank As String
        Public Property mortgage4Forgivable As Nullable(Of SByte)
        Public Property mortgage4OriginalBalance As Nullable(Of Double)
        Public Property mortgage4NumberOfYears As Nullable(Of Integer)
        Public Property mortgage5Price As Nullable(Of Double)
        Public Property mortgage5Bank As String
        Public Property mortgage5Forgivable As Nullable(Of SByte)
        Public Property mortgage5OriginalBalance As Nullable(Of Double)
        Public Property mortgage5NumberOfYears As Nullable(Of Integer)
        Public Property mortgage6Price As Nullable(Of Double)
        Public Property mortgage6Bank As String
        Public Property mortgage6Forgivable As Nullable(Of SByte)
        Public Property mortgage6OriginalBalance As Nullable(Of Double)
        Public Property mortgage6NumberOfYears As Nullable(Of Integer)
    
    End Class

End Namespace
