' ++++++++++++++++++++++++++++++++++++++++++++++++++
' This code is generated by a tool and is provided "as is", without warranty of any kind,
' express or implied, including but not limited to the warranties of merchantability,
' fitness for a particular purpose and non-infringement.
' In no event shall the authors or copyright holders be liable for any claim, damages or
' other liability, whether in an action of contract, tort or otherwise, arising from,
' out of or in connection with the software or the use or other dealings in the software.
' ++++++++++++++++++++++++++++++++++++++++++++++++++
'

Imports System.ComponentModel
Imports System.Data.Entity.Core.Objects
Imports System.Data.Entity

Namespace DatabaseTestApplication2
	
	Public Class frmgeneral_has_survey
		
		Private ctx As mydbEntities3
		
		Private Sub Form1_Load(sender As System.Object, e As System.EventArgs) Handles MyBase.Load
			ctx = new mydbEntities3()
			ctx.general_has_survey.Load()
			Dim _entities As BindingList(Of general_has_survey) = ctx.general_has_survey.Local.ToBindingList()
			general_has_surveyBindingSource.DataSource = _entities
			Me.general_UID_comboBox.DataSource = ctx.general.ToList()
			Me.general_UID_comboBox.DisplayMember = "UID"
			Me.general_UID_comboBox.ValueMember = "UID"
			Me.general_UID_comboBox.DataBindings.Add(New System.Windows.Forms.Binding("SelectedValue", Me.general_has_surveyBindingSource, "", True))
			Me.survey_SurveyID_comboBox.DataSource = ctx.survey.ToList()
			Me.survey_SurveyID_comboBox.DisplayMember = "SurveyID"
			Me.survey_SurveyID_comboBox.ValueMember = "SurveyID"
			Me.survey_SurveyID_comboBox.DataBindings.Add(New System.Windows.Forms.Binding("SelectedValue", Me.general_has_surveyBindingSource, "", True))
		End Sub
		
		Private Sub ToolStripButton1_Click(sender As System.Object, e As System.EventArgs) Handles ToolStripButton1.Click
			If Not Me.Validate() Then
				Return
			End If
			general_has_surveyBindingSource.EndEdit()
			ctx.SaveChanges()
		End Sub
		
		Private Sub Form1_FormClosing(sender As System.Object, e As System.Windows.Forms.FormClosingEventArgs) Handles MyBase.FormClosing
			e.Cancel = False
		End Sub
		
		Private Sub general_UID_comboBox_Validating(sender As System.Object, e As System.ComponentModel.CancelEventArgs) Handles general_UID_comboBox.Validating
			Dim i As Integer = general_UID_comboBox.SelectedIndex
			e.Cancel = False
			If i = -1 Then
				e.Cancel = True
				errorProvider1.SetError(general_UID_comboBox, "Must select a general_UID")
			End If
			If Not e.Cancel Then
				errorProvider1.SetError(general_UID_comboBox, "")
			End If
		End Sub
		Private Sub survey_SurveyID_comboBox_Validating(sender As System.Object, e As System.ComponentModel.CancelEventArgs) Handles survey_SurveyID_comboBox.Validating
			Dim i As Integer = survey_SurveyID_comboBox.SelectedIndex
			e.Cancel = False
			If i = -1 Then
				e.Cancel = True
				errorProvider1.SetError(survey_SurveyID_comboBox, "Must select a survey_SurveyID")
			End If
			If Not e.Cancel Then
				errorProvider1.SetError(survey_SurveyID_comboBox, "")
			End If
		End Sub
		
		Private Sub bindingNavigatorAddNewItem_Click(sender As System.Object, e As System.EventArgs) Handles BindingNavigatorAddNewItem.Click
			general_has_surveyBindingSource.AddNew()
		End Sub
		
	End Class
	
End Namespace
