' ++++++++++++++++++++++++++++++++++++++++++++++++++
' This code is generated by a tool and is provided "as is", without warranty of any kind,
' express or implied, including but not limited to the warranties of merchantability,
' fitness for a particular purpose and non-infringement.
' In no event shall the authors or copyright holders be liable for any claim, damages or
' other liability, whether in an action of contract, tort or otherwise, arising from,
' out of or in connection with the software or the use or other dealings in the software.
' ++++++++++++++++++++++++++++++++++++++++++++++++++
' 

Namespace DatabaseTestApplication2
	
	<Global.Microsoft.VisualBasic.CompilerServices.DesignerGenerated()> _
	Partial Class frmgeneral
		Inherits System.Windows.Forms.Form
		
		'Form overrides dispose to clean up the component list.
		<System.Diagnostics.DebuggerNonUserCode()> _
		Protected Overrides Sub Dispose(ByVal disposing As Boolean)
			Try
			If disposing AndAlso components IsNot Nothing Then
				components.Dispose()
			End If
			Finally
			MyBase.Dispose(disposing)
			End Try
		End Sub
		
		'Required by the Windows Form Designer
		Private components As System.ComponentModel.IContainer
		
		'NOTE: The following procedure is required by the Windows Form Designer
		'It can be modified using the Windows Form Designer.  
		'Do not modify it using the code editor.
		<System.Diagnostics.DebuggerStepThrough()> _
		Private Sub InitializeComponent()
            Me.components = New System.ComponentModel.Container()
            Dim resources As System.ComponentModel.ComponentResourceManager = New System.ComponentModel.ComponentResourceManager(GetType(frmgeneral))
            Me.BindingNavigator1 = New System.Windows.Forms.BindingNavigator(Me.components)
            Me.generalBindingSource = New System.Windows.Forms.BindingSource(Me.components)
            Me.BindingNavigatorCountItem = New System.Windows.Forms.ToolStripLabel()
            Me.BindingNavigatorDeleteItem = New System.Windows.Forms.ToolStripButton()
            Me.BindingNavigatorMoveFirstItem = New System.Windows.Forms.ToolStripButton()
            Me.BindingNavigatorMovePreviousItem = New System.Windows.Forms.ToolStripButton()
            Me.BindingNavigatorSeparator = New System.Windows.Forms.ToolStripSeparator()
            Me.BindingNavigatorPositionItem = New System.Windows.Forms.ToolStripTextBox()
            Me.BindingNavigatorSeparator1 = New System.Windows.Forms.ToolStripSeparator()
            Me.BindingNavigatorMoveNextItem = New System.Windows.Forms.ToolStripButton()
            Me.BindingNavigatorMoveLastItem = New System.Windows.Forms.ToolStripButton()
            Me.BindingNavigatorSeparator2 = New System.Windows.Forms.ToolStripSeparator()
            Me.BindingNavigatorAddNewItem = New System.Windows.Forms.ToolStripButton()
            Me.ToolStripButton1 = New System.Windows.Forms.ToolStripButton()
            Me.ErrorProvider1 = New System.Windows.Forms.ErrorProvider(Me.components)
            Me.Panel1 = New System.Windows.Forms.Panel()
            Me.raceComboBox = New System.Windows.Forms.ComboBox()
            Me.maritalStatusComboBox = New System.Windows.Forms.ComboBox()
            Me.genderComboBox = New System.Windows.Forms.ComboBox()
            Me.PictureBox1 = New System.Windows.Forms.PictureBox()
            Me.generalInfo = New System.Windows.Forms.Label()
            Me.UIDLabel = New System.Windows.Forms.Label()
            Me.UIDTextBox = New System.Windows.Forms.TextBox()
            Me.firstNameLabel = New System.Windows.Forms.Label()
            Me.firstNameTextBox = New System.Windows.Forms.TextBox()
            Me.lastNameLabel = New System.Windows.Forms.Label()
            Me.lastNameTextBox = New System.Windows.Forms.TextBox()
            Me.inquiryDateLabel = New System.Windows.Forms.Label()
            Me.inquiryDate_dateTimePicker = New System.Windows.Forms.DateTimePicker()
            Me.streetAddressLabel = New System.Windows.Forms.Label()
            Me.streetAddressTextBox = New System.Windows.Forms.TextBox()
            Me.cityAddressLabel = New System.Windows.Forms.Label()
            Me.cityAddressTextBox = New System.Windows.Forms.TextBox()
            Me.zipAddressLabel = New System.Windows.Forms.Label()
            Me.zipAddressTextBox = New System.Windows.Forms.TextBox()
            Me.stateAddressLabel = New System.Windows.Forms.Label()
            Me.stateAddressTextBox = New System.Windows.Forms.TextBox()
            Me.countryAddressLabel = New System.Windows.Forms.Label()
            Me.countryAddressTextBox = New System.Windows.Forms.TextBox()
            Me.phoneNumberLabel = New System.Windows.Forms.Label()
            Me.phoneNumberTextBox = New System.Windows.Forms.TextBox()
            Me.emailLabel = New System.Windows.Forms.Label()
            Me.emailTextBox = New System.Windows.Forms.TextBox()
            Me.genderLabel = New System.Windows.Forms.Label()
            Me.birthdateLabel = New System.Windows.Forms.Label()
            Me.birthdate_dateTimePicker = New System.Windows.Forms.DateTimePicker()
            Me.householdSizeLabel = New System.Windows.Forms.Label()
            Me.householdSizeTextBox = New System.Windows.Forms.TextBox()
            Me.householdAMILabel = New System.Windows.Forms.Label()
            Me.householdAMITextBox = New System.Windows.Forms.TextBox()
            Me.raceLabel = New System.Windows.Forms.Label()
            Me.maritalStatusLabel = New System.Windows.Forms.Label()
            Me.notesLabel = New System.Windows.Forms.Label()
            Me.notesTextBox = New System.Windows.Forms.TextBox()
            Me.MenuStrip1 = New System.Windows.Forms.MenuStrip()
            Me.MainMenuToolStripMenuItem = New System.Windows.Forms.ToolStripMenuItem()
            Me.HomeownershipToolStripMenuItem = New System.Windows.Forms.ToolStripMenuItem()
            Me.RepairsToolStripMenuItem = New System.Windows.Forms.ToolStripMenuItem()
            Me.TrackingToolStripMenuItem = New System.Windows.Forms.ToolStripMenuItem()
            Me.panel3 = New System.Windows.Forms.Panel()
            Me.panel4 = New System.Windows.Forms.Panel()
            Me.panel5 = New System.Windows.Forms.Panel()
            Me.panel6 = New System.Windows.Forms.Panel()
            CType(Me.BindingNavigator1, System.ComponentModel.ISupportInitialize).BeginInit()
            Me.BindingNavigator1.SuspendLayout()
            CType(Me.generalBindingSource, System.ComponentModel.ISupportInitialize).BeginInit()
            CType(Me.ErrorProvider1, System.ComponentModel.ISupportInitialize).BeginInit()
            Me.Panel1.SuspendLayout()
            CType(Me.PictureBox1, System.ComponentModel.ISupportInitialize).BeginInit()
            Me.MenuStrip1.SuspendLayout()
            Me.panel3.SuspendLayout()
            Me.SuspendLayout()
            '
            'BindingNavigator1
            '
            Me.BindingNavigator1.AddNewItem = Nothing
            Me.BindingNavigator1.BindingSource = Me.generalBindingSource
            Me.BindingNavigator1.CountItem = Me.BindingNavigatorCountItem
            Me.BindingNavigator1.DeleteItem = Me.BindingNavigatorDeleteItem
            Me.BindingNavigator1.ImageScalingSize = New System.Drawing.Size(20, 20)
            Me.BindingNavigator1.Items.AddRange(New System.Windows.Forms.ToolStripItem() {Me.BindingNavigatorMoveFirstItem, Me.BindingNavigatorMovePreviousItem, Me.BindingNavigatorSeparator, Me.BindingNavigatorPositionItem, Me.BindingNavigatorCountItem, Me.BindingNavigatorSeparator1, Me.BindingNavigatorMoveNextItem, Me.BindingNavigatorMoveLastItem, Me.BindingNavigatorSeparator2, Me.BindingNavigatorAddNewItem, Me.BindingNavigatorDeleteItem, Me.ToolStripButton1})
            Me.BindingNavigator1.Location = New System.Drawing.Point(0, 0)
            Me.BindingNavigator1.MoveFirstItem = Me.BindingNavigatorMoveFirstItem
            Me.BindingNavigator1.MoveLastItem = Me.BindingNavigatorMoveLastItem
            Me.BindingNavigator1.MoveNextItem = Me.BindingNavigatorMoveNextItem
            Me.BindingNavigator1.MovePreviousItem = Me.BindingNavigatorMovePreviousItem
            Me.BindingNavigator1.Name = "BindingNavigator1"
            Me.BindingNavigator1.Padding = New System.Windows.Forms.Padding(13, 0, 13, 0)
            Me.BindingNavigator1.PositionItem = Me.BindingNavigatorPositionItem
            Me.BindingNavigator1.Size = New System.Drawing.Size(989, 27)
            Me.BindingNavigator1.TabIndex = 0
            Me.BindingNavigator1.Text = "BindingNavigator1"
            '
            'BindingNavigatorCountItem
            '
            Me.BindingNavigatorCountItem.Name = "BindingNavigatorCountItem"
            Me.BindingNavigatorCountItem.Size = New System.Drawing.Size(45, 24)
            Me.BindingNavigatorCountItem.Text = "of {0}"
            Me.BindingNavigatorCountItem.ToolTipText = "Total number of items"
            '
            'BindingNavigatorDeleteItem
            '
            Me.BindingNavigatorDeleteItem.DisplayStyle = System.Windows.Forms.ToolStripItemDisplayStyle.Image
            Me.BindingNavigatorDeleteItem.Image = CType(resources.GetObject("BindingNavigatorDeleteItem.Image"), System.Drawing.Image)
            Me.BindingNavigatorDeleteItem.Name = "BindingNavigatorDeleteItem"
            Me.BindingNavigatorDeleteItem.RightToLeftAutoMirrorImage = True
            Me.BindingNavigatorDeleteItem.Size = New System.Drawing.Size(29, 24)
            Me.BindingNavigatorDeleteItem.Text = "Delete"
            '
            'BindingNavigatorMoveFirstItem
            '
            Me.BindingNavigatorMoveFirstItem.DisplayStyle = System.Windows.Forms.ToolStripItemDisplayStyle.Image
            Me.BindingNavigatorMoveFirstItem.Image = CType(resources.GetObject("BindingNavigatorMoveFirstItem.Image"), System.Drawing.Image)
            Me.BindingNavigatorMoveFirstItem.Name = "BindingNavigatorMoveFirstItem"
            Me.BindingNavigatorMoveFirstItem.RightToLeftAutoMirrorImage = True
            Me.BindingNavigatorMoveFirstItem.Size = New System.Drawing.Size(29, 24)
            Me.BindingNavigatorMoveFirstItem.Text = "Move first"
            '
            'BindingNavigatorMovePreviousItem
            '
            Me.BindingNavigatorMovePreviousItem.DisplayStyle = System.Windows.Forms.ToolStripItemDisplayStyle.Image
            Me.BindingNavigatorMovePreviousItem.Image = CType(resources.GetObject("BindingNavigatorMovePreviousItem.Image"), System.Drawing.Image)
            Me.BindingNavigatorMovePreviousItem.Name = "BindingNavigatorMovePreviousItem"
            Me.BindingNavigatorMovePreviousItem.RightToLeftAutoMirrorImage = True
            Me.BindingNavigatorMovePreviousItem.Size = New System.Drawing.Size(29, 24)
            Me.BindingNavigatorMovePreviousItem.Text = "Move previous"
            '
            'BindingNavigatorSeparator
            '
            Me.BindingNavigatorSeparator.Name = "BindingNavigatorSeparator"
            Me.BindingNavigatorSeparator.Size = New System.Drawing.Size(6, 27)
            '
            'BindingNavigatorPositionItem
            '
            Me.BindingNavigatorPositionItem.AccessibleName = "Position"
            Me.BindingNavigatorPositionItem.AutoSize = False
            Me.BindingNavigatorPositionItem.Font = New System.Drawing.Font("Segoe UI", 9.0!)
            Me.BindingNavigatorPositionItem.Name = "BindingNavigatorPositionItem"
            Me.BindingNavigatorPositionItem.Size = New System.Drawing.Size(65, 27)
            Me.BindingNavigatorPositionItem.Text = "0"
            Me.BindingNavigatorPositionItem.ToolTipText = "Current position"
            '
            'BindingNavigatorSeparator1
            '
            Me.BindingNavigatorSeparator1.Name = "BindingNavigatorSeparator1"
            Me.BindingNavigatorSeparator1.Size = New System.Drawing.Size(6, 27)
            '
            'BindingNavigatorMoveNextItem
            '
            Me.BindingNavigatorMoveNextItem.DisplayStyle = System.Windows.Forms.ToolStripItemDisplayStyle.Image
            Me.BindingNavigatorMoveNextItem.Image = CType(resources.GetObject("BindingNavigatorMoveNextItem.Image"), System.Drawing.Image)
            Me.BindingNavigatorMoveNextItem.Name = "BindingNavigatorMoveNextItem"
            Me.BindingNavigatorMoveNextItem.RightToLeftAutoMirrorImage = True
            Me.BindingNavigatorMoveNextItem.Size = New System.Drawing.Size(29, 24)
            Me.BindingNavigatorMoveNextItem.Text = "Move next"
            '
            'BindingNavigatorMoveLastItem
            '
            Me.BindingNavigatorMoveLastItem.DisplayStyle = System.Windows.Forms.ToolStripItemDisplayStyle.Image
            Me.BindingNavigatorMoveLastItem.Image = CType(resources.GetObject("BindingNavigatorMoveLastItem.Image"), System.Drawing.Image)
            Me.BindingNavigatorMoveLastItem.Name = "BindingNavigatorMoveLastItem"
            Me.BindingNavigatorMoveLastItem.RightToLeftAutoMirrorImage = True
            Me.BindingNavigatorMoveLastItem.Size = New System.Drawing.Size(29, 24)
            Me.BindingNavigatorMoveLastItem.Text = "Move last"
            '
            'BindingNavigatorSeparator2
            '
            Me.BindingNavigatorSeparator2.Name = "BindingNavigatorSeparator2"
            Me.BindingNavigatorSeparator2.Size = New System.Drawing.Size(6, 27)
            '
            'BindingNavigatorAddNewItem
            '
            Me.BindingNavigatorAddNewItem.DisplayStyle = System.Windows.Forms.ToolStripItemDisplayStyle.Image
            Me.BindingNavigatorAddNewItem.Image = CType(resources.GetObject("BindingNavigatorAddNewItem.Image"), System.Drawing.Image)
            Me.BindingNavigatorAddNewItem.Name = "BindingNavigatorAddNewItem"
            Me.BindingNavigatorAddNewItem.RightToLeftAutoMirrorImage = True
            Me.BindingNavigatorAddNewItem.Size = New System.Drawing.Size(29, 24)
            Me.BindingNavigatorAddNewItem.Text = "Add new"
            '
            'ToolStripButton1
            '
            Me.ToolStripButton1.DisplayStyle = System.Windows.Forms.ToolStripItemDisplayStyle.Image
            Me.ToolStripButton1.Image = CType(resources.GetObject("ToolStripButton1.Image"), System.Drawing.Image)
            Me.ToolStripButton1.ImageTransparentColor = System.Drawing.Color.Magenta
            Me.ToolStripButton1.Name = "ToolStripButton1"
            Me.ToolStripButton1.Size = New System.Drawing.Size(29, 24)
            Me.ToolStripButton1.Text = "Save"
            '
            'ErrorProvider1
            '
            Me.ErrorProvider1.ContainerControl = Me
            '
            'Panel1
            '
            Me.Panel1.AutoScroll = True
            Me.Panel1.AutoSize = True
            Me.Panel1.BackgroundImage = CType(resources.GetObject("Panel1.BackgroundImage"), System.Drawing.Image)
            Me.Panel1.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch
            Me.Panel1.Controls.Add(Me.raceComboBox)
            Me.Panel1.Controls.Add(Me.maritalStatusComboBox)
            Me.Panel1.Controls.Add(Me.genderComboBox)
            Me.Panel1.Controls.Add(Me.PictureBox1)
            Me.Panel1.Controls.Add(Me.generalInfo)
            Me.Panel1.Controls.Add(Me.UIDLabel)
            Me.Panel1.Controls.Add(Me.UIDTextBox)
            Me.Panel1.Controls.Add(Me.firstNameLabel)
            Me.Panel1.Controls.Add(Me.firstNameTextBox)
            Me.Panel1.Controls.Add(Me.lastNameLabel)
            Me.Panel1.Controls.Add(Me.lastNameTextBox)
            Me.Panel1.Controls.Add(Me.inquiryDateLabel)
            Me.Panel1.Controls.Add(Me.inquiryDate_dateTimePicker)
            Me.Panel1.Controls.Add(Me.streetAddressLabel)
            Me.Panel1.Controls.Add(Me.streetAddressTextBox)
            Me.Panel1.Controls.Add(Me.cityAddressLabel)
            Me.Panel1.Controls.Add(Me.cityAddressTextBox)
            Me.Panel1.Controls.Add(Me.zipAddressLabel)
            Me.Panel1.Controls.Add(Me.zipAddressTextBox)
            Me.Panel1.Controls.Add(Me.stateAddressLabel)
            Me.Panel1.Controls.Add(Me.stateAddressTextBox)
            Me.Panel1.Controls.Add(Me.countryAddressLabel)
            Me.Panel1.Controls.Add(Me.countryAddressTextBox)
            Me.Panel1.Controls.Add(Me.phoneNumberLabel)
            Me.Panel1.Controls.Add(Me.phoneNumberTextBox)
            Me.Panel1.Controls.Add(Me.emailLabel)
            Me.Panel1.Controls.Add(Me.emailTextBox)
            Me.Panel1.Controls.Add(Me.genderLabel)
            Me.Panel1.Controls.Add(Me.birthdateLabel)
            Me.Panel1.Controls.Add(Me.birthdate_dateTimePicker)
            Me.Panel1.Controls.Add(Me.householdSizeLabel)
            Me.Panel1.Controls.Add(Me.householdSizeTextBox)
            Me.Panel1.Controls.Add(Me.householdAMILabel)
            Me.Panel1.Controls.Add(Me.householdAMITextBox)
            Me.Panel1.Controls.Add(Me.raceLabel)
            Me.Panel1.Controls.Add(Me.maritalStatusLabel)
            Me.Panel1.Controls.Add(Me.notesLabel)
            Me.Panel1.Controls.Add(Me.notesTextBox)
            Me.Panel1.Controls.Add(Me.MenuStrip1)
            Me.Panel1.Dock = System.Windows.Forms.DockStyle.Fill
            Me.Panel1.ForeColor = System.Drawing.SystemColors.ControlLightLight
            Me.Panel1.Location = New System.Drawing.Point(13, 0)
            Me.Panel1.Margin = New System.Windows.Forms.Padding(13, 4, 13, 4)
            Me.Panel1.Name = "Panel1"
            Me.Panel1.Size = New System.Drawing.Size(963, 584)
            Me.Panel1.TabIndex = 1
            '
            'raceComboBox
            '
            Me.raceComboBox.FormattingEnabled = True
            Me.raceComboBox.Items.AddRange(New Object() {"White", "Black or African American", "American Indian or Alaska Native", "Asian", "Native Hawaiian or Other Pacific Islander"})
            Me.raceComboBox.Location = New System.Drawing.Point(565, 423)
            Me.raceComboBox.Name = "raceComboBox"
            Me.raceComboBox.Size = New System.Drawing.Size(221, 24)
            Me.raceComboBox.TabIndex = 42
            '
            'maritalStatusComboBox
            '
            Me.maritalStatusComboBox.FormattingEnabled = True
            Me.maritalStatusComboBox.Items.AddRange(New Object() {"Married", "Widowed", "Single", "Divorced or Separated"})
            Me.maritalStatusComboBox.Location = New System.Drawing.Point(565, 467)
            Me.maritalStatusComboBox.Name = "maritalStatusComboBox"
            Me.maritalStatusComboBox.Size = New System.Drawing.Size(221, 24)
            Me.maritalStatusComboBox.TabIndex = 41
            '
            'genderComboBox
            '
            Me.genderComboBox.FormattingEnabled = True
            Me.genderComboBox.Items.AddRange(New Object() {"Male", "Female", "Other"})
            Me.genderComboBox.Location = New System.Drawing.Point(565, 258)
            Me.genderComboBox.Name = "genderComboBox"
            Me.genderComboBox.Size = New System.Drawing.Size(221, 24)
            Me.genderComboBox.TabIndex = 40
            '
            'PictureBox1
            '
            Me.PictureBox1.BackColor = System.Drawing.Color.Transparent
            Me.PictureBox1.BackgroundImage = Global.DatabaseTestApplication2.My.Resources.Resources.CV_HB_Logo_White_400px
            Me.PictureBox1.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Zoom
            Me.PictureBox1.Location = New System.Drawing.Point(720, 31)
            Me.PictureBox1.Name = "PictureBox1"
            Me.PictureBox1.Size = New System.Drawing.Size(237, 107)
            Me.PictureBox1.TabIndex = 39
            Me.PictureBox1.TabStop = False
            '
            'generalInfo
            '
            Me.generalInfo.AutoSize = True
            Me.generalInfo.BackColor = System.Drawing.Color.Transparent
            Me.generalInfo.Font = New System.Drawing.Font("Microsoft YaHei UI", 24.0!, CType((System.Drawing.FontStyle.Bold Or System.Drawing.FontStyle.Italic), System.Drawing.FontStyle), System.Drawing.GraphicsUnit.Point, CType(0, Byte))
            Me.generalInfo.Location = New System.Drawing.Point(7, 42)
            Me.generalInfo.Name = "generalInfo"
            Me.generalInfo.Size = New System.Drawing.Size(271, 52)
            Me.generalInfo.TabIndex = 38
            Me.generalInfo.Text = "General Info"
            '
            'UIDLabel
            '
            Me.UIDLabel.AutoSize = True
            Me.UIDLabel.BackColor = System.Drawing.Color.Transparent
            Me.UIDLabel.ForeColor = System.Drawing.SystemColors.ControlLightLight
            Me.UIDLabel.Location = New System.Drawing.Point(91, 175)
            Me.UIDLabel.Margin = New System.Windows.Forms.Padding(4, 0, 4, 0)
            Me.UIDLabel.Name = "UIDLabel"
            Me.UIDLabel.Size = New System.Drawing.Size(83, 17)
            Me.UIDLabel.TabIndex = 1
            Me.UIDLabel.Text = "Applicant ID"
            '
            'UIDTextBox
            '
            Me.UIDTextBox.BackColor = System.Drawing.SystemColors.Window
            Me.UIDTextBox.Location = New System.Drawing.Point(182, 175)
            Me.UIDTextBox.Margin = New System.Windows.Forms.Padding(4)
            Me.UIDTextBox.Name = "UIDTextBox"
            Me.UIDTextBox.Size = New System.Drawing.Size(221, 22)
            Me.UIDTextBox.TabIndex = 2
            '
            'firstNameLabel
            '
            Me.firstNameLabel.AutoSize = True
            Me.firstNameLabel.BackColor = System.Drawing.Color.Transparent
            Me.firstNameLabel.ForeColor = System.Drawing.SystemColors.ControlLightLight
            Me.firstNameLabel.Location = New System.Drawing.Point(98, 216)
            Me.firstNameLabel.Margin = New System.Windows.Forms.Padding(4, 0, 4, 0)
            Me.firstNameLabel.Name = "firstNameLabel"
            Me.firstNameLabel.Size = New System.Drawing.Size(76, 17)
            Me.firstNameLabel.TabIndex = 3
            Me.firstNameLabel.Text = "First Name"
            '
            'firstNameTextBox
            '
            Me.firstNameTextBox.Location = New System.Drawing.Point(182, 216)
            Me.firstNameTextBox.Margin = New System.Windows.Forms.Padding(4)
            Me.firstNameTextBox.Name = "firstNameTextBox"
            Me.firstNameTextBox.Size = New System.Drawing.Size(221, 22)
            Me.firstNameTextBox.TabIndex = 4
            '
            'lastNameLabel
            '
            Me.lastNameLabel.AutoSize = True
            Me.lastNameLabel.BackColor = System.Drawing.Color.Transparent
            Me.lastNameLabel.ForeColor = System.Drawing.SystemColors.ControlLightLight
            Me.lastNameLabel.Location = New System.Drawing.Point(98, 258)
            Me.lastNameLabel.Margin = New System.Windows.Forms.Padding(4, 0, 4, 0)
            Me.lastNameLabel.Name = "lastNameLabel"
            Me.lastNameLabel.Size = New System.Drawing.Size(76, 17)
            Me.lastNameLabel.TabIndex = 5
            Me.lastNameLabel.Text = "Last Name"
            '
            'lastNameTextBox
            '
            Me.lastNameTextBox.Location = New System.Drawing.Point(182, 258)
            Me.lastNameTextBox.Margin = New System.Windows.Forms.Padding(4)
            Me.lastNameTextBox.Name = "lastNameTextBox"
            Me.lastNameTextBox.Size = New System.Drawing.Size(221, 22)
            Me.lastNameTextBox.TabIndex = 6
            '
            'inquiryDateLabel
            '
            Me.inquiryDateLabel.AutoSize = True
            Me.inquiryDateLabel.BackColor = System.Drawing.Color.Transparent
            Me.inquiryDateLabel.ForeColor = System.Drawing.SystemColors.ControlLightLight
            Me.inquiryDateLabel.Location = New System.Drawing.Point(90, 300)
            Me.inquiryDateLabel.Margin = New System.Windows.Forms.Padding(4, 0, 4, 0)
            Me.inquiryDateLabel.Name = "inquiryDateLabel"
            Me.inquiryDateLabel.Size = New System.Drawing.Size(84, 17)
            Me.inquiryDateLabel.TabIndex = 7
            Me.inquiryDateLabel.Text = "Inquiry Date"
            '
            'inquiryDate_dateTimePicker
            '
            Me.inquiryDate_dateTimePicker.CustomFormat = "MM/dd/yyyy"
            Me.inquiryDate_dateTimePicker.Format = System.Windows.Forms.DateTimePickerFormat.Custom
            Me.inquiryDate_dateTimePicker.Location = New System.Drawing.Point(182, 300)
            Me.inquiryDate_dateTimePicker.Margin = New System.Windows.Forms.Padding(4)
            Me.inquiryDate_dateTimePicker.Name = "inquiryDate_dateTimePicker"
            Me.inquiryDate_dateTimePicker.Size = New System.Drawing.Size(221, 22)
            Me.inquiryDate_dateTimePicker.TabIndex = 8
            Me.inquiryDate_dateTimePicker.Value = New Date(2014, 5, 26, 17, 35, 11, 0)
            '
            'streetAddressLabel
            '
            Me.streetAddressLabel.AutoSize = True
            Me.streetAddressLabel.BackColor = System.Drawing.Color.Transparent
            Me.streetAddressLabel.ForeColor = System.Drawing.SystemColors.ControlLightLight
            Me.streetAddressLabel.Location = New System.Drawing.Point(72, 342)
            Me.streetAddressLabel.Margin = New System.Windows.Forms.Padding(4, 0, 4, 0)
            Me.streetAddressLabel.Name = "streetAddressLabel"
            Me.streetAddressLabel.Size = New System.Drawing.Size(102, 17)
            Me.streetAddressLabel.TabIndex = 9
            Me.streetAddressLabel.Text = "Street Address"
            '
            'streetAddressTextBox
            '
            Me.streetAddressTextBox.Location = New System.Drawing.Point(182, 342)
            Me.streetAddressTextBox.Margin = New System.Windows.Forms.Padding(4)
            Me.streetAddressTextBox.Name = "streetAddressTextBox"
            Me.streetAddressTextBox.Size = New System.Drawing.Size(221, 22)
            Me.streetAddressTextBox.TabIndex = 10
            '
            'cityAddressLabel
            '
            Me.cityAddressLabel.AutoSize = True
            Me.cityAddressLabel.BackColor = System.Drawing.Color.Transparent
            Me.cityAddressLabel.ForeColor = System.Drawing.SystemColors.ControlLightLight
            Me.cityAddressLabel.Location = New System.Drawing.Point(143, 384)
            Me.cityAddressLabel.Margin = New System.Windows.Forms.Padding(4, 0, 4, 0)
            Me.cityAddressLabel.Name = "cityAddressLabel"
            Me.cityAddressLabel.Size = New System.Drawing.Size(31, 17)
            Me.cityAddressLabel.TabIndex = 11
            Me.cityAddressLabel.Text = "City"
            '
            'cityAddressTextBox
            '
            Me.cityAddressTextBox.Location = New System.Drawing.Point(182, 384)
            Me.cityAddressTextBox.Margin = New System.Windows.Forms.Padding(4)
            Me.cityAddressTextBox.Name = "cityAddressTextBox"
            Me.cityAddressTextBox.Size = New System.Drawing.Size(221, 22)
            Me.cityAddressTextBox.TabIndex = 12
            '
            'zipAddressLabel
            '
            Me.zipAddressLabel.AutoSize = True
            Me.zipAddressLabel.BackColor = System.Drawing.Color.Transparent
            Me.zipAddressLabel.ForeColor = System.Drawing.SystemColors.ControlLightLight
            Me.zipAddressLabel.Location = New System.Drawing.Point(109, 467)
            Me.zipAddressLabel.Margin = New System.Windows.Forms.Padding(4, 0, 4, 0)
            Me.zipAddressLabel.Name = "zipAddressLabel"
            Me.zipAddressLabel.Size = New System.Drawing.Size(65, 17)
            Me.zipAddressLabel.TabIndex = 13
            Me.zipAddressLabel.Text = "Zip Code"
            '
            'zipAddressTextBox
            '
            Me.zipAddressTextBox.Location = New System.Drawing.Point(182, 467)
            Me.zipAddressTextBox.Margin = New System.Windows.Forms.Padding(4)
            Me.zipAddressTextBox.Name = "zipAddressTextBox"
            Me.zipAddressTextBox.Size = New System.Drawing.Size(221, 22)
            Me.zipAddressTextBox.TabIndex = 14
            '
            'stateAddressLabel
            '
            Me.stateAddressLabel.AutoSize = True
            Me.stateAddressLabel.BackColor = System.Drawing.Color.Transparent
            Me.stateAddressLabel.ForeColor = System.Drawing.SystemColors.ControlLightLight
            Me.stateAddressLabel.Location = New System.Drawing.Point(133, 426)
            Me.stateAddressLabel.Margin = New System.Windows.Forms.Padding(4, 0, 4, 0)
            Me.stateAddressLabel.Name = "stateAddressLabel"
            Me.stateAddressLabel.Size = New System.Drawing.Size(41, 17)
            Me.stateAddressLabel.TabIndex = 15
            Me.stateAddressLabel.Text = "State"
            '
            'stateAddressTextBox
            '
            Me.stateAddressTextBox.Location = New System.Drawing.Point(182, 426)
            Me.stateAddressTextBox.Margin = New System.Windows.Forms.Padding(4)
            Me.stateAddressTextBox.Name = "stateAddressTextBox"
            Me.stateAddressTextBox.Size = New System.Drawing.Size(221, 22)
            Me.stateAddressTextBox.TabIndex = 16
            '
            'countryAddressLabel
            '
            Me.countryAddressLabel.AutoSize = True
            Me.countryAddressLabel.BackColor = System.Drawing.Color.Transparent
            Me.countryAddressLabel.ForeColor = System.Drawing.SystemColors.ControlLightLight
            Me.countryAddressLabel.Location = New System.Drawing.Point(117, 509)
            Me.countryAddressLabel.Margin = New System.Windows.Forms.Padding(4, 0, 4, 0)
            Me.countryAddressLabel.Name = "countryAddressLabel"
            Me.countryAddressLabel.Size = New System.Drawing.Size(57, 17)
            Me.countryAddressLabel.TabIndex = 17
            Me.countryAddressLabel.Text = "Country"
            '
            'countryAddressTextBox
            '
            Me.countryAddressTextBox.Location = New System.Drawing.Point(182, 509)
            Me.countryAddressTextBox.Margin = New System.Windows.Forms.Padding(4)
            Me.countryAddressTextBox.Name = "countryAddressTextBox"
            Me.countryAddressTextBox.Size = New System.Drawing.Size(221, 22)
            Me.countryAddressTextBox.TabIndex = 18
            '
            'phoneNumberLabel
            '
            Me.phoneNumberLabel.AutoSize = True
            Me.phoneNumberLabel.BackColor = System.Drawing.Color.Transparent
            Me.phoneNumberLabel.ForeColor = System.Drawing.SystemColors.ControlLightLight
            Me.phoneNumberLabel.Location = New System.Drawing.Point(454, 175)
            Me.phoneNumberLabel.Margin = New System.Windows.Forms.Padding(4, 0, 4, 0)
            Me.phoneNumberLabel.Name = "phoneNumberLabel"
            Me.phoneNumberLabel.Size = New System.Drawing.Size(103, 17)
            Me.phoneNumberLabel.TabIndex = 19
            Me.phoneNumberLabel.Text = "Phone Number"
            '
            'phoneNumberTextBox
            '
            Me.phoneNumberTextBox.Location = New System.Drawing.Point(565, 175)
            Me.phoneNumberTextBox.Margin = New System.Windows.Forms.Padding(4)
            Me.phoneNumberTextBox.Name = "phoneNumberTextBox"
            Me.phoneNumberTextBox.Size = New System.Drawing.Size(221, 22)
            Me.phoneNumberTextBox.TabIndex = 20
            '
            'emailLabel
            '
            Me.emailLabel.AutoSize = True
            Me.emailLabel.BackColor = System.Drawing.Color.Transparent
            Me.emailLabel.ForeColor = System.Drawing.SystemColors.ControlLightLight
            Me.emailLabel.Location = New System.Drawing.Point(515, 216)
            Me.emailLabel.Margin = New System.Windows.Forms.Padding(4, 0, 4, 0)
            Me.emailLabel.Name = "emailLabel"
            Me.emailLabel.Size = New System.Drawing.Size(42, 17)
            Me.emailLabel.TabIndex = 21
            Me.emailLabel.Text = "Email"
            '
            'emailTextBox
            '
            Me.emailTextBox.Location = New System.Drawing.Point(565, 216)
            Me.emailTextBox.Margin = New System.Windows.Forms.Padding(4)
            Me.emailTextBox.Name = "emailTextBox"
            Me.emailTextBox.Size = New System.Drawing.Size(221, 22)
            Me.emailTextBox.TabIndex = 22
            '
            'genderLabel
            '
            Me.genderLabel.AutoSize = True
            Me.genderLabel.BackColor = System.Drawing.Color.Transparent
            Me.genderLabel.ForeColor = System.Drawing.SystemColors.ControlLightLight
            Me.genderLabel.Location = New System.Drawing.Point(501, 258)
            Me.genderLabel.Margin = New System.Windows.Forms.Padding(4, 0, 4, 0)
            Me.genderLabel.Name = "genderLabel"
            Me.genderLabel.Size = New System.Drawing.Size(56, 17)
            Me.genderLabel.TabIndex = 23
            Me.genderLabel.Text = "Gender"
            '
            'birthdateLabel
            '
            Me.birthdateLabel.AutoSize = True
            Me.birthdateLabel.BackColor = System.Drawing.Color.Transparent
            Me.birthdateLabel.ForeColor = System.Drawing.SystemColors.ControlLightLight
            Me.birthdateLabel.Location = New System.Drawing.Point(486, 300)
            Me.birthdateLabel.Margin = New System.Windows.Forms.Padding(4, 0, 4, 0)
            Me.birthdateLabel.Name = "birthdateLabel"
            Me.birthdateLabel.Size = New System.Drawing.Size(71, 17)
            Me.birthdateLabel.TabIndex = 25
            Me.birthdateLabel.Text = "Birth Date"
            '
            'birthdate_dateTimePicker
            '
            Me.birthdate_dateTimePicker.CustomFormat = "MM/dd/yyyy"
            Me.birthdate_dateTimePicker.Format = System.Windows.Forms.DateTimePickerFormat.Custom
            Me.birthdate_dateTimePicker.Location = New System.Drawing.Point(565, 300)
            Me.birthdate_dateTimePicker.Margin = New System.Windows.Forms.Padding(4)
            Me.birthdate_dateTimePicker.Name = "birthdate_dateTimePicker"
            Me.birthdate_dateTimePicker.Size = New System.Drawing.Size(221, 22)
            Me.birthdate_dateTimePicker.TabIndex = 26
            Me.birthdate_dateTimePicker.Value = New Date(2014, 5, 26, 17, 35, 11, 0)
            '
            'householdSizeLabel
            '
            Me.householdSizeLabel.AutoSize = True
            Me.householdSizeLabel.BackColor = System.Drawing.Color.Transparent
            Me.householdSizeLabel.ForeColor = System.Drawing.SystemColors.ControlLightLight
            Me.householdSizeLabel.Location = New System.Drawing.Point(450, 342)
            Me.householdSizeLabel.Margin = New System.Windows.Forms.Padding(4, 0, 4, 0)
            Me.householdSizeLabel.Name = "householdSizeLabel"
            Me.householdSizeLabel.Size = New System.Drawing.Size(107, 17)
            Me.householdSizeLabel.TabIndex = 27
            Me.householdSizeLabel.Text = "Household Size"
            '
            'householdSizeTextBox
            '
            Me.householdSizeTextBox.Location = New System.Drawing.Point(565, 342)
            Me.householdSizeTextBox.Margin = New System.Windows.Forms.Padding(4)
            Me.householdSizeTextBox.Name = "householdSizeTextBox"
            Me.householdSizeTextBox.Size = New System.Drawing.Size(221, 22)
            Me.householdSizeTextBox.TabIndex = 28
            '
            'householdAMILabel
            '
            Me.householdAMILabel.AutoSize = True
            Me.householdAMILabel.BackColor = System.Drawing.Color.Transparent
            Me.householdAMILabel.ForeColor = System.Drawing.SystemColors.ControlLightLight
            Me.householdAMILabel.Location = New System.Drawing.Point(454, 384)
            Me.householdAMILabel.Margin = New System.Windows.Forms.Padding(4, 0, 4, 0)
            Me.householdAMILabel.Name = "householdAMILabel"
            Me.householdAMILabel.Size = New System.Drawing.Size(103, 17)
            Me.householdAMILabel.TabIndex = 29
            Me.householdAMILabel.Text = "Household AMI"
            '
            'householdAMITextBox
            '
            Me.householdAMITextBox.Location = New System.Drawing.Point(565, 384)
            Me.householdAMITextBox.Margin = New System.Windows.Forms.Padding(4)
            Me.householdAMITextBox.Name = "householdAMITextBox"
            Me.householdAMITextBox.Size = New System.Drawing.Size(221, 22)
            Me.householdAMITextBox.TabIndex = 30
            '
            'raceLabel
            '
            Me.raceLabel.AutoSize = True
            Me.raceLabel.BackColor = System.Drawing.Color.Transparent
            Me.raceLabel.ForeColor = System.Drawing.SystemColors.ControlLightLight
            Me.raceLabel.Location = New System.Drawing.Point(516, 426)
            Me.raceLabel.Margin = New System.Windows.Forms.Padding(4, 0, 4, 0)
            Me.raceLabel.Name = "raceLabel"
            Me.raceLabel.Size = New System.Drawing.Size(41, 17)
            Me.raceLabel.TabIndex = 31
            Me.raceLabel.Text = "Race"
            '
            'maritalStatusLabel
            '
            Me.maritalStatusLabel.AutoSize = True
            Me.maritalStatusLabel.BackColor = System.Drawing.Color.Transparent
            Me.maritalStatusLabel.ForeColor = System.Drawing.SystemColors.ControlLightLight
            Me.maritalStatusLabel.Location = New System.Drawing.Point(463, 467)
            Me.maritalStatusLabel.Margin = New System.Windows.Forms.Padding(4, 0, 4, 0)
            Me.maritalStatusLabel.Name = "maritalStatusLabel"
            Me.maritalStatusLabel.Size = New System.Drawing.Size(94, 17)
            Me.maritalStatusLabel.TabIndex = 33
            Me.maritalStatusLabel.Text = "Marital Status"
            '
            'notesLabel
            '
            Me.notesLabel.AutoSize = True
            Me.notesLabel.BackColor = System.Drawing.Color.Transparent
            Me.notesLabel.ForeColor = System.Drawing.SystemColors.ControlLightLight
            Me.notesLabel.Location = New System.Drawing.Point(512, 509)
            Me.notesLabel.Margin = New System.Windows.Forms.Padding(4, 0, 4, 0)
            Me.notesLabel.Name = "notesLabel"
            Me.notesLabel.Size = New System.Drawing.Size(45, 17)
            Me.notesLabel.TabIndex = 35
            Me.notesLabel.Text = "Notes"
            '
            'notesTextBox
            '
            Me.notesTextBox.Location = New System.Drawing.Point(565, 509)
            Me.notesTextBox.Margin = New System.Windows.Forms.Padding(4)
            Me.notesTextBox.Name = "notesTextBox"
            Me.notesTextBox.Size = New System.Drawing.Size(221, 22)
            Me.notesTextBox.TabIndex = 36
            '
            'MenuStrip1
            '
            Me.MenuStrip1.ImageScalingSize = New System.Drawing.Size(20, 20)
            Me.MenuStrip1.Items.AddRange(New System.Windows.Forms.ToolStripItem() {Me.MainMenuToolStripMenuItem, Me.HomeownershipToolStripMenuItem, Me.RepairsToolStripMenuItem, Me.TrackingToolStripMenuItem})
            Me.MenuStrip1.Location = New System.Drawing.Point(0, 0)
            Me.MenuStrip1.Name = "MenuStrip1"
            Me.MenuStrip1.Size = New System.Drawing.Size(963, 28)
            Me.MenuStrip1.TabIndex = 37
            Me.MenuStrip1.Text = "MenuStrip1"
            '
            'MainMenuToolStripMenuItem
            '
            Me.MainMenuToolStripMenuItem.Name = "MainMenuToolStripMenuItem"
            Me.MainMenuToolStripMenuItem.Size = New System.Drawing.Size(97, 24)
            Me.MainMenuToolStripMenuItem.Text = "Main Menu"
            '
            'HomeownershipToolStripMenuItem
            '
            Me.HomeownershipToolStripMenuItem.Name = "HomeownershipToolStripMenuItem"
            Me.HomeownershipToolStripMenuItem.Size = New System.Drawing.Size(132, 24)
            Me.HomeownershipToolStripMenuItem.Text = "Homeownership"
            '
            'RepairsToolStripMenuItem
            '
            Me.RepairsToolStripMenuItem.Name = "RepairsToolStripMenuItem"
            Me.RepairsToolStripMenuItem.Size = New System.Drawing.Size(72, 24)
            Me.RepairsToolStripMenuItem.Text = "Repairs"
            '
            'TrackingToolStripMenuItem
            '
            Me.TrackingToolStripMenuItem.Name = "TrackingToolStripMenuItem"
            Me.TrackingToolStripMenuItem.Size = New System.Drawing.Size(78, 24)
            Me.TrackingToolStripMenuItem.Text = "Tracking"
            '
            'panel3
            '
            Me.panel3.Controls.Add(Me.Panel1)
            Me.panel3.Controls.Add(Me.panel4)
            Me.panel3.Controls.Add(Me.panel5)
            Me.panel3.Controls.Add(Me.panel6)
            Me.panel3.Dock = System.Windows.Forms.DockStyle.Fill
            Me.panel3.Location = New System.Drawing.Point(0, 27)
            Me.panel3.Margin = New System.Windows.Forms.Padding(4)
            Me.panel3.Name = "panel3"
            Me.panel3.Size = New System.Drawing.Size(989, 596)
            Me.panel3.TabIndex = 19
            '
            'panel4
            '
            Me.panel4.Dock = System.Windows.Forms.DockStyle.Right
            Me.panel4.Location = New System.Drawing.Point(976, 0)
            Me.panel4.Margin = New System.Windows.Forms.Padding(4)
            Me.panel4.Name = "panel4"
            Me.panel4.Size = New System.Drawing.Size(13, 584)
            Me.panel4.TabIndex = 3
            '
            'panel5
            '
            Me.panel5.Dock = System.Windows.Forms.DockStyle.Left
            Me.panel5.Location = New System.Drawing.Point(0, 0)
            Me.panel5.Margin = New System.Windows.Forms.Padding(4)
            Me.panel5.Name = "panel5"
            Me.panel5.Size = New System.Drawing.Size(13, 584)
            Me.panel5.TabIndex = 5
            '
            'panel6
            '
            Me.panel6.Dock = System.Windows.Forms.DockStyle.Bottom
            Me.panel6.Location = New System.Drawing.Point(0, 584)
            Me.panel6.Margin = New System.Windows.Forms.Padding(4)
            Me.panel6.Name = "panel6"
            Me.panel6.Size = New System.Drawing.Size(989, 12)
            Me.panel6.TabIndex = 6
            '
            'frmgeneral
            '
            Me.AutoScaleDimensions = New System.Drawing.SizeF(8.0!, 16.0!)
            Me.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font
            Me.ClientSize = New System.Drawing.Size(989, 623)
            Me.Controls.Add(Me.panel3)
            Me.Controls.Add(Me.BindingNavigator1)
            Me.MainMenuStrip = Me.MenuStrip1
            Me.Margin = New System.Windows.Forms.Padding(4)
            Me.Name = "frmgeneral"
            Me.Text = "General"
            CType(Me.BindingNavigator1, System.ComponentModel.ISupportInitialize).EndInit()
            Me.BindingNavigator1.ResumeLayout(False)
            Me.BindingNavigator1.PerformLayout()
            CType(Me.generalBindingSource, System.ComponentModel.ISupportInitialize).EndInit()
            CType(Me.ErrorProvider1, System.ComponentModel.ISupportInitialize).EndInit()
            Me.Panel1.ResumeLayout(False)
            Me.Panel1.PerformLayout()
            CType(Me.PictureBox1, System.ComponentModel.ISupportInitialize).EndInit()
            Me.MenuStrip1.ResumeLayout(False)
            Me.MenuStrip1.PerformLayout()
            Me.panel3.ResumeLayout(False)
            Me.panel3.PerformLayout()
            Me.ResumeLayout(False)
            Me.PerformLayout()

        End Sub
        Friend WithEvents BindingNavigator1 As System.Windows.Forms.BindingNavigator
		Friend WithEvents BindingNavigatorAddNewItem As System.Windows.Forms.ToolStripButton
		Friend WithEvents BindingNavigatorCountItem As System.Windows.Forms.ToolStripLabel
		Friend WithEvents BindingNavigatorDeleteItem As System.Windows.Forms.ToolStripButton
		Friend WithEvents BindingNavigatorMoveFirstItem As System.Windows.Forms.ToolStripButton
		Friend WithEvents BindingNavigatorMovePreviousItem As System.Windows.Forms.ToolStripButton
		Friend WithEvents BindingNavigatorSeparator As System.Windows.Forms.ToolStripSeparator
		Friend WithEvents BindingNavigatorPositionItem As System.Windows.Forms.ToolStripTextBox
		Friend WithEvents BindingNavigatorSeparator1 As System.Windows.Forms.ToolStripSeparator
		Friend WithEvents BindingNavigatorMoveNextItem As System.Windows.Forms.ToolStripButton
		Friend WithEvents BindingNavigatorMoveLastItem As System.Windows.Forms.ToolStripButton
		Friend WithEvents BindingNavigatorSeparator2 As System.Windows.Forms.ToolStripSeparator
		Friend WithEvents ToolStripButton1 As System.Windows.Forms.ToolStripButton
		Friend WithEvents ErrorProvider1 As System.Windows.Forms.ErrorProvider
		Friend WithEvents Panel1 As System.Windows.Forms.Panel
		Friend WithEvents generalBindingSource As System.Windows.Forms.BindingSource
		Friend WithEvents UIDTextBox As System.Windows.Forms.TextBox
		Friend WithEvents UIDLabel As System.Windows.Forms.Label
		Friend WithEvents firstNameTextBox As System.Windows.Forms.TextBox
		Friend WithEvents firstNameLabel As System.Windows.Forms.Label
		Friend WithEvents lastNameTextBox As System.Windows.Forms.TextBox
		Friend WithEvents lastNameLabel As System.Windows.Forms.Label
		Friend WithEvents inquiryDate_dateTimePicker As System.Windows.Forms.DateTimePicker
		Friend WithEvents inquiryDateLabel As System.Windows.Forms.Label
		Friend WithEvents streetAddressTextBox As System.Windows.Forms.TextBox
		Friend WithEvents streetAddressLabel As System.Windows.Forms.Label
		Friend WithEvents cityAddressTextBox As System.Windows.Forms.TextBox
		Friend WithEvents cityAddressLabel As System.Windows.Forms.Label
		Friend WithEvents zipAddressTextBox As System.Windows.Forms.TextBox
		Friend WithEvents zipAddressLabel As System.Windows.Forms.Label
		Friend WithEvents stateAddressTextBox As System.Windows.Forms.TextBox
		Friend WithEvents stateAddressLabel As System.Windows.Forms.Label
		Friend WithEvents countryAddressTextBox As System.Windows.Forms.TextBox
		Friend WithEvents countryAddressLabel As System.Windows.Forms.Label
		Friend WithEvents phoneNumberTextBox As System.Windows.Forms.TextBox
		Friend WithEvents phoneNumberLabel As System.Windows.Forms.Label
		Friend WithEvents emailTextBox As System.Windows.Forms.TextBox
		Friend WithEvents emailLabel As System.Windows.Forms.Label
        Friend WithEvents genderLabel As System.Windows.Forms.Label
        Friend WithEvents birthdate_dateTimePicker As System.Windows.Forms.DateTimePicker
        Friend WithEvents birthdateLabel As System.Windows.Forms.Label
        Friend WithEvents householdSizeTextBox As System.Windows.Forms.TextBox
        Friend WithEvents householdSizeLabel As System.Windows.Forms.Label
        Friend WithEvents householdAMITextBox As System.Windows.Forms.TextBox
        Friend WithEvents householdAMILabel As System.Windows.Forms.Label
        Friend WithEvents raceLabel As System.Windows.Forms.Label
        Friend WithEvents maritalStatusLabel As System.Windows.Forms.Label
        Friend WithEvents notesTextBox As System.Windows.Forms.TextBox
        Friend WithEvents notesLabel As System.Windows.Forms.Label
        Friend WithEvents panel3 As System.Windows.Forms.Panel
        Friend WithEvents panel4 As System.Windows.Forms.Panel
        Friend WithEvents panel5 As System.Windows.Forms.Panel
        Friend WithEvents panel6 As System.Windows.Forms.Panel
        Friend WithEvents MenuStrip1 As MenuStrip
        Friend WithEvents MainMenuToolStripMenuItem As ToolStripMenuItem
        Friend WithEvents HomeownershipToolStripMenuItem As ToolStripMenuItem
        Friend WithEvents RepairsToolStripMenuItem As ToolStripMenuItem
        Friend WithEvents TrackingToolStripMenuItem As ToolStripMenuItem
        Friend WithEvents generalInfo As Label
        Friend WithEvents PictureBox1 As PictureBox
        Friend WithEvents genderComboBox As ComboBox
        Friend WithEvents maritalStatusComboBox As ComboBox
        Friend WithEvents raceComboBox As ComboBox
    End Class

End Namespace
