' ++++++++++++++++++++++++++++++++++++++++++++++++++
' This code is generated by a tool and is provided "as is", without warranty of any kind,
' express or implied, including but not limited to the warranties of merchantability,
' fitness for a particular purpose and non-infringement.
' In no event shall the authors or copyright holders be liable for any claim, damages or
' other liability, whether in an action of contract, tort or otherwise, arising from,
' out of or in connection with the software or the use or other dealings in the software.
' ++++++++++++++++++++++++++++++++++++++++++++++++++
' 

Namespace DatabaseTestApplication2
	
	<Global.Microsoft.VisualBasic.CompilerServices.DesignerGenerated()> _
	Partial Class frmhomeownership
		Inherits System.Windows.Forms.Form
		
		'Form overrides dispose to clean up the component list.
		<System.Diagnostics.DebuggerNonUserCode()> _
		Protected Overrides Sub Dispose(ByVal disposing As Boolean)
			Try
			If disposing AndAlso components IsNot Nothing Then
				components.Dispose()
			End If
			Finally
			MyBase.Dispose(disposing)
			End Try
		End Sub
		
		'Required by the Windows Form Designer
		Private components As System.ComponentModel.IContainer
		
		'NOTE: The following procedure is required by the Windows Form Designer
		'It can be modified using the Windows Form Designer.  
		'Do not modify it using the code editor.
		<System.Diagnostics.DebuggerStepThrough()> _
		Private Sub InitializeComponent()
            Me.components = New System.ComponentModel.Container()
            Dim resources As System.ComponentModel.ComponentResourceManager = New System.ComponentModel.ComponentResourceManager(GetType(frmhomeownership))
            Me.BindingNavigator1 = New System.Windows.Forms.BindingNavigator(Me.components)
            Me.homeownershipBindingSource = New System.Windows.Forms.BindingSource(Me.components)
            Me.BindingNavigatorCountItem = New System.Windows.Forms.ToolStripLabel()
            Me.BindingNavigatorDeleteItem = New System.Windows.Forms.ToolStripButton()
            Me.BindingNavigatorMoveFirstItem = New System.Windows.Forms.ToolStripButton()
            Me.BindingNavigatorMovePreviousItem = New System.Windows.Forms.ToolStripButton()
            Me.BindingNavigatorSeparator = New System.Windows.Forms.ToolStripSeparator()
            Me.BindingNavigatorPositionItem = New System.Windows.Forms.ToolStripTextBox()
            Me.BindingNavigatorSeparator1 = New System.Windows.Forms.ToolStripSeparator()
            Me.BindingNavigatorMoveNextItem = New System.Windows.Forms.ToolStripButton()
            Me.BindingNavigatorMoveLastItem = New System.Windows.Forms.ToolStripButton()
            Me.BindingNavigatorSeparator2 = New System.Windows.Forms.ToolStripSeparator()
            Me.BindingNavigatorAddNewItem = New System.Windows.Forms.ToolStripButton()
            Me.ToolStripButton1 = New System.Windows.Forms.ToolStripButton()
            Me.ErrorProvider1 = New System.Windows.Forms.ErrorProvider(Me.components)
            Me.Panel1 = New System.Windows.Forms.Panel()
            Me.applicantInfoMeetingLabel = New System.Windows.Forms.Label()
            Me.applicantInfoMeeting_dateTimePicker = New System.Windows.Forms.DateTimePicker()
            Me.applicationChecklist1Label = New System.Windows.Forms.Label()
            Me.applicationChecklist1_dateTimePicker = New System.Windows.Forms.DateTimePicker()
            Me.applicationChecklist2Label = New System.Windows.Forms.Label()
            Me.applicationChecklist2_dateTimePicker = New System.Windows.Forms.DateTimePicker()
            Me.employmentVerifiedLabel = New System.Windows.Forms.Label()
            Me.employmentVerifiedTextBox = New System.Windows.Forms.TextBox()
            Me.landlordReferenceLabel = New System.Windows.Forms.Label()
            Me.landlordReferenceTextBox = New System.Windows.Forms.TextBox()
            Me.previousLandlordReferenceLabel = New System.Windows.Forms.Label()
            Me.previousLandlordReferenceTextBox = New System.Windows.Forms.TextBox()
            Me.backgroundCheckLabel = New System.Windows.Forms.Label()
            Me.backgroundCheckTextBox = New System.Windows.Forms.TextBox()
            Me.CCCBudgetLabel = New System.Windows.Forms.Label()
            Me.CCCBudgetTextBox = New System.Windows.Forms.TextBox()
            Me.creditReportRunLabel = New System.Windows.Forms.Label()
            Me.creditReportRunTextBox = New System.Windows.Forms.TextBox()
            Me.homeVisitLabel = New System.Windows.Forms.Label()
            Me.homeVisit_dateTimePicker = New System.Windows.Forms.DateTimePicker()
            Me.committeeDecisionLabel = New System.Windows.Forms.Label()
            Me.committeeDecision_dateTimePicker = New System.Windows.Forms.DateTimePicker()
            Me.committeeAcceptedLabel = New System.Windows.Forms.Label()
            Me.committeeAcceptedTextBox = New System.Windows.Forms.TextBox()
            Me.committeeReasonLabel = New System.Windows.Forms.Label()
            Me.committeeReasonTextBox = New System.Windows.Forms.TextBox()
            Me.boardVoteLabel = New System.Windows.Forms.Label()
            Me.boardVote_dateTimePicker = New System.Windows.Forms.DateTimePicker()
            Me.boardAcceptedLabel = New System.Windows.Forms.Label()
            Me.boardAcceptedTextBox = New System.Windows.Forms.TextBox()
            Me.boardReasonLabel = New System.Windows.Forms.Label()
            Me.boardReasonTextBox = New System.Windows.Forms.TextBox()
            Me.handbookReviewLabel = New System.Windows.Forms.Label()
            Me.handbookReview_dateTimePicker = New System.Windows.Forms.DateTimePicker()
            Me.general_UIDLabel = New System.Windows.Forms.Label()
            Me.general_UID_comboBox = New System.Windows.Forms.ComboBox()
            Me.panel3 = New System.Windows.Forms.Panel()
            Me.panel4 = New System.Windows.Forms.Panel()
            Me.panel5 = New System.Windows.Forms.Panel()
            Me.panel6 = New System.Windows.Forms.Panel()
            Me.MenuStrip2 = New System.Windows.Forms.MenuStrip()
            Me.ToolStripMenuItem1 = New System.Windows.Forms.ToolStripMenuItem()
            Me.ToolStripMenuItem2 = New System.Windows.Forms.ToolStripMenuItem()
            Me.ToolStripMenuItem3 = New System.Windows.Forms.ToolStripMenuItem()
            Me.ToolStripMenuItem4 = New System.Windows.Forms.ToolStripMenuItem()
            Me.TrackingToolStripMenuItem = New System.Windows.Forms.ToolStripMenuItem()
            Me.ToolStripMenuItem5 = New System.Windows.Forms.ToolStripMenuItem()
            Me.SurveyToolStripMenuItem = New System.Windows.Forms.ToolStripMenuItem()
            CType(Me.BindingNavigator1, System.ComponentModel.ISupportInitialize).BeginInit()
            Me.BindingNavigator1.SuspendLayout()
            CType(Me.homeownershipBindingSource, System.ComponentModel.ISupportInitialize).BeginInit()
            CType(Me.ErrorProvider1, System.ComponentModel.ISupportInitialize).BeginInit()
            Me.Panel1.SuspendLayout()
            Me.panel3.SuspendLayout()
            Me.MenuStrip2.SuspendLayout()
            Me.SuspendLayout()
            '
            'BindingNavigator1
            '
            Me.BindingNavigator1.AddNewItem = Nothing
            Me.BindingNavigator1.BindingSource = Me.homeownershipBindingSource
            Me.BindingNavigator1.CountItem = Me.BindingNavigatorCountItem
            Me.BindingNavigator1.DeleteItem = Me.BindingNavigatorDeleteItem
            Me.BindingNavigator1.ImageScalingSize = New System.Drawing.Size(20, 20)
            Me.BindingNavigator1.Items.AddRange(New System.Windows.Forms.ToolStripItem() {Me.BindingNavigatorMoveFirstItem, Me.BindingNavigatorMovePreviousItem, Me.BindingNavigatorSeparator, Me.BindingNavigatorPositionItem, Me.BindingNavigatorCountItem, Me.BindingNavigatorSeparator1, Me.BindingNavigatorMoveNextItem, Me.BindingNavigatorMoveLastItem, Me.BindingNavigatorSeparator2, Me.BindingNavigatorAddNewItem, Me.BindingNavigatorDeleteItem, Me.ToolStripButton1})
            Me.BindingNavigator1.Location = New System.Drawing.Point(0, 0)
            Me.BindingNavigator1.MoveFirstItem = Me.BindingNavigatorMoveFirstItem
            Me.BindingNavigator1.MoveLastItem = Me.BindingNavigatorMoveLastItem
            Me.BindingNavigator1.MoveNextItem = Me.BindingNavigatorMoveNextItem
            Me.BindingNavigator1.MovePreviousItem = Me.BindingNavigatorMovePreviousItem
            Me.BindingNavigator1.Name = "BindingNavigator1"
            Me.BindingNavigator1.Padding = New System.Windows.Forms.Padding(10, 0, 10, 0)
            Me.BindingNavigator1.PositionItem = Me.BindingNavigatorPositionItem
            Me.BindingNavigator1.Size = New System.Drawing.Size(892, 27)
            Me.BindingNavigator1.TabIndex = 0
            Me.BindingNavigator1.Text = "BindingNavigator1"
            '
            'BindingNavigatorCountItem
            '
            Me.BindingNavigatorCountItem.Name = "BindingNavigatorCountItem"
            Me.BindingNavigatorCountItem.Size = New System.Drawing.Size(35, 24)
            Me.BindingNavigatorCountItem.Text = "of {0}"
            Me.BindingNavigatorCountItem.ToolTipText = "Total number of items"
            '
            'BindingNavigatorDeleteItem
            '
            Me.BindingNavigatorDeleteItem.DisplayStyle = System.Windows.Forms.ToolStripItemDisplayStyle.Image
            Me.BindingNavigatorDeleteItem.Image = CType(resources.GetObject("BindingNavigatorDeleteItem.Image"), System.Drawing.Image)
            Me.BindingNavigatorDeleteItem.Name = "BindingNavigatorDeleteItem"
            Me.BindingNavigatorDeleteItem.RightToLeftAutoMirrorImage = True
            Me.BindingNavigatorDeleteItem.Size = New System.Drawing.Size(24, 24)
            Me.BindingNavigatorDeleteItem.Text = "Delete"
            '
            'BindingNavigatorMoveFirstItem
            '
            Me.BindingNavigatorMoveFirstItem.DisplayStyle = System.Windows.Forms.ToolStripItemDisplayStyle.Image
            Me.BindingNavigatorMoveFirstItem.Image = CType(resources.GetObject("BindingNavigatorMoveFirstItem.Image"), System.Drawing.Image)
            Me.BindingNavigatorMoveFirstItem.Name = "BindingNavigatorMoveFirstItem"
            Me.BindingNavigatorMoveFirstItem.RightToLeftAutoMirrorImage = True
            Me.BindingNavigatorMoveFirstItem.Size = New System.Drawing.Size(24, 24)
            Me.BindingNavigatorMoveFirstItem.Text = "Move first"
            '
            'BindingNavigatorMovePreviousItem
            '
            Me.BindingNavigatorMovePreviousItem.DisplayStyle = System.Windows.Forms.ToolStripItemDisplayStyle.Image
            Me.BindingNavigatorMovePreviousItem.Image = CType(resources.GetObject("BindingNavigatorMovePreviousItem.Image"), System.Drawing.Image)
            Me.BindingNavigatorMovePreviousItem.Name = "BindingNavigatorMovePreviousItem"
            Me.BindingNavigatorMovePreviousItem.RightToLeftAutoMirrorImage = True
            Me.BindingNavigatorMovePreviousItem.Size = New System.Drawing.Size(24, 24)
            Me.BindingNavigatorMovePreviousItem.Text = "Move previous"
            '
            'BindingNavigatorSeparator
            '
            Me.BindingNavigatorSeparator.Name = "BindingNavigatorSeparator"
            Me.BindingNavigatorSeparator.Size = New System.Drawing.Size(6, 27)
            '
            'BindingNavigatorPositionItem
            '
            Me.BindingNavigatorPositionItem.AccessibleName = "Position"
            Me.BindingNavigatorPositionItem.AutoSize = False
            Me.BindingNavigatorPositionItem.Font = New System.Drawing.Font("Segoe UI", 9.0!)
            Me.BindingNavigatorPositionItem.Name = "BindingNavigatorPositionItem"
            Me.BindingNavigatorPositionItem.Size = New System.Drawing.Size(50, 23)
            Me.BindingNavigatorPositionItem.Text = "0"
            Me.BindingNavigatorPositionItem.ToolTipText = "Current position"
            '
            'BindingNavigatorSeparator1
            '
            Me.BindingNavigatorSeparator1.Name = "BindingNavigatorSeparator1"
            Me.BindingNavigatorSeparator1.Size = New System.Drawing.Size(6, 27)
            '
            'BindingNavigatorMoveNextItem
            '
            Me.BindingNavigatorMoveNextItem.DisplayStyle = System.Windows.Forms.ToolStripItemDisplayStyle.Image
            Me.BindingNavigatorMoveNextItem.Image = CType(resources.GetObject("BindingNavigatorMoveNextItem.Image"), System.Drawing.Image)
            Me.BindingNavigatorMoveNextItem.Name = "BindingNavigatorMoveNextItem"
            Me.BindingNavigatorMoveNextItem.RightToLeftAutoMirrorImage = True
            Me.BindingNavigatorMoveNextItem.Size = New System.Drawing.Size(24, 24)
            Me.BindingNavigatorMoveNextItem.Text = "Move next"
            '
            'BindingNavigatorMoveLastItem
            '
            Me.BindingNavigatorMoveLastItem.DisplayStyle = System.Windows.Forms.ToolStripItemDisplayStyle.Image
            Me.BindingNavigatorMoveLastItem.Image = CType(resources.GetObject("BindingNavigatorMoveLastItem.Image"), System.Drawing.Image)
            Me.BindingNavigatorMoveLastItem.Name = "BindingNavigatorMoveLastItem"
            Me.BindingNavigatorMoveLastItem.RightToLeftAutoMirrorImage = True
            Me.BindingNavigatorMoveLastItem.Size = New System.Drawing.Size(24, 24)
            Me.BindingNavigatorMoveLastItem.Text = "Move last"
            '
            'BindingNavigatorSeparator2
            '
            Me.BindingNavigatorSeparator2.Name = "BindingNavigatorSeparator2"
            Me.BindingNavigatorSeparator2.Size = New System.Drawing.Size(6, 27)
            '
            'BindingNavigatorAddNewItem
            '
            Me.BindingNavigatorAddNewItem.DisplayStyle = System.Windows.Forms.ToolStripItemDisplayStyle.Image
            Me.BindingNavigatorAddNewItem.Image = CType(resources.GetObject("BindingNavigatorAddNewItem.Image"), System.Drawing.Image)
            Me.BindingNavigatorAddNewItem.Name = "BindingNavigatorAddNewItem"
            Me.BindingNavigatorAddNewItem.RightToLeftAutoMirrorImage = True
            Me.BindingNavigatorAddNewItem.Size = New System.Drawing.Size(24, 24)
            Me.BindingNavigatorAddNewItem.Text = "Add new"
            '
            'ToolStripButton1
            '
            Me.ToolStripButton1.DisplayStyle = System.Windows.Forms.ToolStripItemDisplayStyle.Image
            Me.ToolStripButton1.Image = CType(resources.GetObject("ToolStripButton1.Image"), System.Drawing.Image)
            Me.ToolStripButton1.ImageTransparentColor = System.Drawing.Color.Magenta
            Me.ToolStripButton1.Name = "ToolStripButton1"
            Me.ToolStripButton1.Size = New System.Drawing.Size(24, 24)
            Me.ToolStripButton1.Text = "Save"
            '
            'ErrorProvider1
            '
            Me.ErrorProvider1.ContainerControl = Me
            '
            'Panel1
            '
            Me.Panel1.AutoScroll = True
            Me.Panel1.AutoSize = True
            Me.Panel1.Controls.Add(Me.MenuStrip2)
            Me.Panel1.Controls.Add(Me.applicantInfoMeetingLabel)
            Me.Panel1.Controls.Add(Me.applicantInfoMeeting_dateTimePicker)
            Me.Panel1.Controls.Add(Me.applicationChecklist1Label)
            Me.Panel1.Controls.Add(Me.applicationChecklist1_dateTimePicker)
            Me.Panel1.Controls.Add(Me.applicationChecklist2Label)
            Me.Panel1.Controls.Add(Me.applicationChecklist2_dateTimePicker)
            Me.Panel1.Controls.Add(Me.employmentVerifiedLabel)
            Me.Panel1.Controls.Add(Me.employmentVerifiedTextBox)
            Me.Panel1.Controls.Add(Me.landlordReferenceLabel)
            Me.Panel1.Controls.Add(Me.landlordReferenceTextBox)
            Me.Panel1.Controls.Add(Me.previousLandlordReferenceLabel)
            Me.Panel1.Controls.Add(Me.previousLandlordReferenceTextBox)
            Me.Panel1.Controls.Add(Me.backgroundCheckLabel)
            Me.Panel1.Controls.Add(Me.backgroundCheckTextBox)
            Me.Panel1.Controls.Add(Me.CCCBudgetLabel)
            Me.Panel1.Controls.Add(Me.CCCBudgetTextBox)
            Me.Panel1.Controls.Add(Me.creditReportRunLabel)
            Me.Panel1.Controls.Add(Me.creditReportRunTextBox)
            Me.Panel1.Controls.Add(Me.homeVisitLabel)
            Me.Panel1.Controls.Add(Me.homeVisit_dateTimePicker)
            Me.Panel1.Controls.Add(Me.committeeDecisionLabel)
            Me.Panel1.Controls.Add(Me.committeeDecision_dateTimePicker)
            Me.Panel1.Controls.Add(Me.committeeAcceptedLabel)
            Me.Panel1.Controls.Add(Me.committeeAcceptedTextBox)
            Me.Panel1.Controls.Add(Me.committeeReasonLabel)
            Me.Panel1.Controls.Add(Me.committeeReasonTextBox)
            Me.Panel1.Controls.Add(Me.boardVoteLabel)
            Me.Panel1.Controls.Add(Me.boardVote_dateTimePicker)
            Me.Panel1.Controls.Add(Me.boardAcceptedLabel)
            Me.Panel1.Controls.Add(Me.boardAcceptedTextBox)
            Me.Panel1.Controls.Add(Me.boardReasonLabel)
            Me.Panel1.Controls.Add(Me.boardReasonTextBox)
            Me.Panel1.Controls.Add(Me.handbookReviewLabel)
            Me.Panel1.Controls.Add(Me.handbookReview_dateTimePicker)
            Me.Panel1.Controls.Add(Me.general_UIDLabel)
            Me.Panel1.Controls.Add(Me.general_UID_comboBox)
            Me.Panel1.Dock = System.Windows.Forms.DockStyle.Fill
            Me.Panel1.Location = New System.Drawing.Point(10, 0)
            Me.Panel1.Margin = New System.Windows.Forms.Padding(10, 3, 10, 3)
            Me.Panel1.Name = "Panel1"
            Me.Panel1.Size = New System.Drawing.Size(872, 359)
            Me.Panel1.TabIndex = 1
            '
            'applicantInfoMeetingLabel
            '
            Me.applicantInfoMeetingLabel.AutoSize = True
            Me.applicantInfoMeetingLabel.Location = New System.Drawing.Point(110, 50)
            Me.applicantInfoMeetingLabel.Name = "applicantInfoMeetingLabel"
            Me.applicantInfoMeetingLabel.Size = New System.Drawing.Size(113, 13)
            Me.applicantInfoMeetingLabel.TabIndex = 1
            Me.applicantInfoMeetingLabel.Text = "Applicant Info Meeting"
            '
            'applicantInfoMeeting_dateTimePicker
            '
            Me.applicantInfoMeeting_dateTimePicker.CustomFormat = "dd/MM/yyyy"
            Me.applicantInfoMeeting_dateTimePicker.Format = System.Windows.Forms.DateTimePickerFormat.Custom
            Me.applicantInfoMeeting_dateTimePicker.Location = New System.Drawing.Point(244, 50)
            Me.applicantInfoMeeting_dateTimePicker.Name = "applicantInfoMeeting_dateTimePicker"
            Me.applicantInfoMeeting_dateTimePicker.Size = New System.Drawing.Size(200, 20)
            Me.applicantInfoMeeting_dateTimePicker.TabIndex = 2
            Me.applicantInfoMeeting_dateTimePicker.Value = New Date(2014, 5, 26, 17, 35, 11, 0)
            '
            'applicationChecklist1Label
            '
            Me.applicationChecklist1Label.AutoSize = True
            Me.applicationChecklist1Label.Location = New System.Drawing.Point(109, 84)
            Me.applicationChecklist1Label.Name = "applicationChecklist1Label"
            Me.applicationChecklist1Label.Size = New System.Drawing.Size(114, 13)
            Me.applicationChecklist1Label.TabIndex = 3
            Me.applicationChecklist1Label.Text = "Application Checklist 1"
            '
            'applicationChecklist1_dateTimePicker
            '
            Me.applicationChecklist1_dateTimePicker.CustomFormat = "dd/MM/yyyy"
            Me.applicationChecklist1_dateTimePicker.Format = System.Windows.Forms.DateTimePickerFormat.Custom
            Me.applicationChecklist1_dateTimePicker.Location = New System.Drawing.Point(244, 84)
            Me.applicationChecklist1_dateTimePicker.Name = "applicationChecklist1_dateTimePicker"
            Me.applicationChecklist1_dateTimePicker.Size = New System.Drawing.Size(200, 20)
            Me.applicationChecklist1_dateTimePicker.TabIndex = 4
            Me.applicationChecklist1_dateTimePicker.Value = New Date(2014, 5, 26, 17, 35, 11, 0)
            '
            'applicationChecklist2Label
            '
            Me.applicationChecklist2Label.AutoSize = True
            Me.applicationChecklist2Label.Location = New System.Drawing.Point(109, 118)
            Me.applicationChecklist2Label.Name = "applicationChecklist2Label"
            Me.applicationChecklist2Label.Size = New System.Drawing.Size(114, 13)
            Me.applicationChecklist2Label.TabIndex = 5
            Me.applicationChecklist2Label.Text = "Application Checklist 2"
            '
            'applicationChecklist2_dateTimePicker
            '
            Me.applicationChecklist2_dateTimePicker.CustomFormat = "dd/MM/yyyy"
            Me.applicationChecklist2_dateTimePicker.Format = System.Windows.Forms.DateTimePickerFormat.Custom
            Me.applicationChecklist2_dateTimePicker.Location = New System.Drawing.Point(244, 118)
            Me.applicationChecklist2_dateTimePicker.Name = "applicationChecklist2_dateTimePicker"
            Me.applicationChecklist2_dateTimePicker.Size = New System.Drawing.Size(200, 20)
            Me.applicationChecklist2_dateTimePicker.TabIndex = 6
            Me.applicationChecklist2_dateTimePicker.Value = New Date(2014, 5, 26, 17, 35, 11, 0)
            '
            'employmentVerifiedLabel
            '
            Me.employmentVerifiedLabel.AutoSize = True
            Me.employmentVerifiedLabel.Location = New System.Drawing.Point(524, 193)
            Me.employmentVerifiedLabel.Name = "employmentVerifiedLabel"
            Me.employmentVerifiedLabel.Size = New System.Drawing.Size(102, 13)
            Me.employmentVerifiedLabel.TabIndex = 7
            Me.employmentVerifiedLabel.Text = "Employment Verified"
            '
            'employmentVerifiedTextBox
            '
            Me.employmentVerifiedTextBox.Location = New System.Drawing.Point(648, 186)
            Me.employmentVerifiedTextBox.Name = "employmentVerifiedTextBox"
            Me.employmentVerifiedTextBox.Size = New System.Drawing.Size(100, 20)
            Me.employmentVerifiedTextBox.TabIndex = 8
            '
            'landlordReferenceLabel
            '
            Me.landlordReferenceLabel.AutoSize = True
            Me.landlordReferenceLabel.Location = New System.Drawing.Point(122, 186)
            Me.landlordReferenceLabel.Name = "landlordReferenceLabel"
            Me.landlordReferenceLabel.Size = New System.Drawing.Size(101, 13)
            Me.landlordReferenceLabel.TabIndex = 9
            Me.landlordReferenceLabel.Text = "Landlord Reference"
            '
            'landlordReferenceTextBox
            '
            Me.landlordReferenceTextBox.Location = New System.Drawing.Point(244, 186)
            Me.landlordReferenceTextBox.Name = "landlordReferenceTextBox"
            Me.landlordReferenceTextBox.Size = New System.Drawing.Size(100, 20)
            Me.landlordReferenceTextBox.TabIndex = 10
            '
            'previousLandlordReferenceLabel
            '
            Me.previousLandlordReferenceLabel.AutoSize = True
            Me.previousLandlordReferenceLabel.Location = New System.Drawing.Point(78, 220)
            Me.previousLandlordReferenceLabel.Name = "previousLandlordReferenceLabel"
            Me.previousLandlordReferenceLabel.Size = New System.Drawing.Size(145, 13)
            Me.previousLandlordReferenceLabel.TabIndex = 11
            Me.previousLandlordReferenceLabel.Text = "Previous Landlord Reference"
            '
            'previousLandlordReferenceTextBox
            '
            Me.previousLandlordReferenceTextBox.Location = New System.Drawing.Point(244, 220)
            Me.previousLandlordReferenceTextBox.Name = "previousLandlordReferenceTextBox"
            Me.previousLandlordReferenceTextBox.Size = New System.Drawing.Size(100, 20)
            Me.previousLandlordReferenceTextBox.TabIndex = 12
            '
            'backgroundCheckLabel
            '
            Me.backgroundCheckLabel.AutoSize = True
            Me.backgroundCheckLabel.Location = New System.Drawing.Point(121, 254)
            Me.backgroundCheckLabel.Name = "backgroundCheckLabel"
            Me.backgroundCheckLabel.Size = New System.Drawing.Size(99, 13)
            Me.backgroundCheckLabel.TabIndex = 13
            Me.backgroundCheckLabel.Text = "Background Check"
            '
            'backgroundCheckTextBox
            '
            Me.backgroundCheckTextBox.Location = New System.Drawing.Point(244, 254)
            Me.backgroundCheckTextBox.Name = "backgroundCheckTextBox"
            Me.backgroundCheckTextBox.Size = New System.Drawing.Size(100, 20)
            Me.backgroundCheckTextBox.TabIndex = 14
            '
            'CCCBudgetLabel
            '
            Me.CCCBudgetLabel.AutoSize = True
            Me.CCCBudgetLabel.Location = New System.Drawing.Point(154, 288)
            Me.CCCBudgetLabel.Name = "CCCBudgetLabel"
            Me.CCCBudgetLabel.Size = New System.Drawing.Size(65, 13)
            Me.CCCBudgetLabel.TabIndex = 15
            Me.CCCBudgetLabel.Text = "CCC Budget"
            '
            'CCCBudgetTextBox
            '
            Me.CCCBudgetTextBox.Location = New System.Drawing.Point(244, 288)
            Me.CCCBudgetTextBox.Name = "CCCBudgetTextBox"
            Me.CCCBudgetTextBox.Size = New System.Drawing.Size(100, 20)
            Me.CCCBudgetTextBox.TabIndex = 16
            '
            'creditReportRunLabel
            '
            Me.creditReportRunLabel.AutoSize = True
            Me.creditReportRunLabel.Location = New System.Drawing.Point(131, 325)
            Me.creditReportRunLabel.Name = "creditReportRunLabel"
            Me.creditReportRunLabel.Size = New System.Drawing.Size(92, 13)
            Me.creditReportRunLabel.TabIndex = 17
            Me.creditReportRunLabel.Text = "Credit Report Run"
            '
            'creditReportRunTextBox
            '
            Me.creditReportRunTextBox.Location = New System.Drawing.Point(244, 322)
            Me.creditReportRunTextBox.Name = "creditReportRunTextBox"
            Me.creditReportRunTextBox.Size = New System.Drawing.Size(100, 20)
            Me.creditReportRunTextBox.TabIndex = 18
            '
            'homeVisitLabel
            '
            Me.homeVisitLabel.AutoSize = True
            Me.homeVisitLabel.Location = New System.Drawing.Point(538, 159)
            Me.homeVisitLabel.Name = "homeVisitLabel"
            Me.homeVisitLabel.Size = New System.Drawing.Size(83, 13)
            Me.homeVisitLabel.TabIndex = 19
            Me.homeVisitLabel.Text = "Home Visit Date"
            '
            'homeVisit_dateTimePicker
            '
            Me.homeVisit_dateTimePicker.CustomFormat = "dd/MM/yyyy"
            Me.homeVisit_dateTimePicker.Format = System.Windows.Forms.DateTimePickerFormat.Custom
            Me.homeVisit_dateTimePicker.Location = New System.Drawing.Point(648, 50)
            Me.homeVisit_dateTimePicker.Name = "homeVisit_dateTimePicker"
            Me.homeVisit_dateTimePicker.Size = New System.Drawing.Size(200, 20)
            Me.homeVisit_dateTimePicker.TabIndex = 20
            Me.homeVisit_dateTimePicker.Value = New Date(2014, 5, 26, 17, 35, 11, 0)
            '
            'committeeDecisionLabel
            '
            Me.committeeDecisionLabel.AutoSize = True
            Me.committeeDecisionLabel.Location = New System.Drawing.Point(495, 50)
            Me.committeeDecisionLabel.Name = "committeeDecisionLabel"
            Me.committeeDecisionLabel.Size = New System.Drawing.Size(126, 13)
            Me.committeeDecisionLabel.TabIndex = 21
            Me.committeeDecisionLabel.Text = "Committee Decision Date"
            '
            'committeeDecision_dateTimePicker
            '
            Me.committeeDecision_dateTimePicker.CustomFormat = "dd/MM/yyyy"
            Me.committeeDecision_dateTimePicker.Format = System.Windows.Forms.DateTimePickerFormat.Custom
            Me.committeeDecision_dateTimePicker.Location = New System.Drawing.Point(648, 84)
            Me.committeeDecision_dateTimePicker.Name = "committeeDecision_dateTimePicker"
            Me.committeeDecision_dateTimePicker.Size = New System.Drawing.Size(200, 20)
            Me.committeeDecision_dateTimePicker.TabIndex = 22
            Me.committeeDecision_dateTimePicker.Value = New Date(2014, 5, 26, 17, 35, 11, 0)
            '
            'committeeAcceptedLabel
            '
            Me.committeeAcceptedLabel.AutoSize = True
            Me.committeeAcceptedLabel.Location = New System.Drawing.Point(517, 284)
            Me.committeeAcceptedLabel.Name = "committeeAcceptedLabel"
            Me.committeeAcceptedLabel.Size = New System.Drawing.Size(105, 13)
            Me.committeeAcceptedLabel.TabIndex = 23
            Me.committeeAcceptedLabel.Text = "Committee Accepted"
            '
            'committeeAcceptedTextBox
            '
            Me.committeeAcceptedTextBox.Location = New System.Drawing.Point(648, 284)
            Me.committeeAcceptedTextBox.Name = "committeeAcceptedTextBox"
            Me.committeeAcceptedTextBox.Size = New System.Drawing.Size(100, 20)
            Me.committeeAcceptedTextBox.TabIndex = 24
            '
            'committeeReasonLabel
            '
            Me.committeeReasonLabel.AutoSize = True
            Me.committeeReasonLabel.Location = New System.Drawing.Point(528, 318)
            Me.committeeReasonLabel.Name = "committeeReasonLabel"
            Me.committeeReasonLabel.Size = New System.Drawing.Size(96, 13)
            Me.committeeReasonLabel.TabIndex = 25
            Me.committeeReasonLabel.Text = "Committee Reason"
            '
            'committeeReasonTextBox
            '
            Me.committeeReasonTextBox.Location = New System.Drawing.Point(648, 318)
            Me.committeeReasonTextBox.Name = "committeeReasonTextBox"
            Me.committeeReasonTextBox.Size = New System.Drawing.Size(100, 20)
            Me.committeeReasonTextBox.TabIndex = 26
            '
            'boardVoteLabel
            '
            Me.boardVoteLabel.AutoSize = True
            Me.boardVoteLabel.Location = New System.Drawing.Point(537, 125)
            Me.boardVoteLabel.Name = "boardVoteLabel"
            Me.boardVoteLabel.Size = New System.Drawing.Size(86, 13)
            Me.boardVoteLabel.TabIndex = 27
            Me.boardVoteLabel.Text = "Board Vote Date"
            '
            'boardVote_dateTimePicker
            '
            Me.boardVote_dateTimePicker.CustomFormat = "dd/MM/yyyy"
            Me.boardVote_dateTimePicker.Format = System.Windows.Forms.DateTimePickerFormat.Custom
            Me.boardVote_dateTimePicker.Location = New System.Drawing.Point(648, 118)
            Me.boardVote_dateTimePicker.Name = "boardVote_dateTimePicker"
            Me.boardVote_dateTimePicker.Size = New System.Drawing.Size(200, 20)
            Me.boardVote_dateTimePicker.TabIndex = 28
            Me.boardVote_dateTimePicker.Value = New Date(2014, 5, 26, 17, 35, 11, 0)
            '
            'boardAcceptedLabel
            '
            Me.boardAcceptedLabel.AutoSize = True
            Me.boardAcceptedLabel.Location = New System.Drawing.Point(541, 220)
            Me.boardAcceptedLabel.Name = "boardAcceptedLabel"
            Me.boardAcceptedLabel.Size = New System.Drawing.Size(84, 13)
            Me.boardAcceptedLabel.TabIndex = 29
            Me.boardAcceptedLabel.Text = "Board Accepted"
            '
            'boardAcceptedTextBox
            '
            Me.boardAcceptedTextBox.Location = New System.Drawing.Point(648, 220)
            Me.boardAcceptedTextBox.Name = "boardAcceptedTextBox"
            Me.boardAcceptedTextBox.Size = New System.Drawing.Size(100, 20)
            Me.boardAcceptedTextBox.TabIndex = 30
            '
            'boardReasonLabel
            '
            Me.boardReasonLabel.AutoSize = True
            Me.boardReasonLabel.Location = New System.Drawing.Point(549, 257)
            Me.boardReasonLabel.Name = "boardReasonLabel"
            Me.boardReasonLabel.Size = New System.Drawing.Size(75, 13)
            Me.boardReasonLabel.TabIndex = 31
            Me.boardReasonLabel.Text = "Board Reason"
            '
            'boardReasonTextBox
            '
            Me.boardReasonTextBox.Location = New System.Drawing.Point(648, 254)
            Me.boardReasonTextBox.Name = "boardReasonTextBox"
            Me.boardReasonTextBox.Size = New System.Drawing.Size(100, 20)
            Me.boardReasonTextBox.TabIndex = 32
            '
            'handbookReviewLabel
            '
            Me.handbookReviewLabel.AutoSize = True
            Me.handbookReviewLabel.Location = New System.Drawing.Point(501, 90)
            Me.handbookReviewLabel.Name = "handbookReviewLabel"
            Me.handbookReviewLabel.Size = New System.Drawing.Size(122, 13)
            Me.handbookReviewLabel.TabIndex = 33
            Me.handbookReviewLabel.Text = "Handbook Review Date"
            '
            'handbookReview_dateTimePicker
            '
            Me.handbookReview_dateTimePicker.CustomFormat = "dd/MM/yyyy"
            Me.handbookReview_dateTimePicker.Format = System.Windows.Forms.DateTimePickerFormat.Custom
            Me.handbookReview_dateTimePicker.Location = New System.Drawing.Point(648, 159)
            Me.handbookReview_dateTimePicker.Name = "handbookReview_dateTimePicker"
            Me.handbookReview_dateTimePicker.Size = New System.Drawing.Size(200, 20)
            Me.handbookReview_dateTimePicker.TabIndex = 34
            Me.handbookReview_dateTimePicker.Value = New Date(2014, 5, 26, 17, 35, 11, 0)
            '
            'general_UIDLabel
            '
            Me.general_UIDLabel.AutoSize = True
            Me.general_UIDLabel.Location = New System.Drawing.Point(144, 154)
            Me.general_UIDLabel.Name = "general_UIDLabel"
            Me.general_UIDLabel.Size = New System.Drawing.Size(67, 13)
            Me.general_UIDLabel.TabIndex = 35
            Me.general_UIDLabel.Text = "general_UID"
            '
            'general_UID_comboBox
            '
            Me.general_UID_comboBox.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.Append
            Me.general_UID_comboBox.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.ListItems
            Me.general_UID_comboBox.FormattingEnabled = True
            Me.general_UID_comboBox.Location = New System.Drawing.Point(244, 151)
            Me.general_UID_comboBox.Name = "general_UID_comboBox"
            Me.general_UID_comboBox.Size = New System.Drawing.Size(200, 21)
            Me.general_UID_comboBox.TabIndex = 36
            '
            'panel3
            '
            Me.panel3.Controls.Add(Me.Panel1)
            Me.panel3.Controls.Add(Me.panel4)
            Me.panel3.Controls.Add(Me.panel5)
            Me.panel3.Controls.Add(Me.panel6)
            Me.panel3.Dock = System.Windows.Forms.DockStyle.Fill
            Me.panel3.Location = New System.Drawing.Point(0, 27)
            Me.panel3.Name = "panel3"
            Me.panel3.Size = New System.Drawing.Size(892, 369)
            Me.panel3.TabIndex = 19
            '
            'panel4
            '
            Me.panel4.Dock = System.Windows.Forms.DockStyle.Right
            Me.panel4.Location = New System.Drawing.Point(882, 0)
            Me.panel4.Name = "panel4"
            Me.panel4.Size = New System.Drawing.Size(10, 359)
            Me.panel4.TabIndex = 3
            '
            'panel5
            '
            Me.panel5.Dock = System.Windows.Forms.DockStyle.Left
            Me.panel5.Location = New System.Drawing.Point(0, 0)
            Me.panel5.Name = "panel5"
            Me.panel5.Size = New System.Drawing.Size(10, 359)
            Me.panel5.TabIndex = 5
            '
            'panel6
            '
            Me.panel6.Dock = System.Windows.Forms.DockStyle.Bottom
            Me.panel6.Location = New System.Drawing.Point(0, 359)
            Me.panel6.Name = "panel6"
            Me.panel6.Size = New System.Drawing.Size(892, 10)
            Me.panel6.TabIndex = 6
            '
            'MenuStrip2
            '
            Me.MenuStrip2.Items.AddRange(New System.Windows.Forms.ToolStripItem() {Me.ToolStripMenuItem1, Me.ToolStripMenuItem2, Me.ToolStripMenuItem3, Me.ToolStripMenuItem4, Me.TrackingToolStripMenuItem, Me.ToolStripMenuItem5, Me.SurveyToolStripMenuItem})
            Me.MenuStrip2.Location = New System.Drawing.Point(0, 0)
            Me.MenuStrip2.Name = "MenuStrip2"
            Me.MenuStrip2.Size = New System.Drawing.Size(872, 24)
            Me.MenuStrip2.TabIndex = 122
            Me.MenuStrip2.Text = "MenuStrip2"
            '
            'ToolStripMenuItem1
            '
            Me.ToolStripMenuItem1.Name = "ToolStripMenuItem1"
            Me.ToolStripMenuItem1.Size = New System.Drawing.Size(80, 20)
            Me.ToolStripMenuItem1.Text = "Main Menu"
            '
            'ToolStripMenuItem2
            '
            Me.ToolStripMenuItem2.Name = "ToolStripMenuItem2"
            Me.ToolStripMenuItem2.Size = New System.Drawing.Size(59, 20)
            Me.ToolStripMenuItem2.Text = "General"
            '
            'ToolStripMenuItem3
            '
            Me.ToolStripMenuItem3.Enabled = False
            Me.ToolStripMenuItem3.Name = "ToolStripMenuItem3"
            Me.ToolStripMenuItem3.Size = New System.Drawing.Size(107, 20)
            Me.ToolStripMenuItem3.Text = "Homeownership"
            '
            'ToolStripMenuItem4
            '
            Me.ToolStripMenuItem4.Name = "ToolStripMenuItem4"
            Me.ToolStripMenuItem4.Size = New System.Drawing.Size(57, 20)
            Me.ToolStripMenuItem4.Text = "Repairs"
            '
            'TrackingToolStripMenuItem
            '
            Me.TrackingToolStripMenuItem.Name = "TrackingToolStripMenuItem"
            Me.TrackingToolStripMenuItem.Size = New System.Drawing.Size(63, 20)
            Me.TrackingToolStripMenuItem.Text = "Tracking"
            '
            'ToolStripMenuItem5
            '
            Me.ToolStripMenuItem5.Name = "ToolStripMenuItem5"
            Me.ToolStripMenuItem5.Size = New System.Drawing.Size(88, 20)
            Me.ToolStripMenuItem5.Text = "Survey Editor"
            '
            'SurveyToolStripMenuItem
            '
            Me.SurveyToolStripMenuItem.Name = "SurveyToolStripMenuItem"
            Me.SurveyToolStripMenuItem.Size = New System.Drawing.Size(94, 20)
            Me.SurveyToolStripMenuItem.Text = "Survey Results"
            '
            'frmhomeownership
            '
            Me.AutoScaleDimensions = New System.Drawing.SizeF(6.0!, 13.0!)
            Me.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font
            Me.ClientSize = New System.Drawing.Size(892, 396)
            Me.Controls.Add(Me.panel3)
            Me.Controls.Add(Me.BindingNavigator1)
            Me.Name = "frmhomeownership"
            Me.Text = "Homeownership"
            CType(Me.BindingNavigator1, System.ComponentModel.ISupportInitialize).EndInit()
            Me.BindingNavigator1.ResumeLayout(False)
            Me.BindingNavigator1.PerformLayout()
            CType(Me.homeownershipBindingSource, System.ComponentModel.ISupportInitialize).EndInit()
            CType(Me.ErrorProvider1, System.ComponentModel.ISupportInitialize).EndInit()
            Me.Panel1.ResumeLayout(False)
            Me.Panel1.PerformLayout()
            Me.panel3.ResumeLayout(False)
            Me.panel3.PerformLayout()
            Me.MenuStrip2.ResumeLayout(False)
            Me.MenuStrip2.PerformLayout()
            Me.ResumeLayout(False)
            Me.PerformLayout()

        End Sub
        Friend WithEvents BindingNavigator1 As System.Windows.Forms.BindingNavigator
		Friend WithEvents BindingNavigatorAddNewItem As System.Windows.Forms.ToolStripButton
		Friend WithEvents BindingNavigatorCountItem As System.Windows.Forms.ToolStripLabel
		Friend WithEvents BindingNavigatorDeleteItem As System.Windows.Forms.ToolStripButton
		Friend WithEvents BindingNavigatorMoveFirstItem As System.Windows.Forms.ToolStripButton
		Friend WithEvents BindingNavigatorMovePreviousItem As System.Windows.Forms.ToolStripButton
		Friend WithEvents BindingNavigatorSeparator As System.Windows.Forms.ToolStripSeparator
		Friend WithEvents BindingNavigatorPositionItem As System.Windows.Forms.ToolStripTextBox
		Friend WithEvents BindingNavigatorSeparator1 As System.Windows.Forms.ToolStripSeparator
		Friend WithEvents BindingNavigatorMoveNextItem As System.Windows.Forms.ToolStripButton
		Friend WithEvents BindingNavigatorMoveLastItem As System.Windows.Forms.ToolStripButton
		Friend WithEvents BindingNavigatorSeparator2 As System.Windows.Forms.ToolStripSeparator
		Friend WithEvents ToolStripButton1 As System.Windows.Forms.ToolStripButton
		Friend WithEvents ErrorProvider1 As System.Windows.Forms.ErrorProvider
		Friend WithEvents Panel1 As System.Windows.Forms.Panel
		Friend WithEvents homeownershipBindingSource As System.Windows.Forms.BindingSource
		Friend WithEvents applicantInfoMeeting_dateTimePicker As System.Windows.Forms.DateTimePicker
		Friend WithEvents applicantInfoMeetingLabel As System.Windows.Forms.Label
		Friend WithEvents applicationChecklist1_dateTimePicker As System.Windows.Forms.DateTimePicker
		Friend WithEvents applicationChecklist1Label As System.Windows.Forms.Label
		Friend WithEvents applicationChecklist2_dateTimePicker As System.Windows.Forms.DateTimePicker
		Friend WithEvents applicationChecklist2Label As System.Windows.Forms.Label
		Friend WithEvents employmentVerifiedTextBox As System.Windows.Forms.TextBox
		Friend WithEvents employmentVerifiedLabel As System.Windows.Forms.Label
		Friend WithEvents landlordReferenceTextBox As System.Windows.Forms.TextBox
		Friend WithEvents landlordReferenceLabel As System.Windows.Forms.Label
		Friend WithEvents previousLandlordReferenceTextBox As System.Windows.Forms.TextBox
		Friend WithEvents previousLandlordReferenceLabel As System.Windows.Forms.Label
		Friend WithEvents backgroundCheckTextBox As System.Windows.Forms.TextBox
		Friend WithEvents backgroundCheckLabel As System.Windows.Forms.Label
		Friend WithEvents CCCBudgetTextBox As System.Windows.Forms.TextBox
		Friend WithEvents CCCBudgetLabel As System.Windows.Forms.Label
		Friend WithEvents creditReportRunTextBox As System.Windows.Forms.TextBox
		Friend WithEvents creditReportRunLabel As System.Windows.Forms.Label
		Friend WithEvents homeVisit_dateTimePicker As System.Windows.Forms.DateTimePicker
		Friend WithEvents homeVisitLabel As System.Windows.Forms.Label
		Friend WithEvents committeeDecision_dateTimePicker As System.Windows.Forms.DateTimePicker
		Friend WithEvents committeeDecisionLabel As System.Windows.Forms.Label
		Friend WithEvents committeeAcceptedTextBox As System.Windows.Forms.TextBox
		Friend WithEvents committeeAcceptedLabel As System.Windows.Forms.Label
		Friend WithEvents committeeReasonTextBox As System.Windows.Forms.TextBox
		Friend WithEvents committeeReasonLabel As System.Windows.Forms.Label
		Friend WithEvents boardVote_dateTimePicker As System.Windows.Forms.DateTimePicker
		Friend WithEvents boardVoteLabel As System.Windows.Forms.Label
		Friend WithEvents boardAcceptedTextBox As System.Windows.Forms.TextBox
		Friend WithEvents boardAcceptedLabel As System.Windows.Forms.Label
		Friend WithEvents boardReasonTextBox As System.Windows.Forms.TextBox
		Friend WithEvents boardReasonLabel As System.Windows.Forms.Label
		Friend WithEvents handbookReview_dateTimePicker As System.Windows.Forms.DateTimePicker
		Friend WithEvents handbookReviewLabel As System.Windows.Forms.Label
		Friend WithEvents general_UID_comboBox As System.Windows.Forms.ComboBox
		Friend WithEvents general_UIDLabel As System.Windows.Forms.Label
		Friend WithEvents panel3 As System.Windows.Forms.Panel
		Friend WithEvents panel4 As System.Windows.Forms.Panel
		Friend WithEvents panel5 As System.Windows.Forms.Panel
		Friend WithEvents panel6 As System.Windows.Forms.Panel
        Friend WithEvents MenuStrip2 As MenuStrip
        Friend WithEvents ToolStripMenuItem1 As ToolStripMenuItem
        Friend WithEvents ToolStripMenuItem2 As ToolStripMenuItem
        Friend WithEvents ToolStripMenuItem3 As ToolStripMenuItem
        Friend WithEvents ToolStripMenuItem4 As ToolStripMenuItem
        Friend WithEvents TrackingToolStripMenuItem As ToolStripMenuItem
        Friend WithEvents ToolStripMenuItem5 As ToolStripMenuItem
        Friend WithEvents SurveyToolStripMenuItem As ToolStripMenuItem
    End Class

End Namespace
