' ++++++++++++++++++++++++++++++++++++++++++++++++++
' This code is generated by a tool and is provided "as is", without warranty of any kind,
' express or implied, including but not limited to the warranties of merchantability,
' fitness for a particular purpose and non-infringement.
' In no event shall the authors or copyright holders be liable for any claim, damages or
' other liability, whether in an action of contract, tort or otherwise, arising from,
' out of or in connection with the software or the use or other dealings in the software.
' ++++++++++++++++++++++++++++++++++++++++++++++++++
' 

Namespace DatabaseTestApplication2
	
	<Global.Microsoft.VisualBasic.CompilerServices.DesignerGenerated()> _
	Partial Class frmrepairs
		Inherits System.Windows.Forms.Form
		
		'Form overrides dispose to clean up the component list.
		<System.Diagnostics.DebuggerNonUserCode()> _
		Protected Overrides Sub Dispose(ByVal disposing As Boolean)
			Try
			If disposing AndAlso components IsNot Nothing Then
				components.Dispose()
			End If
			Finally
			MyBase.Dispose(disposing)
			End Try
		End Sub
		
		'Required by the Windows Form Designer
		Private components As System.ComponentModel.IContainer
		
		'NOTE: The following procedure is required by the Windows Form Designer
		'It can be modified using the Windows Form Designer.  
		'Do not modify it using the code editor.
		<System.Diagnostics.DebuggerStepThrough()> _
		Private Sub InitializeComponent()
            Me.components = New System.ComponentModel.Container()
            Dim resources As System.ComponentModel.ComponentResourceManager = New System.ComponentModel.ComponentResourceManager(GetType(frmrepairs))
            Me.BindingNavigator1 = New System.Windows.Forms.BindingNavigator(Me.components)
            Me.repairsBindingSource = New System.Windows.Forms.BindingSource(Me.components)
            Me.BindingNavigatorCountItem = New System.Windows.Forms.ToolStripLabel()
            Me.BindingNavigatorDeleteItem = New System.Windows.Forms.ToolStripButton()
            Me.BindingNavigatorMoveFirstItem = New System.Windows.Forms.ToolStripButton()
            Me.BindingNavigatorMovePreviousItem = New System.Windows.Forms.ToolStripButton()
            Me.BindingNavigatorSeparator = New System.Windows.Forms.ToolStripSeparator()
            Me.BindingNavigatorPositionItem = New System.Windows.Forms.ToolStripTextBox()
            Me.BindingNavigatorSeparator1 = New System.Windows.Forms.ToolStripSeparator()
            Me.BindingNavigatorMoveNextItem = New System.Windows.Forms.ToolStripButton()
            Me.BindingNavigatorMoveLastItem = New System.Windows.Forms.ToolStripButton()
            Me.BindingNavigatorSeparator2 = New System.Windows.Forms.ToolStripSeparator()
            Me.BindingNavigatorAddNewItem = New System.Windows.Forms.ToolStripButton()
            Me.ToolStripButton1 = New System.Windows.Forms.ToolStripButton()
            Me.ErrorProvider1 = New System.Windows.Forms.ErrorProvider(Me.components)
            Me.Panel1 = New System.Windows.Forms.Panel()
            Me.chkIDDocs = New System.Windows.Forms.CheckBox()
            Me.chkFundSource = New System.Windows.Forms.CheckBox()
            Me.chkGISAssessment = New System.Windows.Forms.CheckBox()
            Me.chkParcelReport = New System.Windows.Forms.CheckBox()
            Me.chkCompletedApp = New System.Windows.Forms.CheckBox()
            Me.chkSatisfaction = New System.Windows.Forms.CheckBox()
            Me.chkTaxBill = New System.Windows.Forms.CheckBox()
            Me.chkDeed = New System.Windows.Forms.CheckBox()
            Me.chkIncomeVerified = New System.Windows.Forms.CheckBox()
            Me.PictureBox1 = New System.Windows.Forms.PictureBox()
            Me.Label1 = New System.Windows.Forms.Label()
            Me.ApplicationSubmissionLabel = New System.Windows.Forms.Label()
            Me.ApplicationSubmission_dateTimePicker = New System.Windows.Forms.DateTimePicker()
            Me.AdditionalDocumentsLabel = New System.Windows.Forms.Label()
            Me.AdditionalDocuments_dateTimePicker = New System.Windows.Forms.DateTimePicker()
            Me.ApprovalSiteVisitLabel = New System.Windows.Forms.Label()
            Me.ApprovalSiteVisit_dateTimePicker = New System.Windows.Forms.DateTimePicker()
            Me.SiteVisitCompleteLabel = New System.Windows.Forms.Label()
            Me.SiteVisitComplete_dateTimePicker = New System.Windows.Forms.DateTimePicker()
            Me.ScopeOfWorkLabel = New System.Windows.Forms.Label()
            Me.ScopeOfWork_dateTimePicker = New System.Windows.Forms.DateTimePicker()
            Me.ContractCompleteLabel = New System.Windows.Forms.Label()
            Me.ContractComplete_dateTimePicker = New System.Windows.Forms.DateTimePicker()
            Me.WorkCompleteLabel = New System.Windows.Forms.Label()
            Me.WorkComplete_dateTimePicker = New System.Windows.Forms.DateTimePicker()
            Me.IDDocumentsLabel = New System.Windows.Forms.Label()
            Me.IDDocumentsTextBox = New System.Windows.Forms.TextBox()
            Me.IncomeVerifiedLabel = New System.Windows.Forms.Label()
            Me.IncomeVerifiedTextBox = New System.Windows.Forms.TextBox()
            Me.DeedOfTrustLabel = New System.Windows.Forms.Label()
            Me.DeedOfTrustTextBox = New System.Windows.Forms.TextBox()
            Me.TaxBillLabel = New System.Windows.Forms.Label()
            Me.TaxBillTextBox = New System.Windows.Forms.TextBox()
            Me.SatisfactionLabel = New System.Windows.Forms.Label()
            Me.SatisfactionTextBox = New System.Windows.Forms.TextBox()
            Me.CompletedApplicationLabel = New System.Windows.Forms.Label()
            Me.CompletedApplicationTextBox = New System.Windows.Forms.TextBox()
            Me.ParcelReportLabel = New System.Windows.Forms.Label()
            Me.ParcelReportTextBox = New System.Windows.Forms.TextBox()
            Me.GISAssessmentLabel = New System.Windows.Forms.Label()
            Me.GISAssessmentTextBox = New System.Windows.Forms.TextBox()
            Me.FundingSourceLabel = New System.Windows.Forms.Label()
            Me.FundingSourceTextBox = New System.Windows.Forms.TextBox()
            Me.General_Info_UIDLabel = New System.Windows.Forms.Label()
            Me.General_Info_UID_comboBox = New System.Windows.Forms.ComboBox()
            Me.mStripMENUBAR = New System.Windows.Forms.MenuStrip()
            Me.tstripMainMenu = New System.Windows.Forms.ToolStripMenuItem()
            Me.tstripGeneral = New System.Windows.Forms.ToolStripMenuItem()
            Me.tstripHomeownership = New System.Windows.Forms.ToolStripMenuItem()
            Me.RepairsToolStripMenuItem = New System.Windows.Forms.ToolStripMenuItem()
            Me.panel3 = New System.Windows.Forms.Panel()
            Me.panel4 = New System.Windows.Forms.Panel()
            Me.panel5 = New System.Windows.Forms.Panel()
            Me.panel6 = New System.Windows.Forms.Panel()
            CType(Me.BindingNavigator1, System.ComponentModel.ISupportInitialize).BeginInit()
            Me.BindingNavigator1.SuspendLayout()
            CType(Me.repairsBindingSource, System.ComponentModel.ISupportInitialize).BeginInit()
            CType(Me.ErrorProvider1, System.ComponentModel.ISupportInitialize).BeginInit()
            Me.Panel1.SuspendLayout()
            CType(Me.PictureBox1, System.ComponentModel.ISupportInitialize).BeginInit()
            Me.mStripMENUBAR.SuspendLayout()
            Me.panel3.SuspendLayout()
            Me.SuspendLayout()
            '
            'BindingNavigator1
            '
            Me.BindingNavigator1.AddNewItem = Nothing
            Me.BindingNavigator1.BindingSource = Me.repairsBindingSource
            Me.BindingNavigator1.CountItem = Me.BindingNavigatorCountItem
            Me.BindingNavigator1.DeleteItem = Me.BindingNavigatorDeleteItem
            Me.BindingNavigator1.ImageScalingSize = New System.Drawing.Size(20, 20)
            Me.BindingNavigator1.Items.AddRange(New System.Windows.Forms.ToolStripItem() {Me.BindingNavigatorMoveFirstItem, Me.BindingNavigatorMovePreviousItem, Me.BindingNavigatorSeparator, Me.BindingNavigatorPositionItem, Me.BindingNavigatorCountItem, Me.BindingNavigatorSeparator1, Me.BindingNavigatorMoveNextItem, Me.BindingNavigatorMoveLastItem, Me.BindingNavigatorSeparator2, Me.BindingNavigatorAddNewItem, Me.BindingNavigatorDeleteItem, Me.ToolStripButton1})
            Me.BindingNavigator1.Location = New System.Drawing.Point(0, 0)
            Me.BindingNavigator1.MoveFirstItem = Me.BindingNavigatorMoveFirstItem
            Me.BindingNavigator1.MoveLastItem = Me.BindingNavigatorMoveLastItem
            Me.BindingNavigator1.MoveNextItem = Me.BindingNavigatorMoveNextItem
            Me.BindingNavigator1.MovePreviousItem = Me.BindingNavigatorMovePreviousItem
            Me.BindingNavigator1.Name = "BindingNavigator1"
            Me.BindingNavigator1.Padding = New System.Windows.Forms.Padding(13, 0, 13, 0)
            Me.BindingNavigator1.PositionItem = Me.BindingNavigatorPositionItem
            Me.BindingNavigator1.Size = New System.Drawing.Size(1140, 27)
            Me.BindingNavigator1.TabIndex = 0
            Me.BindingNavigator1.Text = "BindingNavigator1"
            '
            'BindingNavigatorCountItem
            '
            Me.BindingNavigatorCountItem.Name = "BindingNavigatorCountItem"
            Me.BindingNavigatorCountItem.Size = New System.Drawing.Size(45, 24)
            Me.BindingNavigatorCountItem.Text = "of {0}"
            Me.BindingNavigatorCountItem.ToolTipText = "Total number of items"
            '
            'BindingNavigatorDeleteItem
            '
            Me.BindingNavigatorDeleteItem.DisplayStyle = System.Windows.Forms.ToolStripItemDisplayStyle.Image
            Me.BindingNavigatorDeleteItem.Image = CType(resources.GetObject("BindingNavigatorDeleteItem.Image"), System.Drawing.Image)
            Me.BindingNavigatorDeleteItem.Name = "BindingNavigatorDeleteItem"
            Me.BindingNavigatorDeleteItem.RightToLeftAutoMirrorImage = True
            Me.BindingNavigatorDeleteItem.Size = New System.Drawing.Size(29, 24)
            Me.BindingNavigatorDeleteItem.Text = "Delete"
            '
            'BindingNavigatorMoveFirstItem
            '
            Me.BindingNavigatorMoveFirstItem.DisplayStyle = System.Windows.Forms.ToolStripItemDisplayStyle.Image
            Me.BindingNavigatorMoveFirstItem.Image = CType(resources.GetObject("BindingNavigatorMoveFirstItem.Image"), System.Drawing.Image)
            Me.BindingNavigatorMoveFirstItem.Name = "BindingNavigatorMoveFirstItem"
            Me.BindingNavigatorMoveFirstItem.RightToLeftAutoMirrorImage = True
            Me.BindingNavigatorMoveFirstItem.Size = New System.Drawing.Size(29, 24)
            Me.BindingNavigatorMoveFirstItem.Text = "Move first"
            '
            'BindingNavigatorMovePreviousItem
            '
            Me.BindingNavigatorMovePreviousItem.DisplayStyle = System.Windows.Forms.ToolStripItemDisplayStyle.Image
            Me.BindingNavigatorMovePreviousItem.Image = CType(resources.GetObject("BindingNavigatorMovePreviousItem.Image"), System.Drawing.Image)
            Me.BindingNavigatorMovePreviousItem.Name = "BindingNavigatorMovePreviousItem"
            Me.BindingNavigatorMovePreviousItem.RightToLeftAutoMirrorImage = True
            Me.BindingNavigatorMovePreviousItem.Size = New System.Drawing.Size(29, 24)
            Me.BindingNavigatorMovePreviousItem.Text = "Move previous"
            '
            'BindingNavigatorSeparator
            '
            Me.BindingNavigatorSeparator.Name = "BindingNavigatorSeparator"
            Me.BindingNavigatorSeparator.Size = New System.Drawing.Size(6, 27)
            '
            'BindingNavigatorPositionItem
            '
            Me.BindingNavigatorPositionItem.AccessibleName = "Position"
            Me.BindingNavigatorPositionItem.AutoSize = False
            Me.BindingNavigatorPositionItem.Font = New System.Drawing.Font("Segoe UI", 9.0!)
            Me.BindingNavigatorPositionItem.Name = "BindingNavigatorPositionItem"
            Me.BindingNavigatorPositionItem.Size = New System.Drawing.Size(65, 27)
            Me.BindingNavigatorPositionItem.Text = "0"
            Me.BindingNavigatorPositionItem.ToolTipText = "Current position"
            '
            'BindingNavigatorSeparator1
            '
            Me.BindingNavigatorSeparator1.Name = "BindingNavigatorSeparator1"
            Me.BindingNavigatorSeparator1.Size = New System.Drawing.Size(6, 27)
            '
            'BindingNavigatorMoveNextItem
            '
            Me.BindingNavigatorMoveNextItem.DisplayStyle = System.Windows.Forms.ToolStripItemDisplayStyle.Image
            Me.BindingNavigatorMoveNextItem.Image = CType(resources.GetObject("BindingNavigatorMoveNextItem.Image"), System.Drawing.Image)
            Me.BindingNavigatorMoveNextItem.Name = "BindingNavigatorMoveNextItem"
            Me.BindingNavigatorMoveNextItem.RightToLeftAutoMirrorImage = True
            Me.BindingNavigatorMoveNextItem.Size = New System.Drawing.Size(29, 24)
            Me.BindingNavigatorMoveNextItem.Text = "Move next"
            '
            'BindingNavigatorMoveLastItem
            '
            Me.BindingNavigatorMoveLastItem.DisplayStyle = System.Windows.Forms.ToolStripItemDisplayStyle.Image
            Me.BindingNavigatorMoveLastItem.Image = CType(resources.GetObject("BindingNavigatorMoveLastItem.Image"), System.Drawing.Image)
            Me.BindingNavigatorMoveLastItem.Name = "BindingNavigatorMoveLastItem"
            Me.BindingNavigatorMoveLastItem.RightToLeftAutoMirrorImage = True
            Me.BindingNavigatorMoveLastItem.Size = New System.Drawing.Size(29, 24)
            Me.BindingNavigatorMoveLastItem.Text = "Move last"
            '
            'BindingNavigatorSeparator2
            '
            Me.BindingNavigatorSeparator2.Name = "BindingNavigatorSeparator2"
            Me.BindingNavigatorSeparator2.Size = New System.Drawing.Size(6, 27)
            '
            'BindingNavigatorAddNewItem
            '
            Me.BindingNavigatorAddNewItem.DisplayStyle = System.Windows.Forms.ToolStripItemDisplayStyle.Image
            Me.BindingNavigatorAddNewItem.Image = CType(resources.GetObject("BindingNavigatorAddNewItem.Image"), System.Drawing.Image)
            Me.BindingNavigatorAddNewItem.Name = "BindingNavigatorAddNewItem"
            Me.BindingNavigatorAddNewItem.RightToLeftAutoMirrorImage = True
            Me.BindingNavigatorAddNewItem.Size = New System.Drawing.Size(29, 24)
            Me.BindingNavigatorAddNewItem.Text = "Add new"
            '
            'ToolStripButton1
            '
            Me.ToolStripButton1.DisplayStyle = System.Windows.Forms.ToolStripItemDisplayStyle.Image
            Me.ToolStripButton1.Image = CType(resources.GetObject("ToolStripButton1.Image"), System.Drawing.Image)
            Me.ToolStripButton1.ImageTransparentColor = System.Drawing.Color.Magenta
            Me.ToolStripButton1.Name = "ToolStripButton1"
            Me.ToolStripButton1.Size = New System.Drawing.Size(29, 24)
            Me.ToolStripButton1.Text = "Save"
            '
            'ErrorProvider1
            '
            Me.ErrorProvider1.ContainerControl = Me
            '
            'Panel1
            '
            Me.Panel1.AutoScroll = True
            Me.Panel1.AutoSize = True
            Me.Panel1.BackColor = System.Drawing.Color.Transparent
            Me.Panel1.BackgroundImage = Global.DatabaseTestApplication2.My.Resources.Resources.angryimg__12_
            Me.Panel1.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch
            Me.Panel1.Controls.Add(Me.chkIDDocs)
            Me.Panel1.Controls.Add(Me.chkFundSource)
            Me.Panel1.Controls.Add(Me.chkGISAssessment)
            Me.Panel1.Controls.Add(Me.chkParcelReport)
            Me.Panel1.Controls.Add(Me.chkCompletedApp)
            Me.Panel1.Controls.Add(Me.chkSatisfaction)
            Me.Panel1.Controls.Add(Me.chkTaxBill)
            Me.Panel1.Controls.Add(Me.chkDeed)
            Me.Panel1.Controls.Add(Me.chkIncomeVerified)
            Me.Panel1.Controls.Add(Me.PictureBox1)
            Me.Panel1.Controls.Add(Me.Label1)
            Me.Panel1.Controls.Add(Me.ApplicationSubmissionLabel)
            Me.Panel1.Controls.Add(Me.ApplicationSubmission_dateTimePicker)
            Me.Panel1.Controls.Add(Me.AdditionalDocumentsLabel)
            Me.Panel1.Controls.Add(Me.AdditionalDocuments_dateTimePicker)
            Me.Panel1.Controls.Add(Me.ApprovalSiteVisitLabel)
            Me.Panel1.Controls.Add(Me.ApprovalSiteVisit_dateTimePicker)
            Me.Panel1.Controls.Add(Me.SiteVisitCompleteLabel)
            Me.Panel1.Controls.Add(Me.SiteVisitComplete_dateTimePicker)
            Me.Panel1.Controls.Add(Me.ScopeOfWorkLabel)
            Me.Panel1.Controls.Add(Me.ScopeOfWork_dateTimePicker)
            Me.Panel1.Controls.Add(Me.ContractCompleteLabel)
            Me.Panel1.Controls.Add(Me.ContractComplete_dateTimePicker)
            Me.Panel1.Controls.Add(Me.WorkCompleteLabel)
            Me.Panel1.Controls.Add(Me.WorkComplete_dateTimePicker)
            Me.Panel1.Controls.Add(Me.IDDocumentsLabel)
            Me.Panel1.Controls.Add(Me.IDDocumentsTextBox)
            Me.Panel1.Controls.Add(Me.IncomeVerifiedLabel)
            Me.Panel1.Controls.Add(Me.IncomeVerifiedTextBox)
            Me.Panel1.Controls.Add(Me.DeedOfTrustLabel)
            Me.Panel1.Controls.Add(Me.DeedOfTrustTextBox)
            Me.Panel1.Controls.Add(Me.TaxBillLabel)
            Me.Panel1.Controls.Add(Me.TaxBillTextBox)
            Me.Panel1.Controls.Add(Me.SatisfactionLabel)
            Me.Panel1.Controls.Add(Me.SatisfactionTextBox)
            Me.Panel1.Controls.Add(Me.CompletedApplicationLabel)
            Me.Panel1.Controls.Add(Me.CompletedApplicationTextBox)
            Me.Panel1.Controls.Add(Me.ParcelReportLabel)
            Me.Panel1.Controls.Add(Me.ParcelReportTextBox)
            Me.Panel1.Controls.Add(Me.GISAssessmentLabel)
            Me.Panel1.Controls.Add(Me.GISAssessmentTextBox)
            Me.Panel1.Controls.Add(Me.FundingSourceLabel)
            Me.Panel1.Controls.Add(Me.FundingSourceTextBox)
            Me.Panel1.Controls.Add(Me.General_Info_UIDLabel)
            Me.Panel1.Controls.Add(Me.General_Info_UID_comboBox)
            Me.Panel1.Controls.Add(Me.mStripMENUBAR)
            Me.Panel1.Dock = System.Windows.Forms.DockStyle.Fill
            Me.Panel1.ForeColor = System.Drawing.Color.White
            Me.Panel1.Location = New System.Drawing.Point(13, 0)
            Me.Panel1.Margin = New System.Windows.Forms.Padding(13, 4, 13, 4)
            Me.Panel1.Name = "Panel1"
            Me.Panel1.Size = New System.Drawing.Size(1114, 626)
            Me.Panel1.TabIndex = 1
            '
            'chkIDDocs
            '
            Me.chkIDDocs.AutoSize = True
            Me.chkIDDocs.Font = New System.Drawing.Font("Microsoft YaHei", 9.0!)
            Me.chkIDDocs.Location = New System.Drawing.Point(865, 444)
            Me.chkIDDocs.Margin = New System.Windows.Forms.Padding(4, 4, 4, 4)
            Me.chkIDDocs.Name = "chkIDDocs"
            Me.chkIDDocs.Size = New System.Drawing.Size(35, 24)
            Me.chkIDDocs.TabIndex = 107
            Me.chkIDDocs.Text = " "
            Me.chkIDDocs.UseVisualStyleBackColor = True
            '
            'chkFundSource
            '
            Me.chkFundSource.AutoSize = True
            Me.chkFundSource.Font = New System.Drawing.Font("Microsoft YaHei", 9.0!)
            Me.chkFundSource.Location = New System.Drawing.Point(585, 585)
            Me.chkFundSource.Margin = New System.Windows.Forms.Padding(4, 4, 4, 4)
            Me.chkFundSource.Name = "chkFundSource"
            Me.chkFundSource.Size = New System.Drawing.Size(35, 24)
            Me.chkFundSource.TabIndex = 106
            Me.chkFundSource.Text = " "
            Me.chkFundSource.UseVisualStyleBackColor = True
            '
            'chkGISAssessment
            '
            Me.chkGISAssessment.AutoSize = True
            Me.chkGISAssessment.Font = New System.Drawing.Font("Microsoft YaHei", 9.0!)
            Me.chkGISAssessment.Location = New System.Drawing.Point(585, 538)
            Me.chkGISAssessment.Margin = New System.Windows.Forms.Padding(4, 4, 4, 4)
            Me.chkGISAssessment.Name = "chkGISAssessment"
            Me.chkGISAssessment.Size = New System.Drawing.Size(35, 24)
            Me.chkGISAssessment.TabIndex = 105
            Me.chkGISAssessment.Text = " "
            Me.chkGISAssessment.UseVisualStyleBackColor = True
            '
            'chkParcelReport
            '
            Me.chkParcelReport.AutoSize = True
            Me.chkParcelReport.Font = New System.Drawing.Font("Microsoft YaHei", 9.0!)
            Me.chkParcelReport.Location = New System.Drawing.Point(585, 491)
            Me.chkParcelReport.Margin = New System.Windows.Forms.Padding(4, 4, 4, 4)
            Me.chkParcelReport.Name = "chkParcelReport"
            Me.chkParcelReport.Size = New System.Drawing.Size(35, 24)
            Me.chkParcelReport.TabIndex = 104
            Me.chkParcelReport.Text = " "
            Me.chkParcelReport.UseVisualStyleBackColor = True
            '
            'chkCompletedApp
            '
            Me.chkCompletedApp.AutoSize = True
            Me.chkCompletedApp.Font = New System.Drawing.Font("Microsoft YaHei", 9.0!)
            Me.chkCompletedApp.Location = New System.Drawing.Point(585, 441)
            Me.chkCompletedApp.Margin = New System.Windows.Forms.Padding(4, 4, 4, 4)
            Me.chkCompletedApp.Name = "chkCompletedApp"
            Me.chkCompletedApp.Size = New System.Drawing.Size(35, 24)
            Me.chkCompletedApp.TabIndex = 103
            Me.chkCompletedApp.Text = " "
            Me.chkCompletedApp.UseVisualStyleBackColor = True
            '
            'chkSatisfaction
            '
            Me.chkSatisfaction.AutoSize = True
            Me.chkSatisfaction.Font = New System.Drawing.Font("Microsoft YaHei", 9.0!)
            Me.chkSatisfaction.Location = New System.Drawing.Point(223, 582)
            Me.chkSatisfaction.Margin = New System.Windows.Forms.Padding(4, 4, 4, 4)
            Me.chkSatisfaction.Name = "chkSatisfaction"
            Me.chkSatisfaction.Size = New System.Drawing.Size(35, 24)
            Me.chkSatisfaction.TabIndex = 102
            Me.chkSatisfaction.Text = " "
            Me.chkSatisfaction.UseVisualStyleBackColor = True
            '
            'chkTaxBill
            '
            Me.chkTaxBill.AutoSize = True
            Me.chkTaxBill.Font = New System.Drawing.Font("Microsoft YaHei", 9.0!)
            Me.chkTaxBill.Location = New System.Drawing.Point(223, 538)
            Me.chkTaxBill.Margin = New System.Windows.Forms.Padding(4, 4, 4, 4)
            Me.chkTaxBill.Name = "chkTaxBill"
            Me.chkTaxBill.Size = New System.Drawing.Size(35, 24)
            Me.chkTaxBill.TabIndex = 101
            Me.chkTaxBill.Text = " "
            Me.chkTaxBill.UseVisualStyleBackColor = True
            '
            'chkDeed
            '
            Me.chkDeed.AutoSize = True
            Me.chkDeed.Font = New System.Drawing.Font("Microsoft YaHei", 9.0!)
            Me.chkDeed.Location = New System.Drawing.Point(223, 442)
            Me.chkDeed.Margin = New System.Windows.Forms.Padding(4, 4, 4, 4)
            Me.chkDeed.Name = "chkDeed"
            Me.chkDeed.Size = New System.Drawing.Size(35, 24)
            Me.chkDeed.TabIndex = 100
            Me.chkDeed.Text = " "
            Me.chkDeed.UseVisualStyleBackColor = True
            '
            'chkIncomeVerified
            '
            Me.chkIncomeVerified.AutoSize = True
            Me.chkIncomeVerified.Font = New System.Drawing.Font("Microsoft YaHei", 9.0!)
            Me.chkIncomeVerified.Location = New System.Drawing.Point(223, 491)
            Me.chkIncomeVerified.Margin = New System.Windows.Forms.Padding(4, 4, 4, 4)
            Me.chkIncomeVerified.Name = "chkIncomeVerified"
            Me.chkIncomeVerified.Size = New System.Drawing.Size(35, 24)
            Me.chkIncomeVerified.TabIndex = 99
            Me.chkIncomeVerified.Text = " "
            Me.chkIncomeVerified.UseVisualStyleBackColor = True
            '
            'PictureBox1
            '
            Me.PictureBox1.BackColor = System.Drawing.Color.Transparent
            Me.PictureBox1.BackgroundImage = Global.DatabaseTestApplication2.My.Resources.Resources.CV_HB_Logo_White_400px
            Me.PictureBox1.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Zoom
            Me.PictureBox1.Location = New System.Drawing.Point(921, 30)
            Me.PictureBox1.Margin = New System.Windows.Forms.Padding(3, 2, 3, 2)
            Me.PictureBox1.Name = "PictureBox1"
            Me.PictureBox1.Size = New System.Drawing.Size(191, 66)
            Me.PictureBox1.TabIndex = 98
            Me.PictureBox1.TabStop = False
            '
            'Label1
            '
            Me.Label1.BackColor = System.Drawing.Color.Transparent
            Me.Label1.Font = New System.Drawing.Font("Microsoft YaHei UI", 36.0!, CType((System.Drawing.FontStyle.Bold Or System.Drawing.FontStyle.Italic), System.Drawing.FontStyle), System.Drawing.GraphicsUnit.Point, CType(0, Byte))
            Me.Label1.ForeColor = System.Drawing.Color.White
            Me.Label1.Location = New System.Drawing.Point(9, 30)
            Me.Label1.Margin = New System.Windows.Forms.Padding(9, 0, 9, 0)
            Me.Label1.Name = "Label1"
            Me.Label1.Size = New System.Drawing.Size(336, 96)
            Me.Label1.TabIndex = 35
            Me.Label1.Text = "Repairs"
            Me.Label1.TextAlign = System.Drawing.ContentAlignment.MiddleCenter
            '
            'ApplicationSubmissionLabel
            '
            Me.ApplicationSubmissionLabel.BackColor = System.Drawing.Color.Transparent
            Me.ApplicationSubmissionLabel.Font = New System.Drawing.Font("Microsoft YaHei", 9.0!)
            Me.ApplicationSubmissionLabel.ForeColor = System.Drawing.Color.White
            Me.ApplicationSubmissionLabel.Location = New System.Drawing.Point(17, 213)
            Me.ApplicationSubmissionLabel.Margin = New System.Windows.Forms.Padding(4, 0, 4, 0)
            Me.ApplicationSubmissionLabel.Name = "ApplicationSubmissionLabel"
            Me.ApplicationSubmissionLabel.Size = New System.Drawing.Size(197, 25)
            Me.ApplicationSubmissionLabel.TabIndex = 1
            Me.ApplicationSubmissionLabel.Text = "Application Submission"
            Me.ApplicationSubmissionLabel.TextAlign = System.Drawing.ContentAlignment.MiddleCenter
            '
            'ApplicationSubmission_dateTimePicker
            '
            Me.ApplicationSubmission_dateTimePicker.CustomFormat = "MM/dd/yyyy"
            Me.ApplicationSubmission_dateTimePicker.Font = New System.Drawing.Font("Microsoft YaHei", 9.0!)
            Me.ApplicationSubmission_dateTimePicker.Format = System.Windows.Forms.DateTimePickerFormat.Custom
            Me.ApplicationSubmission_dateTimePicker.Location = New System.Drawing.Point(223, 213)
            Me.ApplicationSubmission_dateTimePicker.Margin = New System.Windows.Forms.Padding(4, 4, 4, 4)
            Me.ApplicationSubmission_dateTimePicker.Name = "ApplicationSubmission_dateTimePicker"
            Me.ApplicationSubmission_dateTimePicker.Size = New System.Drawing.Size(265, 27)
            Me.ApplicationSubmission_dateTimePicker.TabIndex = 2
            Me.ApplicationSubmission_dateTimePicker.Value = New Date(2020, 2, 29, 0, 0, 0, 0)
            '
            'AdditionalDocumentsLabel
            '
            Me.AdditionalDocumentsLabel.BackColor = System.Drawing.Color.Transparent
            Me.AdditionalDocumentsLabel.Font = New System.Drawing.Font("Microsoft YaHei", 9.0!)
            Me.AdditionalDocumentsLabel.ForeColor = System.Drawing.Color.White
            Me.AdditionalDocumentsLabel.Location = New System.Drawing.Point(497, 213)
            Me.AdditionalDocumentsLabel.Margin = New System.Windows.Forms.Padding(4, 0, 4, 0)
            Me.AdditionalDocumentsLabel.Name = "AdditionalDocumentsLabel"
            Me.AdditionalDocumentsLabel.Size = New System.Drawing.Size(197, 25)
            Me.AdditionalDocumentsLabel.TabIndex = 3
            Me.AdditionalDocumentsLabel.Text = "AdditionalDocuments"
            Me.AdditionalDocumentsLabel.TextAlign = System.Drawing.ContentAlignment.MiddleCenter
            '
            'AdditionalDocuments_dateTimePicker
            '
            Me.AdditionalDocuments_dateTimePicker.CustomFormat = "MM/dd/yyyy"
            Me.AdditionalDocuments_dateTimePicker.Font = New System.Drawing.Font("Microsoft YaHei", 9.0!)
            Me.AdditionalDocuments_dateTimePicker.Format = System.Windows.Forms.DateTimePickerFormat.Custom
            Me.AdditionalDocuments_dateTimePicker.Location = New System.Drawing.Point(703, 213)
            Me.AdditionalDocuments_dateTimePicker.Margin = New System.Windows.Forms.Padding(4, 4, 4, 4)
            Me.AdditionalDocuments_dateTimePicker.Name = "AdditionalDocuments_dateTimePicker"
            Me.AdditionalDocuments_dateTimePicker.Size = New System.Drawing.Size(265, 27)
            Me.AdditionalDocuments_dateTimePicker.TabIndex = 4
            Me.AdditionalDocuments_dateTimePicker.Value = New Date(2020, 2, 29, 0, 0, 0, 0)
            '
            'ApprovalSiteVisitLabel
            '
            Me.ApprovalSiteVisitLabel.BackColor = System.Drawing.Color.Transparent
            Me.ApprovalSiteVisitLabel.Font = New System.Drawing.Font("Microsoft YaHei", 9.0!)
            Me.ApprovalSiteVisitLabel.ForeColor = System.Drawing.Color.White
            Me.ApprovalSiteVisitLabel.Location = New System.Drawing.Point(17, 260)
            Me.ApprovalSiteVisitLabel.Margin = New System.Windows.Forms.Padding(4, 0, 4, 0)
            Me.ApprovalSiteVisitLabel.Name = "ApprovalSiteVisitLabel"
            Me.ApprovalSiteVisitLabel.Size = New System.Drawing.Size(197, 25)
            Me.ApprovalSiteVisitLabel.TabIndex = 5
            Me.ApprovalSiteVisitLabel.Text = "Approval Site Visit"
            Me.ApprovalSiteVisitLabel.TextAlign = System.Drawing.ContentAlignment.MiddleCenter
            '
            'ApprovalSiteVisit_dateTimePicker
            '
            Me.ApprovalSiteVisit_dateTimePicker.CustomFormat = "MM/dd/yyyy"
            Me.ApprovalSiteVisit_dateTimePicker.Font = New System.Drawing.Font("Microsoft YaHei", 9.0!)
            Me.ApprovalSiteVisit_dateTimePicker.Format = System.Windows.Forms.DateTimePickerFormat.Custom
            Me.ApprovalSiteVisit_dateTimePicker.Location = New System.Drawing.Point(223, 260)
            Me.ApprovalSiteVisit_dateTimePicker.Margin = New System.Windows.Forms.Padding(4, 4, 4, 4)
            Me.ApprovalSiteVisit_dateTimePicker.Name = "ApprovalSiteVisit_dateTimePicker"
            Me.ApprovalSiteVisit_dateTimePicker.Size = New System.Drawing.Size(265, 27)
            Me.ApprovalSiteVisit_dateTimePicker.TabIndex = 6
            Me.ApprovalSiteVisit_dateTimePicker.Value = New Date(2020, 2, 29, 0, 0, 0, 0)
            '
            'SiteVisitCompleteLabel
            '
            Me.SiteVisitCompleteLabel.BackColor = System.Drawing.Color.Transparent
            Me.SiteVisitCompleteLabel.Font = New System.Drawing.Font("Microsoft YaHei", 9.0!)
            Me.SiteVisitCompleteLabel.ForeColor = System.Drawing.Color.White
            Me.SiteVisitCompleteLabel.Location = New System.Drawing.Point(497, 260)
            Me.SiteVisitCompleteLabel.Margin = New System.Windows.Forms.Padding(4, 0, 4, 0)
            Me.SiteVisitCompleteLabel.Name = "SiteVisitCompleteLabel"
            Me.SiteVisitCompleteLabel.Size = New System.Drawing.Size(197, 25)
            Me.SiteVisitCompleteLabel.TabIndex = 7
            Me.SiteVisitCompleteLabel.Text = "SiteVisitComplete"
            Me.SiteVisitCompleteLabel.TextAlign = System.Drawing.ContentAlignment.MiddleCenter
            '
            'SiteVisitComplete_dateTimePicker
            '
            Me.SiteVisitComplete_dateTimePicker.CustomFormat = "MM/dd/yyyy"
            Me.SiteVisitComplete_dateTimePicker.Font = New System.Drawing.Font("Microsoft YaHei", 9.0!)
            Me.SiteVisitComplete_dateTimePicker.Format = System.Windows.Forms.DateTimePickerFormat.Custom
            Me.SiteVisitComplete_dateTimePicker.Location = New System.Drawing.Point(703, 256)
            Me.SiteVisitComplete_dateTimePicker.Margin = New System.Windows.Forms.Padding(4, 4, 4, 4)
            Me.SiteVisitComplete_dateTimePicker.Name = "SiteVisitComplete_dateTimePicker"
            Me.SiteVisitComplete_dateTimePicker.Size = New System.Drawing.Size(265, 27)
            Me.SiteVisitComplete_dateTimePicker.TabIndex = 8
            Me.SiteVisitComplete_dateTimePicker.Value = New Date(2020, 2, 29, 0, 0, 0, 0)
            '
            'ScopeOfWorkLabel
            '
            Me.ScopeOfWorkLabel.BackColor = System.Drawing.Color.Transparent
            Me.ScopeOfWorkLabel.Font = New System.Drawing.Font("Microsoft YaHei", 9.0!)
            Me.ScopeOfWorkLabel.ForeColor = System.Drawing.Color.White
            Me.ScopeOfWorkLabel.Location = New System.Drawing.Point(17, 308)
            Me.ScopeOfWorkLabel.Margin = New System.Windows.Forms.Padding(4, 0, 4, 0)
            Me.ScopeOfWorkLabel.Name = "ScopeOfWorkLabel"
            Me.ScopeOfWorkLabel.Size = New System.Drawing.Size(197, 25)
            Me.ScopeOfWorkLabel.TabIndex = 9
            Me.ScopeOfWorkLabel.Text = "Scope Of Work"
            Me.ScopeOfWorkLabel.TextAlign = System.Drawing.ContentAlignment.MiddleCenter
            '
            'ScopeOfWork_dateTimePicker
            '
            Me.ScopeOfWork_dateTimePicker.CustomFormat = "MM/dd/yyyy"
            Me.ScopeOfWork_dateTimePicker.Font = New System.Drawing.Font("Microsoft YaHei", 9.0!)
            Me.ScopeOfWork_dateTimePicker.Format = System.Windows.Forms.DateTimePickerFormat.Custom
            Me.ScopeOfWork_dateTimePicker.Location = New System.Drawing.Point(223, 308)
            Me.ScopeOfWork_dateTimePicker.Margin = New System.Windows.Forms.Padding(4, 4, 4, 4)
            Me.ScopeOfWork_dateTimePicker.Name = "ScopeOfWork_dateTimePicker"
            Me.ScopeOfWork_dateTimePicker.Size = New System.Drawing.Size(265, 27)
            Me.ScopeOfWork_dateTimePicker.TabIndex = 10
            Me.ScopeOfWork_dateTimePicker.Value = New Date(2020, 2, 29, 0, 0, 0, 0)
            '
            'ContractCompleteLabel
            '
            Me.ContractCompleteLabel.BackColor = System.Drawing.Color.Transparent
            Me.ContractCompleteLabel.Font = New System.Drawing.Font("Microsoft YaHei", 9.0!)
            Me.ContractCompleteLabel.ForeColor = System.Drawing.Color.White
            Me.ContractCompleteLabel.Location = New System.Drawing.Point(497, 308)
            Me.ContractCompleteLabel.Margin = New System.Windows.Forms.Padding(4, 0, 4, 0)
            Me.ContractCompleteLabel.Name = "ContractCompleteLabel"
            Me.ContractCompleteLabel.Size = New System.Drawing.Size(197, 25)
            Me.ContractCompleteLabel.TabIndex = 11
            Me.ContractCompleteLabel.Text = "ContractComplete"
            Me.ContractCompleteLabel.TextAlign = System.Drawing.ContentAlignment.MiddleCenter
            '
            'ContractComplete_dateTimePicker
            '
            Me.ContractComplete_dateTimePicker.CustomFormat = "MM/dd/yyyy"
            Me.ContractComplete_dateTimePicker.Font = New System.Drawing.Font("Microsoft YaHei", 9.0!)
            Me.ContractComplete_dateTimePicker.Format = System.Windows.Forms.DateTimePickerFormat.Custom
            Me.ContractComplete_dateTimePicker.Location = New System.Drawing.Point(703, 308)
            Me.ContractComplete_dateTimePicker.Margin = New System.Windows.Forms.Padding(4, 4, 4, 4)
            Me.ContractComplete_dateTimePicker.Name = "ContractComplete_dateTimePicker"
            Me.ContractComplete_dateTimePicker.Size = New System.Drawing.Size(265, 27)
            Me.ContractComplete_dateTimePicker.TabIndex = 12
            Me.ContractComplete_dateTimePicker.Value = New Date(2020, 2, 29, 0, 0, 0, 0)
            '
            'WorkCompleteLabel
            '
            Me.WorkCompleteLabel.BackColor = System.Drawing.Color.Transparent
            Me.WorkCompleteLabel.Font = New System.Drawing.Font("Microsoft YaHei", 9.0!)
            Me.WorkCompleteLabel.ForeColor = System.Drawing.Color.White
            Me.WorkCompleteLabel.Location = New System.Drawing.Point(17, 357)
            Me.WorkCompleteLabel.Margin = New System.Windows.Forms.Padding(4, 0, 4, 0)
            Me.WorkCompleteLabel.Name = "WorkCompleteLabel"
            Me.WorkCompleteLabel.Size = New System.Drawing.Size(197, 25)
            Me.WorkCompleteLabel.TabIndex = 13
            Me.WorkCompleteLabel.Text = "Work Complete"
            Me.WorkCompleteLabel.TextAlign = System.Drawing.ContentAlignment.MiddleCenter
            '
            'WorkComplete_dateTimePicker
            '
            Me.WorkComplete_dateTimePicker.CustomFormat = "MM/dd/yyyy"
            Me.WorkComplete_dateTimePicker.Font = New System.Drawing.Font("Microsoft YaHei", 9.0!)
            Me.WorkComplete_dateTimePicker.Format = System.Windows.Forms.DateTimePickerFormat.Custom
            Me.WorkComplete_dateTimePicker.Location = New System.Drawing.Point(223, 357)
            Me.WorkComplete_dateTimePicker.Margin = New System.Windows.Forms.Padding(4, 4, 4, 4)
            Me.WorkComplete_dateTimePicker.Name = "WorkComplete_dateTimePicker"
            Me.WorkComplete_dateTimePicker.Size = New System.Drawing.Size(265, 27)
            Me.WorkComplete_dateTimePicker.TabIndex = 14
            Me.WorkComplete_dateTimePicker.Value = New Date(2020, 2, 29, 0, 0, 0, 0)
            '
            'IDDocumentsLabel
            '
            Me.IDDocumentsLabel.BackColor = System.Drawing.Color.Transparent
            Me.IDDocumentsLabel.Font = New System.Drawing.Font("Microsoft YaHei", 9.0!)
            Me.IDDocumentsLabel.ForeColor = System.Drawing.Color.White
            Me.IDDocumentsLabel.Location = New System.Drawing.Point(660, 443)
            Me.IDDocumentsLabel.Margin = New System.Windows.Forms.Padding(4, 0, 4, 0)
            Me.IDDocumentsLabel.Name = "IDDocumentsLabel"
            Me.IDDocumentsLabel.Size = New System.Drawing.Size(197, 25)
            Me.IDDocumentsLabel.TabIndex = 15
            Me.IDDocumentsLabel.Text = "ID Documents"
            Me.IDDocumentsLabel.TextAlign = System.Drawing.ContentAlignment.MiddleCenter
            '
            'IDDocumentsTextBox
            '
            Me.IDDocumentsTextBox.Font = New System.Drawing.Font("Microsoft YaHei", 9.0!)
            Me.IDDocumentsTextBox.Location = New System.Drawing.Point(484, 68)
            Me.IDDocumentsTextBox.Margin = New System.Windows.Forms.Padding(4, 4, 4, 4)
            Me.IDDocumentsTextBox.Name = "IDDocumentsTextBox"
            Me.IDDocumentsTextBox.Size = New System.Drawing.Size(132, 27)
            Me.IDDocumentsTextBox.TabIndex = 16
            Me.IDDocumentsTextBox.Visible = False
            '
            'IncomeVerifiedLabel
            '
            Me.IncomeVerifiedLabel.BackColor = System.Drawing.Color.Transparent
            Me.IncomeVerifiedLabel.Font = New System.Drawing.Font("Microsoft YaHei", 9.0!)
            Me.IncomeVerifiedLabel.ForeColor = System.Drawing.Color.White
            Me.IncomeVerifiedLabel.Location = New System.Drawing.Point(20, 492)
            Me.IncomeVerifiedLabel.Margin = New System.Windows.Forms.Padding(4, 0, 4, 0)
            Me.IncomeVerifiedLabel.Name = "IncomeVerifiedLabel"
            Me.IncomeVerifiedLabel.Size = New System.Drawing.Size(197, 25)
            Me.IncomeVerifiedLabel.TabIndex = 17
            Me.IncomeVerifiedLabel.Text = "Income Verified"
            Me.IncomeVerifiedLabel.TextAlign = System.Drawing.ContentAlignment.MiddleCenter
            '
            'IncomeVerifiedTextBox
            '
            Me.IncomeVerifiedTextBox.Font = New System.Drawing.Font("Microsoft YaHei", 9.0!)
            Me.IncomeVerifiedTextBox.Location = New System.Drawing.Point(625, 103)
            Me.IncomeVerifiedTextBox.Margin = New System.Windows.Forms.Padding(4, 4, 4, 4)
            Me.IncomeVerifiedTextBox.Name = "IncomeVerifiedTextBox"
            Me.IncomeVerifiedTextBox.Size = New System.Drawing.Size(132, 27)
            Me.IncomeVerifiedTextBox.TabIndex = 18
            Me.IncomeVerifiedTextBox.Visible = False
            '
            'DeedOfTrustLabel
            '
            Me.DeedOfTrustLabel.BackColor = System.Drawing.Color.Transparent
            Me.DeedOfTrustLabel.Font = New System.Drawing.Font("Microsoft YaHei", 9.0!)
            Me.DeedOfTrustLabel.ForeColor = System.Drawing.Color.White
            Me.DeedOfTrustLabel.Location = New System.Drawing.Point(17, 441)
            Me.DeedOfTrustLabel.Margin = New System.Windows.Forms.Padding(4, 0, 4, 0)
            Me.DeedOfTrustLabel.Name = "DeedOfTrustLabel"
            Me.DeedOfTrustLabel.Size = New System.Drawing.Size(197, 25)
            Me.DeedOfTrustLabel.TabIndex = 19
            Me.DeedOfTrustLabel.Text = "Deed Of Trust"
            Me.DeedOfTrustLabel.TextAlign = System.Drawing.ContentAlignment.MiddleCenter
            '
            'DeedOfTrustTextBox
            '
            Me.DeedOfTrustTextBox.Font = New System.Drawing.Font("Microsoft YaHei", 9.0!)
            Me.DeedOfTrustTextBox.Location = New System.Drawing.Point(625, 68)
            Me.DeedOfTrustTextBox.Margin = New System.Windows.Forms.Padding(4, 4, 4, 4)
            Me.DeedOfTrustTextBox.Name = "DeedOfTrustTextBox"
            Me.DeedOfTrustTextBox.Size = New System.Drawing.Size(132, 27)
            Me.DeedOfTrustTextBox.TabIndex = 20
            Me.DeedOfTrustTextBox.Visible = False
            '
            'TaxBillLabel
            '
            Me.TaxBillLabel.BackColor = System.Drawing.Color.Transparent
            Me.TaxBillLabel.Font = New System.Drawing.Font("Microsoft YaHei", 9.0!)
            Me.TaxBillLabel.ForeColor = System.Drawing.Color.White
            Me.TaxBillLabel.Location = New System.Drawing.Point(20, 539)
            Me.TaxBillLabel.Margin = New System.Windows.Forms.Padding(4, 0, 4, 0)
            Me.TaxBillLabel.Name = "TaxBillLabel"
            Me.TaxBillLabel.Size = New System.Drawing.Size(197, 25)
            Me.TaxBillLabel.TabIndex = 21
            Me.TaxBillLabel.Text = "Tax Bill"
            Me.TaxBillLabel.TextAlign = System.Drawing.ContentAlignment.MiddleCenter
            '
            'TaxBillTextBox
            '
            Me.TaxBillTextBox.Font = New System.Drawing.Font("Microsoft YaHei", 9.0!)
            Me.TaxBillTextBox.Location = New System.Drawing.Point(625, 139)
            Me.TaxBillTextBox.Margin = New System.Windows.Forms.Padding(4, 4, 4, 4)
            Me.TaxBillTextBox.Name = "TaxBillTextBox"
            Me.TaxBillTextBox.Size = New System.Drawing.Size(132, 27)
            Me.TaxBillTextBox.TabIndex = 22
            Me.TaxBillTextBox.Visible = False
            '
            'SatisfactionLabel
            '
            Me.SatisfactionLabel.BackColor = System.Drawing.Color.Transparent
            Me.SatisfactionLabel.Font = New System.Drawing.Font("Microsoft YaHei", 9.0!)
            Me.SatisfactionLabel.ForeColor = System.Drawing.Color.White
            Me.SatisfactionLabel.Location = New System.Drawing.Point(20, 582)
            Me.SatisfactionLabel.Margin = New System.Windows.Forms.Padding(4, 0, 4, 0)
            Me.SatisfactionLabel.Name = "SatisfactionLabel"
            Me.SatisfactionLabel.Size = New System.Drawing.Size(197, 25)
            Me.SatisfactionLabel.TabIndex = 23
            Me.SatisfactionLabel.Text = "Satisfaction"
            Me.SatisfactionLabel.TextAlign = System.Drawing.ContentAlignment.MiddleCenter
            '
            'SatisfactionTextBox
            '
            Me.SatisfactionTextBox.Font = New System.Drawing.Font("Microsoft YaHei", 9.0!)
            Me.SatisfactionTextBox.Location = New System.Drawing.Point(767, 68)
            Me.SatisfactionTextBox.Margin = New System.Windows.Forms.Padding(4, 4, 4, 4)
            Me.SatisfactionTextBox.Name = "SatisfactionTextBox"
            Me.SatisfactionTextBox.Size = New System.Drawing.Size(132, 27)
            Me.SatisfactionTextBox.TabIndex = 24
            Me.SatisfactionTextBox.Visible = False
            '
            'CompletedApplicationLabel
            '
            Me.CompletedApplicationLabel.BackColor = System.Drawing.Color.Transparent
            Me.CompletedApplicationLabel.Font = New System.Drawing.Font("Microsoft YaHei", 9.0!)
            Me.CompletedApplicationLabel.ForeColor = System.Drawing.Color.White
            Me.CompletedApplicationLabel.Location = New System.Drawing.Point(380, 438)
            Me.CompletedApplicationLabel.Margin = New System.Windows.Forms.Padding(4, 0, 4, 0)
            Me.CompletedApplicationLabel.Name = "CompletedApplicationLabel"
            Me.CompletedApplicationLabel.Size = New System.Drawing.Size(197, 25)
            Me.CompletedApplicationLabel.TabIndex = 25
            Me.CompletedApplicationLabel.Text = "Completed Application"
            Me.CompletedApplicationLabel.TextAlign = System.Drawing.ContentAlignment.MiddleCenter
            '
            'CompletedApplicationTextBox
            '
            Me.CompletedApplicationTextBox.Font = New System.Drawing.Font("Microsoft YaHei", 9.0!)
            Me.CompletedApplicationTextBox.Location = New System.Drawing.Point(767, 103)
            Me.CompletedApplicationTextBox.Margin = New System.Windows.Forms.Padding(4, 4, 4, 4)
            Me.CompletedApplicationTextBox.Name = "CompletedApplicationTextBox"
            Me.CompletedApplicationTextBox.Size = New System.Drawing.Size(132, 27)
            Me.CompletedApplicationTextBox.TabIndex = 26
            Me.CompletedApplicationTextBox.Visible = False
            '
            'ParcelReportLabel
            '
            Me.ParcelReportLabel.BackColor = System.Drawing.Color.Transparent
            Me.ParcelReportLabel.Font = New System.Drawing.Font("Microsoft YaHei", 9.0!)
            Me.ParcelReportLabel.ForeColor = System.Drawing.Color.White
            Me.ParcelReportLabel.Location = New System.Drawing.Point(380, 490)
            Me.ParcelReportLabel.Margin = New System.Windows.Forms.Padding(4, 0, 4, 0)
            Me.ParcelReportLabel.Name = "ParcelReportLabel"
            Me.ParcelReportLabel.Size = New System.Drawing.Size(197, 25)
            Me.ParcelReportLabel.TabIndex = 27
            Me.ParcelReportLabel.Text = "Parcel Report"
            Me.ParcelReportLabel.TextAlign = System.Drawing.ContentAlignment.MiddleCenter
            '
            'ParcelReportTextBox
            '
            Me.ParcelReportTextBox.Font = New System.Drawing.Font("Microsoft YaHei", 9.0!)
            Me.ParcelReportTextBox.Location = New System.Drawing.Point(767, 139)
            Me.ParcelReportTextBox.Margin = New System.Windows.Forms.Padding(4, 4, 4, 4)
            Me.ParcelReportTextBox.Name = "ParcelReportTextBox"
            Me.ParcelReportTextBox.Size = New System.Drawing.Size(132, 27)
            Me.ParcelReportTextBox.TabIndex = 28
            Me.ParcelReportTextBox.Visible = False
            '
            'GISAssessmentLabel
            '
            Me.GISAssessmentLabel.BackColor = System.Drawing.Color.Transparent
            Me.GISAssessmentLabel.Font = New System.Drawing.Font("Microsoft YaHei", 9.0!)
            Me.GISAssessmentLabel.ForeColor = System.Drawing.Color.White
            Me.GISAssessmentLabel.Location = New System.Drawing.Point(380, 538)
            Me.GISAssessmentLabel.Margin = New System.Windows.Forms.Padding(4, 0, 4, 0)
            Me.GISAssessmentLabel.Name = "GISAssessmentLabel"
            Me.GISAssessmentLabel.Size = New System.Drawing.Size(197, 25)
            Me.GISAssessmentLabel.TabIndex = 29
            Me.GISAssessmentLabel.Text = "GIS Assessment"
            Me.GISAssessmentLabel.TextAlign = System.Drawing.ContentAlignment.MiddleCenter
            '
            'GISAssessmentTextBox
            '
            Me.GISAssessmentTextBox.Font = New System.Drawing.Font("Microsoft YaHei", 9.0!)
            Me.GISAssessmentTextBox.Location = New System.Drawing.Point(908, 103)
            Me.GISAssessmentTextBox.Margin = New System.Windows.Forms.Padding(4, 4, 4, 4)
            Me.GISAssessmentTextBox.Name = "GISAssessmentTextBox"
            Me.GISAssessmentTextBox.Size = New System.Drawing.Size(132, 27)
            Me.GISAssessmentTextBox.TabIndex = 30
            Me.GISAssessmentTextBox.Visible = False
            '
            'FundingSourceLabel
            '
            Me.FundingSourceLabel.BackColor = System.Drawing.Color.Transparent
            Me.FundingSourceLabel.Font = New System.Drawing.Font("Microsoft YaHei", 9.0!)
            Me.FundingSourceLabel.ForeColor = System.Drawing.Color.White
            Me.FundingSourceLabel.Location = New System.Drawing.Point(380, 583)
            Me.FundingSourceLabel.Margin = New System.Windows.Forms.Padding(4, 0, 4, 0)
            Me.FundingSourceLabel.Name = "FundingSourceLabel"
            Me.FundingSourceLabel.Size = New System.Drawing.Size(197, 25)
            Me.FundingSourceLabel.TabIndex = 31
            Me.FundingSourceLabel.Text = "Funding Source"
            Me.FundingSourceLabel.TextAlign = System.Drawing.ContentAlignment.MiddleCenter
            '
            'FundingSourceTextBox
            '
            Me.FundingSourceTextBox.Font = New System.Drawing.Font("Microsoft YaHei", 9.0!)
            Me.FundingSourceTextBox.Location = New System.Drawing.Point(908, 143)
            Me.FundingSourceTextBox.Margin = New System.Windows.Forms.Padding(4, 4, 4, 4)
            Me.FundingSourceTextBox.Name = "FundingSourceTextBox"
            Me.FundingSourceTextBox.Size = New System.Drawing.Size(132, 27)
            Me.FundingSourceTextBox.TabIndex = 32
            Me.FundingSourceTextBox.Visible = False
            '
            'General_Info_UIDLabel
            '
            Me.General_Info_UIDLabel.Enabled = False
            Me.General_Info_UIDLabel.Font = New System.Drawing.Font("Microsoft YaHei", 9.0!)
            Me.General_Info_UIDLabel.Location = New System.Drawing.Point(17, 149)
            Me.General_Info_UIDLabel.Margin = New System.Windows.Forms.Padding(4, 0, 4, 0)
            Me.General_Info_UIDLabel.Name = "General_Info_UIDLabel"
            Me.General_Info_UIDLabel.Size = New System.Drawing.Size(197, 25)
            Me.General_Info_UIDLabel.TabIndex = 33
            Me.General_Info_UIDLabel.Text = "Applicant ID"
            Me.General_Info_UIDLabel.TextAlign = System.Drawing.ContentAlignment.MiddleCenter
            '
            'General_Info_UID_comboBox
            '
            Me.General_Info_UID_comboBox.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.Append
            Me.General_Info_UID_comboBox.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.ListItems
            Me.General_Info_UID_comboBox.Font = New System.Drawing.Font("Microsoft YaHei", 9.0!)
            Me.General_Info_UID_comboBox.FormattingEnabled = True
            Me.General_Info_UID_comboBox.Location = New System.Drawing.Point(221, 149)
            Me.General_Info_UID_comboBox.Margin = New System.Windows.Forms.Padding(4, 4, 4, 4)
            Me.General_Info_UID_comboBox.Name = "General_Info_UID_comboBox"
            Me.General_Info_UID_comboBox.Size = New System.Drawing.Size(265, 28)
            Me.General_Info_UID_comboBox.TabIndex = 34
            '
            'mStripMENUBAR
            '
            Me.mStripMENUBAR.ImageScalingSize = New System.Drawing.Size(20, 20)
            Me.mStripMENUBAR.Items.AddRange(New System.Windows.Forms.ToolStripItem() {Me.tstripMainMenu, Me.tstripGeneral, Me.tstripHomeownership, Me.RepairsToolStripMenuItem})
            Me.mStripMENUBAR.Location = New System.Drawing.Point(0, 0)
            Me.mStripMENUBAR.Name = "mStripMENUBAR"
            Me.mStripMENUBAR.Padding = New System.Windows.Forms.Padding(5, 2, 0, 2)
            Me.mStripMENUBAR.Size = New System.Drawing.Size(1114, 28)
            Me.mStripMENUBAR.TabIndex = 108
            Me.mStripMENUBAR.Text = "MenuStrip1"
            '
            'tstripMainMenu
            '
            Me.tstripMainMenu.Name = "tstripMainMenu"
            Me.tstripMainMenu.Size = New System.Drawing.Size(97, 24)
            Me.tstripMainMenu.Text = "Main Menu"
            '
            'tstripGeneral
            '
            Me.tstripGeneral.Name = "tstripGeneral"
            Me.tstripGeneral.Size = New System.Drawing.Size(74, 24)
            Me.tstripGeneral.Text = "General"
            '
            'tstripHomeownership
            '
            Me.tstripHomeownership.Name = "tstripHomeownership"
            Me.tstripHomeownership.Size = New System.Drawing.Size(132, 24)
            Me.tstripHomeownership.Text = "Homeownership"
            '
            'RepairsToolStripMenuItem
            '
            Me.RepairsToolStripMenuItem.Enabled = False
            Me.RepairsToolStripMenuItem.Name = "RepairsToolStripMenuItem"
            Me.RepairsToolStripMenuItem.Size = New System.Drawing.Size(72, 24)
            Me.RepairsToolStripMenuItem.Text = "Repairs"
            '
            'panel3
            '
            Me.panel3.Controls.Add(Me.Panel1)
            Me.panel3.Controls.Add(Me.panel4)
            Me.panel3.Controls.Add(Me.panel5)
            Me.panel3.Controls.Add(Me.panel6)
            Me.panel3.Dock = System.Windows.Forms.DockStyle.Fill
            Me.panel3.Location = New System.Drawing.Point(0, 27)
            Me.panel3.Margin = New System.Windows.Forms.Padding(4, 4, 4, 4)
            Me.panel3.Name = "panel3"
            Me.panel3.Size = New System.Drawing.Size(1140, 638)
            Me.panel3.TabIndex = 19
            '
            'panel4
            '
            Me.panel4.Dock = System.Windows.Forms.DockStyle.Right
            Me.panel4.Location = New System.Drawing.Point(1127, 0)
            Me.panel4.Margin = New System.Windows.Forms.Padding(4, 4, 4, 4)
            Me.panel4.Name = "panel4"
            Me.panel4.Size = New System.Drawing.Size(13, 626)
            Me.panel4.TabIndex = 3
            '
            'panel5
            '
            Me.panel5.Dock = System.Windows.Forms.DockStyle.Left
            Me.panel5.Location = New System.Drawing.Point(0, 0)
            Me.panel5.Margin = New System.Windows.Forms.Padding(4, 4, 4, 4)
            Me.panel5.Name = "panel5"
            Me.panel5.Size = New System.Drawing.Size(13, 626)
            Me.panel5.TabIndex = 5
            '
            'panel6
            '
            Me.panel6.Dock = System.Windows.Forms.DockStyle.Bottom
            Me.panel6.Location = New System.Drawing.Point(0, 626)
            Me.panel6.Margin = New System.Windows.Forms.Padding(4, 4, 4, 4)
            Me.panel6.Name = "panel6"
            Me.panel6.Size = New System.Drawing.Size(1140, 12)
            Me.panel6.TabIndex = 6
            '
            'frmrepairs
            '
            Me.AutoScaleDimensions = New System.Drawing.SizeF(8.0!, 16.0!)
            Me.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font
            Me.ClientSize = New System.Drawing.Size(1140, 665)
            Me.Controls.Add(Me.panel3)
            Me.Controls.Add(Me.BindingNavigator1)
            Me.MainMenuStrip = Me.mStripMENUBAR
            Me.Margin = New System.Windows.Forms.Padding(4, 4, 4, 4)
            Me.Name = "frmrepairs"
            Me.Text = "Repairs"
            CType(Me.BindingNavigator1, System.ComponentModel.ISupportInitialize).EndInit()
            Me.BindingNavigator1.ResumeLayout(False)
            Me.BindingNavigator1.PerformLayout()
            CType(Me.repairsBindingSource, System.ComponentModel.ISupportInitialize).EndInit()
            CType(Me.ErrorProvider1, System.ComponentModel.ISupportInitialize).EndInit()
            Me.Panel1.ResumeLayout(False)
            Me.Panel1.PerformLayout()
            CType(Me.PictureBox1, System.ComponentModel.ISupportInitialize).EndInit()
            Me.mStripMENUBAR.ResumeLayout(False)
            Me.mStripMENUBAR.PerformLayout()
            Me.panel3.ResumeLayout(False)
            Me.panel3.PerformLayout()
            Me.ResumeLayout(False)
            Me.PerformLayout()

        End Sub
        Friend WithEvents BindingNavigator1 As System.Windows.Forms.BindingNavigator
		Friend WithEvents BindingNavigatorAddNewItem As System.Windows.Forms.ToolStripButton
		Friend WithEvents BindingNavigatorCountItem As System.Windows.Forms.ToolStripLabel
		Friend WithEvents BindingNavigatorDeleteItem As System.Windows.Forms.ToolStripButton
		Friend WithEvents BindingNavigatorMoveFirstItem As System.Windows.Forms.ToolStripButton
		Friend WithEvents BindingNavigatorMovePreviousItem As System.Windows.Forms.ToolStripButton
		Friend WithEvents BindingNavigatorSeparator As System.Windows.Forms.ToolStripSeparator
		Friend WithEvents BindingNavigatorPositionItem As System.Windows.Forms.ToolStripTextBox
		Friend WithEvents BindingNavigatorSeparator1 As System.Windows.Forms.ToolStripSeparator
		Friend WithEvents BindingNavigatorMoveNextItem As System.Windows.Forms.ToolStripButton
		Friend WithEvents BindingNavigatorMoveLastItem As System.Windows.Forms.ToolStripButton
		Friend WithEvents BindingNavigatorSeparator2 As System.Windows.Forms.ToolStripSeparator
		Friend WithEvents ToolStripButton1 As System.Windows.Forms.ToolStripButton
		Friend WithEvents ErrorProvider1 As System.Windows.Forms.ErrorProvider
		Friend WithEvents Panel1 As System.Windows.Forms.Panel
		Friend WithEvents repairsBindingSource As System.Windows.Forms.BindingSource
		Friend WithEvents ApplicationSubmission_dateTimePicker As System.Windows.Forms.DateTimePicker
		Friend WithEvents ApplicationSubmissionLabel As System.Windows.Forms.Label
		Friend WithEvents AdditionalDocuments_dateTimePicker As System.Windows.Forms.DateTimePicker
		Friend WithEvents AdditionalDocumentsLabel As System.Windows.Forms.Label
		Friend WithEvents ApprovalSiteVisit_dateTimePicker As System.Windows.Forms.DateTimePicker
		Friend WithEvents ApprovalSiteVisitLabel As System.Windows.Forms.Label
		Friend WithEvents SiteVisitComplete_dateTimePicker As System.Windows.Forms.DateTimePicker
		Friend WithEvents SiteVisitCompleteLabel As System.Windows.Forms.Label
		Friend WithEvents ScopeOfWork_dateTimePicker As System.Windows.Forms.DateTimePicker
		Friend WithEvents ScopeOfWorkLabel As System.Windows.Forms.Label
		Friend WithEvents ContractComplete_dateTimePicker As System.Windows.Forms.DateTimePicker
		Friend WithEvents ContractCompleteLabel As System.Windows.Forms.Label
		Friend WithEvents WorkComplete_dateTimePicker As System.Windows.Forms.DateTimePicker
		Friend WithEvents WorkCompleteLabel As System.Windows.Forms.Label
		Friend WithEvents IDDocumentsTextBox As System.Windows.Forms.TextBox
		Friend WithEvents IDDocumentsLabel As System.Windows.Forms.Label
		Friend WithEvents IncomeVerifiedTextBox As System.Windows.Forms.TextBox
		Friend WithEvents IncomeVerifiedLabel As System.Windows.Forms.Label
		Friend WithEvents DeedOfTrustTextBox As System.Windows.Forms.TextBox
		Friend WithEvents DeedOfTrustLabel As System.Windows.Forms.Label
		Friend WithEvents TaxBillTextBox As System.Windows.Forms.TextBox
		Friend WithEvents TaxBillLabel As System.Windows.Forms.Label
		Friend WithEvents SatisfactionTextBox As System.Windows.Forms.TextBox
		Friend WithEvents SatisfactionLabel As System.Windows.Forms.Label
		Friend WithEvents CompletedApplicationTextBox As System.Windows.Forms.TextBox
		Friend WithEvents CompletedApplicationLabel As System.Windows.Forms.Label
		Friend WithEvents ParcelReportTextBox As System.Windows.Forms.TextBox
		Friend WithEvents ParcelReportLabel As System.Windows.Forms.Label
		Friend WithEvents GISAssessmentTextBox As System.Windows.Forms.TextBox
		Friend WithEvents GISAssessmentLabel As System.Windows.Forms.Label
		Friend WithEvents FundingSourceTextBox As System.Windows.Forms.TextBox
		Friend WithEvents FundingSourceLabel As System.Windows.Forms.Label
		Friend WithEvents General_Info_UID_comboBox As System.Windows.Forms.ComboBox
		Friend WithEvents General_Info_UIDLabel As System.Windows.Forms.Label
		Friend WithEvents panel3 As System.Windows.Forms.Panel
		Friend WithEvents panel4 As System.Windows.Forms.Panel
		Friend WithEvents panel5 As System.Windows.Forms.Panel
		Friend WithEvents panel6 As System.Windows.Forms.Panel
        Friend WithEvents Label1 As Label
        Friend WithEvents PictureBox1 As PictureBox
        Friend WithEvents chkIncomeVerified As CheckBox
        Friend WithEvents chkIDDocs As CheckBox
        Friend WithEvents chkFundSource As CheckBox
        Friend WithEvents chkGISAssessment As CheckBox
        Friend WithEvents chkParcelReport As CheckBox
        Friend WithEvents chkCompletedApp As CheckBox
        Friend WithEvents chkSatisfaction As CheckBox
        Friend WithEvents chkTaxBill As CheckBox
        Friend WithEvents chkDeed As CheckBox
        Friend WithEvents mStripMENUBAR As MenuStrip
        Friend WithEvents tstripMainMenu As ToolStripMenuItem
        Friend WithEvents tstripGeneral As ToolStripMenuItem
        Friend WithEvents tstripHomeownership As ToolStripMenuItem
        Friend WithEvents RepairsToolStripMenuItem As ToolStripMenuItem
    End Class

End Namespace
