' ++++++++++++++++++++++++++++++++++++++++++++++++++
' This code is generated by a tool and is provided "as is", without warranty of any kind,
' express or implied, including but not limited to the warranties of merchantability,
' fitness for a particular purpose and non-infringement.
' In no event shall the authors or copyright holders be liable for any claim, damages or
' other liability, whether in an action of contract, tort or otherwise, arising from,
' out of or in connection with the software or the use or other dealings in the software.
' ++++++++++++++++++++++++++++++++++++++++++++++++++
' 

Namespace DatabaseTestApplication2
	
	<Global.Microsoft.VisualBasic.CompilerServices.DesignerGenerated()> _
	Partial Class frmsurvey
		Inherits System.Windows.Forms.Form
		
		'Form overrides dispose to clean up the component list.
		<System.Diagnostics.DebuggerNonUserCode()> _
		Protected Overrides Sub Dispose(ByVal disposing As Boolean)
			Try
			If disposing AndAlso components IsNot Nothing Then
				components.Dispose()
			End If
			Finally
			MyBase.Dispose(disposing)
			End Try
		End Sub
		
		'Required by the Windows Form Designer
		Private components As System.ComponentModel.IContainer
		
		'NOTE: The following procedure is required by the Windows Form Designer
		'It can be modified using the Windows Form Designer.  
		'Do not modify it using the code editor.
		<System.Diagnostics.DebuggerStepThrough()> _
		Private Sub InitializeComponent()
            Me.components = New System.ComponentModel.Container()
            Dim resources As System.ComponentModel.ComponentResourceManager = New System.ComponentModel.ComponentResourceManager(GetType(frmsurvey))
            Me.BindingNavigator1 = New System.Windows.Forms.BindingNavigator(Me.components)
            Me.surveyBindingSource = New System.Windows.Forms.BindingSource(Me.components)
            Me.BindingNavigatorCountItem = New System.Windows.Forms.ToolStripLabel()
            Me.BindingNavigatorDeleteItem = New System.Windows.Forms.ToolStripButton()
            Me.BindingNavigatorMoveFirstItem = New System.Windows.Forms.ToolStripButton()
            Me.BindingNavigatorMovePreviousItem = New System.Windows.Forms.ToolStripButton()
            Me.BindingNavigatorSeparator = New System.Windows.Forms.ToolStripSeparator()
            Me.BindingNavigatorPositionItem = New System.Windows.Forms.ToolStripTextBox()
            Me.BindingNavigatorSeparator1 = New System.Windows.Forms.ToolStripSeparator()
            Me.BindingNavigatorMoveNextItem = New System.Windows.Forms.ToolStripButton()
            Me.BindingNavigatorMoveLastItem = New System.Windows.Forms.ToolStripButton()
            Me.BindingNavigatorSeparator2 = New System.Windows.Forms.ToolStripSeparator()
            Me.BindingNavigatorAddNewItem = New System.Windows.Forms.ToolStripButton()
            Me.ToolStripButton1 = New System.Windows.Forms.ToolStripButton()
            Me.ErrorProvider1 = New System.Windows.Forms.ErrorProvider(Me.components)
            Me.Panel1 = New System.Windows.Forms.Panel()
            Me.PictureBox1 = New System.Windows.Forms.PictureBox()
            Me.NotesLabel = New System.Windows.Forms.Label()
            Me.NotesTextBox = New System.Windows.Forms.TextBox()
            Me.Question1Label = New System.Windows.Forms.Label()
            Me.Question1TextBox = New System.Windows.Forms.TextBox()
            Me.Question10Label = New System.Windows.Forms.Label()
            Me.Question10TextBox = New System.Windows.Forms.TextBox()
            Me.Question11Label = New System.Windows.Forms.Label()
            Me.Question11TextBox = New System.Windows.Forms.TextBox()
            Me.Question12Label = New System.Windows.Forms.Label()
            Me.Question12TextBox = New System.Windows.Forms.TextBox()
            Me.Question13Label = New System.Windows.Forms.Label()
            Me.Question13TextBox = New System.Windows.Forms.TextBox()
            Me.Question14Label = New System.Windows.Forms.Label()
            Me.Question14TextBox = New System.Windows.Forms.TextBox()
            Me.Question15Label = New System.Windows.Forms.Label()
            Me.Question15TextBox = New System.Windows.Forms.TextBox()
            Me.Question16Label = New System.Windows.Forms.Label()
            Me.Question16TextBox = New System.Windows.Forms.TextBox()
            Me.Question17Label = New System.Windows.Forms.Label()
            Me.Question17TextBox = New System.Windows.Forms.TextBox()
            Me.Question18Label = New System.Windows.Forms.Label()
            Me.Question18TextBox = New System.Windows.Forms.TextBox()
            Me.Question19Label = New System.Windows.Forms.Label()
            Me.Question19TextBox = New System.Windows.Forms.TextBox()
            Me.Question2Label = New System.Windows.Forms.Label()
            Me.Question2TextBox = New System.Windows.Forms.TextBox()
            Me.Question20Label = New System.Windows.Forms.Label()
            Me.Question20TextBox = New System.Windows.Forms.TextBox()
            Me.Question21Label = New System.Windows.Forms.Label()
            Me.Question21TextBox = New System.Windows.Forms.TextBox()
            Me.Question22Label = New System.Windows.Forms.Label()
            Me.Question22TextBox = New System.Windows.Forms.TextBox()
            Me.Question23Label = New System.Windows.Forms.Label()
            Me.Question23TextBox = New System.Windows.Forms.TextBox()
            Me.Question24Label = New System.Windows.Forms.Label()
            Me.Question24TextBox = New System.Windows.Forms.TextBox()
            Me.Question25Label = New System.Windows.Forms.Label()
            Me.Question25TextBox = New System.Windows.Forms.TextBox()
            Me.Question26Label = New System.Windows.Forms.Label()
            Me.Question26TextBox = New System.Windows.Forms.TextBox()
            Me.Question27Label = New System.Windows.Forms.Label()
            Me.Question27TextBox = New System.Windows.Forms.TextBox()
            Me.Question28Label = New System.Windows.Forms.Label()
            Me.Question28TextBox = New System.Windows.Forms.TextBox()
            Me.Question29Label = New System.Windows.Forms.Label()
            Me.Question29TextBox = New System.Windows.Forms.TextBox()
            Me.Question3Label = New System.Windows.Forms.Label()
            Me.Question3TextBox = New System.Windows.Forms.TextBox()
            Me.Question30Label = New System.Windows.Forms.Label()
            Me.Question30TextBox = New System.Windows.Forms.TextBox()
            Me.Question31Label = New System.Windows.Forms.Label()
            Me.Question31TextBox = New System.Windows.Forms.TextBox()
            Me.Question32Label = New System.Windows.Forms.Label()
            Me.Question32TextBox = New System.Windows.Forms.TextBox()
            Me.Question33Label = New System.Windows.Forms.Label()
            Me.Question33TextBox = New System.Windows.Forms.TextBox()
            Me.Question34Label = New System.Windows.Forms.Label()
            Me.Question34TextBox = New System.Windows.Forms.TextBox()
            Me.Question35Label = New System.Windows.Forms.Label()
            Me.Question35TextBox = New System.Windows.Forms.TextBox()
            Me.Question36Label = New System.Windows.Forms.Label()
            Me.Question36TextBox = New System.Windows.Forms.TextBox()
            Me.Question37Label = New System.Windows.Forms.Label()
            Me.Question37TextBox = New System.Windows.Forms.TextBox()
            Me.Question38Label = New System.Windows.Forms.Label()
            Me.Question38TextBox = New System.Windows.Forms.TextBox()
            Me.Question39Label = New System.Windows.Forms.Label()
            Me.Question39TextBox = New System.Windows.Forms.TextBox()
            Me.Question4Label = New System.Windows.Forms.Label()
            Me.Question4TextBox = New System.Windows.Forms.TextBox()
            Me.Question40Label = New System.Windows.Forms.Label()
            Me.Question40TextBox = New System.Windows.Forms.TextBox()
            Me.Question41Label = New System.Windows.Forms.Label()
            Me.Question41TextBox = New System.Windows.Forms.TextBox()
            Me.Question42Label = New System.Windows.Forms.Label()
            Me.Question42TextBox = New System.Windows.Forms.TextBox()
            Me.Question43Label = New System.Windows.Forms.Label()
            Me.Question43TextBox = New System.Windows.Forms.TextBox()
            Me.Question44Label = New System.Windows.Forms.Label()
            Me.Question44TextBox = New System.Windows.Forms.TextBox()
            Me.Question45Label = New System.Windows.Forms.Label()
            Me.Question45TextBox = New System.Windows.Forms.TextBox()
            Me.Question46Label = New System.Windows.Forms.Label()
            Me.Question46TextBox = New System.Windows.Forms.TextBox()
            Me.Question47Label = New System.Windows.Forms.Label()
            Me.Question47TextBox = New System.Windows.Forms.TextBox()
            Me.Question48Label = New System.Windows.Forms.Label()
            Me.Question48TextBox = New System.Windows.Forms.TextBox()
            Me.Question49Label = New System.Windows.Forms.Label()
            Me.Question49TextBox = New System.Windows.Forms.TextBox()
            Me.Question5Label = New System.Windows.Forms.Label()
            Me.Question5TextBox = New System.Windows.Forms.TextBox()
            Me.Question50Label = New System.Windows.Forms.Label()
            Me.Question50TextBox = New System.Windows.Forms.TextBox()
            Me.Question6Label = New System.Windows.Forms.Label()
            Me.Question6TextBox = New System.Windows.Forms.TextBox()
            Me.Question7Label = New System.Windows.Forms.Label()
            Me.Question7TextBox = New System.Windows.Forms.TextBox()
            Me.Question8Label = New System.Windows.Forms.Label()
            Me.Question8TextBox = New System.Windows.Forms.TextBox()
            Me.Question9Label = New System.Windows.Forms.Label()
            Me.Question9TextBox = New System.Windows.Forms.TextBox()
            Me.QuestionFileLabel = New System.Windows.Forms.Label()
            Me.QuestionFileTextBox = New System.Windows.Forms.TextBox()
            Me.QuestionNum1Label = New System.Windows.Forms.Label()
            Me.QuestionNum1TextBox = New System.Windows.Forms.TextBox()
            Me.QuestionNum2Label = New System.Windows.Forms.Label()
            Me.QuestionNum2TextBox = New System.Windows.Forms.TextBox()
            Me.QuestionNum3Label = New System.Windows.Forms.Label()
            Me.QuestionNum3TextBox = New System.Windows.Forms.TextBox()
            Me.QuestionNum4Label = New System.Windows.Forms.Label()
            Me.QuestionNum4TextBox = New System.Windows.Forms.TextBox()
            Me.QuestionNum5Label = New System.Windows.Forms.Label()
            Me.QuestionNum5TextBox = New System.Windows.Forms.TextBox()
            Me.SurveyIDLabel = New System.Windows.Forms.Label()
            Me.SurveyIDTextBox = New System.Windows.Forms.TextBox()
            Me.SurveyNameLabel = New System.Windows.Forms.Label()
            Me.SurveyNameTextBox = New System.Windows.Forms.TextBox()
            Me.panel3 = New System.Windows.Forms.Panel()
            Me.panel4 = New System.Windows.Forms.Panel()
            Me.panel5 = New System.Windows.Forms.Panel()
            Me.panel6 = New System.Windows.Forms.Panel()
            Me.Label1 = New System.Windows.Forms.Label()
            CType(Me.BindingNavigator1, System.ComponentModel.ISupportInitialize).BeginInit()
            Me.BindingNavigator1.SuspendLayout()
            CType(Me.surveyBindingSource, System.ComponentModel.ISupportInitialize).BeginInit()
            CType(Me.ErrorProvider1, System.ComponentModel.ISupportInitialize).BeginInit()
            Me.Panel1.SuspendLayout()
            CType(Me.PictureBox1, System.ComponentModel.ISupportInitialize).BeginInit()
            Me.panel3.SuspendLayout()
            Me.SuspendLayout()
            '
            'BindingNavigator1
            '
            Me.BindingNavigator1.AddNewItem = Nothing
            Me.BindingNavigator1.BindingSource = Me.surveyBindingSource
            Me.BindingNavigator1.CountItem = Me.BindingNavigatorCountItem
            Me.BindingNavigator1.DeleteItem = Me.BindingNavigatorDeleteItem
            Me.BindingNavigator1.ImageScalingSize = New System.Drawing.Size(20, 20)
            Me.BindingNavigator1.Items.AddRange(New System.Windows.Forms.ToolStripItem() {Me.BindingNavigatorMoveFirstItem, Me.BindingNavigatorMovePreviousItem, Me.BindingNavigatorSeparator, Me.BindingNavigatorPositionItem, Me.BindingNavigatorCountItem, Me.BindingNavigatorSeparator1, Me.BindingNavigatorMoveNextItem, Me.BindingNavigatorMoveLastItem, Me.BindingNavigatorSeparator2, Me.BindingNavigatorAddNewItem, Me.BindingNavigatorDeleteItem, Me.ToolStripButton1})
            Me.BindingNavigator1.Location = New System.Drawing.Point(0, 0)
            Me.BindingNavigator1.MoveFirstItem = Me.BindingNavigatorMoveFirstItem
            Me.BindingNavigator1.MoveLastItem = Me.BindingNavigatorMoveLastItem
            Me.BindingNavigator1.MoveNextItem = Me.BindingNavigatorMoveNextItem
            Me.BindingNavigator1.MovePreviousItem = Me.BindingNavigatorMovePreviousItem
            Me.BindingNavigator1.Name = "BindingNavigator1"
            Me.BindingNavigator1.Padding = New System.Windows.Forms.Padding(10, 0, 10, 0)
            Me.BindingNavigator1.PositionItem = Me.BindingNavigatorPositionItem
            Me.BindingNavigator1.Size = New System.Drawing.Size(842, 27)
            Me.BindingNavigator1.TabIndex = 0
            Me.BindingNavigator1.Text = "BindingNavigator1"
            '
            'BindingNavigatorCountItem
            '
            Me.BindingNavigatorCountItem.Name = "BindingNavigatorCountItem"
            Me.BindingNavigatorCountItem.Size = New System.Drawing.Size(35, 24)
            Me.BindingNavigatorCountItem.Text = "of {0}"
            Me.BindingNavigatorCountItem.ToolTipText = "Total number of items"
            '
            'BindingNavigatorDeleteItem
            '
            Me.BindingNavigatorDeleteItem.DisplayStyle = System.Windows.Forms.ToolStripItemDisplayStyle.Image
            Me.BindingNavigatorDeleteItem.Image = CType(resources.GetObject("BindingNavigatorDeleteItem.Image"), System.Drawing.Image)
            Me.BindingNavigatorDeleteItem.Name = "BindingNavigatorDeleteItem"
            Me.BindingNavigatorDeleteItem.RightToLeftAutoMirrorImage = True
            Me.BindingNavigatorDeleteItem.Size = New System.Drawing.Size(24, 24)
            Me.BindingNavigatorDeleteItem.Text = "Delete"
            '
            'BindingNavigatorMoveFirstItem
            '
            Me.BindingNavigatorMoveFirstItem.DisplayStyle = System.Windows.Forms.ToolStripItemDisplayStyle.Image
            Me.BindingNavigatorMoveFirstItem.Image = CType(resources.GetObject("BindingNavigatorMoveFirstItem.Image"), System.Drawing.Image)
            Me.BindingNavigatorMoveFirstItem.Name = "BindingNavigatorMoveFirstItem"
            Me.BindingNavigatorMoveFirstItem.RightToLeftAutoMirrorImage = True
            Me.BindingNavigatorMoveFirstItem.Size = New System.Drawing.Size(24, 24)
            Me.BindingNavigatorMoveFirstItem.Text = "Move first"
            '
            'BindingNavigatorMovePreviousItem
            '
            Me.BindingNavigatorMovePreviousItem.DisplayStyle = System.Windows.Forms.ToolStripItemDisplayStyle.Image
            Me.BindingNavigatorMovePreviousItem.Image = CType(resources.GetObject("BindingNavigatorMovePreviousItem.Image"), System.Drawing.Image)
            Me.BindingNavigatorMovePreviousItem.Name = "BindingNavigatorMovePreviousItem"
            Me.BindingNavigatorMovePreviousItem.RightToLeftAutoMirrorImage = True
            Me.BindingNavigatorMovePreviousItem.Size = New System.Drawing.Size(24, 24)
            Me.BindingNavigatorMovePreviousItem.Text = "Move previous"
            '
            'BindingNavigatorSeparator
            '
            Me.BindingNavigatorSeparator.Name = "BindingNavigatorSeparator"
            Me.BindingNavigatorSeparator.Size = New System.Drawing.Size(6, 27)
            '
            'BindingNavigatorPositionItem
            '
            Me.BindingNavigatorPositionItem.AccessibleName = "Position"
            Me.BindingNavigatorPositionItem.AutoSize = False
            Me.BindingNavigatorPositionItem.Font = New System.Drawing.Font("Segoe UI", 9.0!)
            Me.BindingNavigatorPositionItem.Name = "BindingNavigatorPositionItem"
            Me.BindingNavigatorPositionItem.Size = New System.Drawing.Size(50, 23)
            Me.BindingNavigatorPositionItem.Text = "0"
            Me.BindingNavigatorPositionItem.ToolTipText = "Current position"
            '
            'BindingNavigatorSeparator1
            '
            Me.BindingNavigatorSeparator1.Name = "BindingNavigatorSeparator1"
            Me.BindingNavigatorSeparator1.Size = New System.Drawing.Size(6, 27)
            '
            'BindingNavigatorMoveNextItem
            '
            Me.BindingNavigatorMoveNextItem.DisplayStyle = System.Windows.Forms.ToolStripItemDisplayStyle.Image
            Me.BindingNavigatorMoveNextItem.Image = CType(resources.GetObject("BindingNavigatorMoveNextItem.Image"), System.Drawing.Image)
            Me.BindingNavigatorMoveNextItem.Name = "BindingNavigatorMoveNextItem"
            Me.BindingNavigatorMoveNextItem.RightToLeftAutoMirrorImage = True
            Me.BindingNavigatorMoveNextItem.Size = New System.Drawing.Size(24, 24)
            Me.BindingNavigatorMoveNextItem.Text = "Move next"
            '
            'BindingNavigatorMoveLastItem
            '
            Me.BindingNavigatorMoveLastItem.DisplayStyle = System.Windows.Forms.ToolStripItemDisplayStyle.Image
            Me.BindingNavigatorMoveLastItem.Image = CType(resources.GetObject("BindingNavigatorMoveLastItem.Image"), System.Drawing.Image)
            Me.BindingNavigatorMoveLastItem.Name = "BindingNavigatorMoveLastItem"
            Me.BindingNavigatorMoveLastItem.RightToLeftAutoMirrorImage = True
            Me.BindingNavigatorMoveLastItem.Size = New System.Drawing.Size(24, 24)
            Me.BindingNavigatorMoveLastItem.Text = "Move last"
            '
            'BindingNavigatorSeparator2
            '
            Me.BindingNavigatorSeparator2.Name = "BindingNavigatorSeparator2"
            Me.BindingNavigatorSeparator2.Size = New System.Drawing.Size(6, 27)
            '
            'BindingNavigatorAddNewItem
            '
            Me.BindingNavigatorAddNewItem.DisplayStyle = System.Windows.Forms.ToolStripItemDisplayStyle.Image
            Me.BindingNavigatorAddNewItem.Image = CType(resources.GetObject("BindingNavigatorAddNewItem.Image"), System.Drawing.Image)
            Me.BindingNavigatorAddNewItem.Name = "BindingNavigatorAddNewItem"
            Me.BindingNavigatorAddNewItem.RightToLeftAutoMirrorImage = True
            Me.BindingNavigatorAddNewItem.Size = New System.Drawing.Size(24, 24)
            Me.BindingNavigatorAddNewItem.Text = "Add new"
            '
            'ToolStripButton1
            '
            Me.ToolStripButton1.DisplayStyle = System.Windows.Forms.ToolStripItemDisplayStyle.Image
            Me.ToolStripButton1.Image = CType(resources.GetObject("ToolStripButton1.Image"), System.Drawing.Image)
            Me.ToolStripButton1.ImageTransparentColor = System.Drawing.Color.Magenta
            Me.ToolStripButton1.Name = "ToolStripButton1"
            Me.ToolStripButton1.Size = New System.Drawing.Size(24, 24)
            Me.ToolStripButton1.Text = "Save"
            '
            'ErrorProvider1
            '
            Me.ErrorProvider1.ContainerControl = Me
            '
            'Panel1
            '
            Me.Panel1.AutoScroll = True
            Me.Panel1.AutoSize = True
            Me.Panel1.BackColor = System.Drawing.Color.Transparent
            Me.Panel1.BackgroundImage = Global.DatabaseTestApplication2.My.Resources.Resources.angryimg__12_
            Me.Panel1.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch
            Me.Panel1.Controls.Add(Me.Label1)
            Me.Panel1.Controls.Add(Me.PictureBox1)
            Me.Panel1.Controls.Add(Me.NotesLabel)
            Me.Panel1.Controls.Add(Me.NotesTextBox)
            Me.Panel1.Controls.Add(Me.Question1Label)
            Me.Panel1.Controls.Add(Me.Question1TextBox)
            Me.Panel1.Controls.Add(Me.Question10Label)
            Me.Panel1.Controls.Add(Me.Question10TextBox)
            Me.Panel1.Controls.Add(Me.Question11Label)
            Me.Panel1.Controls.Add(Me.Question11TextBox)
            Me.Panel1.Controls.Add(Me.Question12Label)
            Me.Panel1.Controls.Add(Me.Question12TextBox)
            Me.Panel1.Controls.Add(Me.Question13Label)
            Me.Panel1.Controls.Add(Me.Question13TextBox)
            Me.Panel1.Controls.Add(Me.Question14Label)
            Me.Panel1.Controls.Add(Me.Question14TextBox)
            Me.Panel1.Controls.Add(Me.Question15Label)
            Me.Panel1.Controls.Add(Me.Question15TextBox)
            Me.Panel1.Controls.Add(Me.Question16Label)
            Me.Panel1.Controls.Add(Me.Question16TextBox)
            Me.Panel1.Controls.Add(Me.Question17Label)
            Me.Panel1.Controls.Add(Me.Question17TextBox)
            Me.Panel1.Controls.Add(Me.Question18Label)
            Me.Panel1.Controls.Add(Me.Question18TextBox)
            Me.Panel1.Controls.Add(Me.Question19Label)
            Me.Panel1.Controls.Add(Me.Question19TextBox)
            Me.Panel1.Controls.Add(Me.Question2Label)
            Me.Panel1.Controls.Add(Me.Question2TextBox)
            Me.Panel1.Controls.Add(Me.Question20Label)
            Me.Panel1.Controls.Add(Me.Question20TextBox)
            Me.Panel1.Controls.Add(Me.Question21Label)
            Me.Panel1.Controls.Add(Me.Question21TextBox)
            Me.Panel1.Controls.Add(Me.Question22Label)
            Me.Panel1.Controls.Add(Me.Question22TextBox)
            Me.Panel1.Controls.Add(Me.Question23Label)
            Me.Panel1.Controls.Add(Me.Question23TextBox)
            Me.Panel1.Controls.Add(Me.Question24Label)
            Me.Panel1.Controls.Add(Me.Question24TextBox)
            Me.Panel1.Controls.Add(Me.Question25Label)
            Me.Panel1.Controls.Add(Me.Question25TextBox)
            Me.Panel1.Controls.Add(Me.Question26Label)
            Me.Panel1.Controls.Add(Me.Question26TextBox)
            Me.Panel1.Controls.Add(Me.Question27Label)
            Me.Panel1.Controls.Add(Me.Question27TextBox)
            Me.Panel1.Controls.Add(Me.Question28Label)
            Me.Panel1.Controls.Add(Me.Question28TextBox)
            Me.Panel1.Controls.Add(Me.Question29Label)
            Me.Panel1.Controls.Add(Me.Question29TextBox)
            Me.Panel1.Controls.Add(Me.Question3Label)
            Me.Panel1.Controls.Add(Me.Question3TextBox)
            Me.Panel1.Controls.Add(Me.Question30Label)
            Me.Panel1.Controls.Add(Me.Question30TextBox)
            Me.Panel1.Controls.Add(Me.Question31Label)
            Me.Panel1.Controls.Add(Me.Question31TextBox)
            Me.Panel1.Controls.Add(Me.Question32Label)
            Me.Panel1.Controls.Add(Me.Question32TextBox)
            Me.Panel1.Controls.Add(Me.Question33Label)
            Me.Panel1.Controls.Add(Me.Question33TextBox)
            Me.Panel1.Controls.Add(Me.Question34Label)
            Me.Panel1.Controls.Add(Me.Question34TextBox)
            Me.Panel1.Controls.Add(Me.Question35Label)
            Me.Panel1.Controls.Add(Me.Question35TextBox)
            Me.Panel1.Controls.Add(Me.Question36Label)
            Me.Panel1.Controls.Add(Me.Question36TextBox)
            Me.Panel1.Controls.Add(Me.Question37Label)
            Me.Panel1.Controls.Add(Me.Question37TextBox)
            Me.Panel1.Controls.Add(Me.Question38Label)
            Me.Panel1.Controls.Add(Me.Question38TextBox)
            Me.Panel1.Controls.Add(Me.Question39Label)
            Me.Panel1.Controls.Add(Me.Question39TextBox)
            Me.Panel1.Controls.Add(Me.Question4Label)
            Me.Panel1.Controls.Add(Me.Question4TextBox)
            Me.Panel1.Controls.Add(Me.Question40Label)
            Me.Panel1.Controls.Add(Me.Question40TextBox)
            Me.Panel1.Controls.Add(Me.Question41Label)
            Me.Panel1.Controls.Add(Me.Question41TextBox)
            Me.Panel1.Controls.Add(Me.Question42Label)
            Me.Panel1.Controls.Add(Me.Question42TextBox)
            Me.Panel1.Controls.Add(Me.Question43Label)
            Me.Panel1.Controls.Add(Me.Question43TextBox)
            Me.Panel1.Controls.Add(Me.Question44Label)
            Me.Panel1.Controls.Add(Me.Question44TextBox)
            Me.Panel1.Controls.Add(Me.Question45Label)
            Me.Panel1.Controls.Add(Me.Question45TextBox)
            Me.Panel1.Controls.Add(Me.Question46Label)
            Me.Panel1.Controls.Add(Me.Question46TextBox)
            Me.Panel1.Controls.Add(Me.Question47Label)
            Me.Panel1.Controls.Add(Me.Question47TextBox)
            Me.Panel1.Controls.Add(Me.Question48Label)
            Me.Panel1.Controls.Add(Me.Question48TextBox)
            Me.Panel1.Controls.Add(Me.Question49Label)
            Me.Panel1.Controls.Add(Me.Question49TextBox)
            Me.Panel1.Controls.Add(Me.Question5Label)
            Me.Panel1.Controls.Add(Me.Question5TextBox)
            Me.Panel1.Controls.Add(Me.Question50Label)
            Me.Panel1.Controls.Add(Me.Question50TextBox)
            Me.Panel1.Controls.Add(Me.Question6Label)
            Me.Panel1.Controls.Add(Me.Question6TextBox)
            Me.Panel1.Controls.Add(Me.Question7Label)
            Me.Panel1.Controls.Add(Me.Question7TextBox)
            Me.Panel1.Controls.Add(Me.Question8Label)
            Me.Panel1.Controls.Add(Me.Question8TextBox)
            Me.Panel1.Controls.Add(Me.Question9Label)
            Me.Panel1.Controls.Add(Me.Question9TextBox)
            Me.Panel1.Controls.Add(Me.QuestionFileLabel)
            Me.Panel1.Controls.Add(Me.QuestionFileTextBox)
            Me.Panel1.Controls.Add(Me.QuestionNum1Label)
            Me.Panel1.Controls.Add(Me.QuestionNum1TextBox)
            Me.Panel1.Controls.Add(Me.QuestionNum2Label)
            Me.Panel1.Controls.Add(Me.QuestionNum2TextBox)
            Me.Panel1.Controls.Add(Me.QuestionNum3Label)
            Me.Panel1.Controls.Add(Me.QuestionNum3TextBox)
            Me.Panel1.Controls.Add(Me.QuestionNum4Label)
            Me.Panel1.Controls.Add(Me.QuestionNum4TextBox)
            Me.Panel1.Controls.Add(Me.QuestionNum5Label)
            Me.Panel1.Controls.Add(Me.QuestionNum5TextBox)
            Me.Panel1.Controls.Add(Me.SurveyIDLabel)
            Me.Panel1.Controls.Add(Me.SurveyIDTextBox)
            Me.Panel1.Controls.Add(Me.SurveyNameLabel)
            Me.Panel1.Controls.Add(Me.SurveyNameTextBox)
            Me.Panel1.Dock = System.Windows.Forms.DockStyle.Fill
            Me.Panel1.Location = New System.Drawing.Point(10, 0)
            Me.Panel1.Margin = New System.Windows.Forms.Padding(10, 3, 10, 3)
            Me.Panel1.Name = "Panel1"
            Me.Panel1.Size = New System.Drawing.Size(822, 572)
            Me.Panel1.TabIndex = 1
            '
            'PictureBox1
            '
            Me.PictureBox1.BackgroundImage = Global.DatabaseTestApplication2.My.Resources.Resources.CV_HB_Logo_White_400px
            Me.PictureBox1.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Zoom
            Me.PictureBox1.Location = New System.Drawing.Point(505, 10)
            Me.PictureBox1.Name = "PictureBox1"
            Me.PictureBox1.Size = New System.Drawing.Size(285, 80)
            Me.PictureBox1.TabIndex = 119
            Me.PictureBox1.TabStop = False
            '
            'NotesLabel
            '
            Me.NotesLabel.AutoSize = True
            Me.NotesLabel.Location = New System.Drawing.Point(620, 458)
            Me.NotesLabel.Name = "NotesLabel"
            Me.NotesLabel.Size = New System.Drawing.Size(35, 13)
            Me.NotesLabel.TabIndex = 1
            Me.NotesLabel.Text = "Notes"
            '
            'NotesTextBox
            '
            Me.NotesTextBox.Location = New System.Drawing.Point(690, 451)
            Me.NotesTextBox.Name = "NotesTextBox"
            Me.NotesTextBox.Size = New System.Drawing.Size(100, 20)
            Me.NotesTextBox.TabIndex = 2
            '
            'Question1Label
            '
            Me.Question1Label.AutoSize = True
            Me.Question1Label.Location = New System.Drawing.Point(56, 96)
            Me.Question1Label.Name = "Question1Label"
            Me.Question1Label.Size = New System.Drawing.Size(55, 13)
            Me.Question1Label.TabIndex = 3
            Me.Question1Label.Text = "Question1"
            '
            'Question1TextBox
            '
            Me.Question1TextBox.Location = New System.Drawing.Point(147, 96)
            Me.Question1TextBox.Name = "Question1TextBox"
            Me.Question1TextBox.Size = New System.Drawing.Size(100, 20)
            Me.Question1TextBox.TabIndex = 4
            '
            'Question10Label
            '
            Me.Question10Label.AutoSize = True
            Me.Question10Label.Location = New System.Drawing.Point(56, 390)
            Me.Question10Label.Name = "Question10Label"
            Me.Question10Label.Size = New System.Drawing.Size(61, 13)
            Me.Question10Label.TabIndex = 5
            Me.Question10Label.Text = "Question10"
            '
            'Question10TextBox
            '
            Me.Question10TextBox.Location = New System.Drawing.Point(147, 417)
            Me.Question10TextBox.Name = "Question10TextBox"
            Me.Question10TextBox.Size = New System.Drawing.Size(100, 20)
            Me.Question10TextBox.TabIndex = 6
            '
            'Question11Label
            '
            Me.Question11Label.AutoSize = True
            Me.Question11Label.Location = New System.Drawing.Point(56, 424)
            Me.Question11Label.Name = "Question11Label"
            Me.Question11Label.Size = New System.Drawing.Size(61, 13)
            Me.Question11Label.TabIndex = 7
            Me.Question11Label.Text = "Question11"
            '
            'Question11TextBox
            '
            Me.Question11TextBox.Location = New System.Drawing.Point(147, 387)
            Me.Question11TextBox.Name = "Question11TextBox"
            Me.Question11TextBox.Size = New System.Drawing.Size(100, 20)
            Me.Question11TextBox.TabIndex = 8
            '
            'Question12Label
            '
            Me.Question12Label.AutoSize = True
            Me.Question12Label.Location = New System.Drawing.Point(56, 454)
            Me.Question12Label.Name = "Question12Label"
            Me.Question12Label.Size = New System.Drawing.Size(61, 13)
            Me.Question12Label.TabIndex = 9
            Me.Question12Label.Text = "Question12"
            '
            'Question12TextBox
            '
            Me.Question12TextBox.Location = New System.Drawing.Point(147, 451)
            Me.Question12TextBox.Name = "Question12TextBox"
            Me.Question12TextBox.Size = New System.Drawing.Size(100, 20)
            Me.Question12TextBox.TabIndex = 10
            '
            'Question13Label
            '
            Me.Question13Label.AutoSize = True
            Me.Question13Label.Location = New System.Drawing.Point(56, 485)
            Me.Question13Label.Name = "Question13Label"
            Me.Question13Label.Size = New System.Drawing.Size(61, 13)
            Me.Question13Label.TabIndex = 11
            Me.Question13Label.Text = "Question13"
            '
            'Question13TextBox
            '
            Me.Question13TextBox.Location = New System.Drawing.Point(147, 485)
            Me.Question13TextBox.Name = "Question13TextBox"
            Me.Question13TextBox.Size = New System.Drawing.Size(100, 20)
            Me.Question13TextBox.TabIndex = 12
            '
            'Question14Label
            '
            Me.Question14Label.AutoSize = True
            Me.Question14Label.Location = New System.Drawing.Point(56, 519)
            Me.Question14Label.Name = "Question14Label"
            Me.Question14Label.Size = New System.Drawing.Size(61, 13)
            Me.Question14Label.TabIndex = 13
            Me.Question14Label.Text = "Question14"
            '
            'Question14TextBox
            '
            Me.Question14TextBox.Location = New System.Drawing.Point(147, 519)
            Me.Question14TextBox.Name = "Question14TextBox"
            Me.Question14TextBox.Size = New System.Drawing.Size(100, 20)
            Me.Question14TextBox.TabIndex = 14
            '
            'Question15Label
            '
            Me.Question15Label.AutoSize = True
            Me.Question15Label.Location = New System.Drawing.Point(56, 551)
            Me.Question15Label.Name = "Question15Label"
            Me.Question15Label.Size = New System.Drawing.Size(61, 13)
            Me.Question15Label.TabIndex = 15
            Me.Question15Label.Text = "Question15"
            '
            'Question15TextBox
            '
            Me.Question15TextBox.Location = New System.Drawing.Point(147, 548)
            Me.Question15TextBox.Name = "Question15TextBox"
            Me.Question15TextBox.Size = New System.Drawing.Size(100, 20)
            Me.Question15TextBox.TabIndex = 16
            '
            'Question16Label
            '
            Me.Question16Label.AutoSize = True
            Me.Question16Label.Location = New System.Drawing.Point(56, 582)
            Me.Question16Label.Name = "Question16Label"
            Me.Question16Label.Size = New System.Drawing.Size(61, 13)
            Me.Question16Label.TabIndex = 17
            Me.Question16Label.Text = "Question16"
            '
            'Question16TextBox
            '
            Me.Question16TextBox.Location = New System.Drawing.Point(147, 582)
            Me.Question16TextBox.Name = "Question16TextBox"
            Me.Question16TextBox.Size = New System.Drawing.Size(100, 20)
            Me.Question16TextBox.TabIndex = 18
            '
            'Question17Label
            '
            Me.Question17Label.AutoSize = True
            Me.Question17Label.Location = New System.Drawing.Point(56, 616)
            Me.Question17Label.Name = "Question17Label"
            Me.Question17Label.Size = New System.Drawing.Size(61, 13)
            Me.Question17Label.TabIndex = 19
            Me.Question17Label.Text = "Question17"
            '
            'Question17TextBox
            '
            Me.Question17TextBox.Location = New System.Drawing.Point(147, 616)
            Me.Question17TextBox.Name = "Question17TextBox"
            Me.Question17TextBox.Size = New System.Drawing.Size(100, 20)
            Me.Question17TextBox.TabIndex = 20
            '
            'Question18Label
            '
            Me.Question18Label.AutoSize = True
            Me.Question18Label.Location = New System.Drawing.Point(56, 650)
            Me.Question18Label.Name = "Question18Label"
            Me.Question18Label.Size = New System.Drawing.Size(61, 13)
            Me.Question18Label.TabIndex = 21
            Me.Question18Label.Text = "Question18"
            '
            'Question18TextBox
            '
            Me.Question18TextBox.Location = New System.Drawing.Point(147, 650)
            Me.Question18TextBox.Name = "Question18TextBox"
            Me.Question18TextBox.Size = New System.Drawing.Size(100, 20)
            Me.Question18TextBox.TabIndex = 22
            '
            'Question19Label
            '
            Me.Question19Label.AutoSize = True
            Me.Question19Label.Location = New System.Drawing.Point(56, 684)
            Me.Question19Label.Name = "Question19Label"
            Me.Question19Label.Size = New System.Drawing.Size(61, 13)
            Me.Question19Label.TabIndex = 23
            Me.Question19Label.Text = "Question19"
            '
            'Question19TextBox
            '
            Me.Question19TextBox.Location = New System.Drawing.Point(147, 684)
            Me.Question19TextBox.Name = "Question19TextBox"
            Me.Question19TextBox.Size = New System.Drawing.Size(100, 20)
            Me.Question19TextBox.TabIndex = 24
            '
            'Question2Label
            '
            Me.Question2Label.AutoSize = True
            Me.Question2Label.Location = New System.Drawing.Point(56, 127)
            Me.Question2Label.Name = "Question2Label"
            Me.Question2Label.Size = New System.Drawing.Size(55, 13)
            Me.Question2Label.TabIndex = 25
            Me.Question2Label.Text = "Question2"
            '
            'Question2TextBox
            '
            Me.Question2TextBox.Location = New System.Drawing.Point(147, 127)
            Me.Question2TextBox.Name = "Question2TextBox"
            Me.Question2TextBox.Size = New System.Drawing.Size(100, 20)
            Me.Question2TextBox.TabIndex = 26
            '
            'Question20Label
            '
            Me.Question20Label.AutoSize = True
            Me.Question20Label.Location = New System.Drawing.Point(56, 723)
            Me.Question20Label.Name = "Question20Label"
            Me.Question20Label.Size = New System.Drawing.Size(61, 13)
            Me.Question20Label.TabIndex = 27
            Me.Question20Label.Text = "Question20"
            '
            'Question20TextBox
            '
            Me.Question20TextBox.Location = New System.Drawing.Point(147, 723)
            Me.Question20TextBox.Name = "Question20TextBox"
            Me.Question20TextBox.Size = New System.Drawing.Size(100, 20)
            Me.Question20TextBox.TabIndex = 28
            '
            'Question21Label
            '
            Me.Question21Label.AutoSize = True
            Me.Question21Label.Location = New System.Drawing.Point(56, 757)
            Me.Question21Label.Name = "Question21Label"
            Me.Question21Label.Size = New System.Drawing.Size(61, 13)
            Me.Question21Label.TabIndex = 29
            Me.Question21Label.Text = "Question21"
            '
            'Question21TextBox
            '
            Me.Question21TextBox.Location = New System.Drawing.Point(147, 757)
            Me.Question21TextBox.Name = "Question21TextBox"
            Me.Question21TextBox.Size = New System.Drawing.Size(100, 20)
            Me.Question21TextBox.TabIndex = 30
            '
            'Question22Label
            '
            Me.Question22Label.AutoSize = True
            Me.Question22Label.Location = New System.Drawing.Point(56, 791)
            Me.Question22Label.Name = "Question22Label"
            Me.Question22Label.Size = New System.Drawing.Size(61, 13)
            Me.Question22Label.TabIndex = 31
            Me.Question22Label.Text = "Question22"
            '
            'Question22TextBox
            '
            Me.Question22TextBox.Location = New System.Drawing.Point(147, 791)
            Me.Question22TextBox.Name = "Question22TextBox"
            Me.Question22TextBox.Size = New System.Drawing.Size(100, 20)
            Me.Question22TextBox.TabIndex = 32
            '
            'Question23Label
            '
            Me.Question23Label.AutoSize = True
            Me.Question23Label.Location = New System.Drawing.Point(56, 825)
            Me.Question23Label.Name = "Question23Label"
            Me.Question23Label.Size = New System.Drawing.Size(61, 13)
            Me.Question23Label.TabIndex = 33
            Me.Question23Label.Text = "Question23"
            '
            'Question23TextBox
            '
            Me.Question23TextBox.Location = New System.Drawing.Point(147, 825)
            Me.Question23TextBox.Name = "Question23TextBox"
            Me.Question23TextBox.Size = New System.Drawing.Size(100, 20)
            Me.Question23TextBox.TabIndex = 34
            '
            'Question24Label
            '
            Me.Question24Label.AutoSize = True
            Me.Question24Label.Location = New System.Drawing.Point(56, 859)
            Me.Question24Label.Name = "Question24Label"
            Me.Question24Label.Size = New System.Drawing.Size(61, 13)
            Me.Question24Label.TabIndex = 35
            Me.Question24Label.Text = "Question24"
            '
            'Question24TextBox
            '
            Me.Question24TextBox.Location = New System.Drawing.Point(147, 859)
            Me.Question24TextBox.Name = "Question24TextBox"
            Me.Question24TextBox.Size = New System.Drawing.Size(100, 20)
            Me.Question24TextBox.TabIndex = 36
            '
            'Question25Label
            '
            Me.Question25Label.AutoSize = True
            Me.Question25Label.Location = New System.Drawing.Point(56, 893)
            Me.Question25Label.Name = "Question25Label"
            Me.Question25Label.Size = New System.Drawing.Size(61, 13)
            Me.Question25Label.TabIndex = 37
            Me.Question25Label.Text = "Question25"
            '
            'Question25TextBox
            '
            Me.Question25TextBox.Location = New System.Drawing.Point(147, 893)
            Me.Question25TextBox.Name = "Question25TextBox"
            Me.Question25TextBox.Size = New System.Drawing.Size(100, 20)
            Me.Question25TextBox.TabIndex = 38
            '
            'Question26Label
            '
            Me.Question26Label.AutoSize = True
            Me.Question26Label.Location = New System.Drawing.Point(363, 96)
            Me.Question26Label.Name = "Question26Label"
            Me.Question26Label.Size = New System.Drawing.Size(61, 13)
            Me.Question26Label.TabIndex = 39
            Me.Question26Label.Text = "Question26"
            '
            'Question26TextBox
            '
            Me.Question26TextBox.Location = New System.Drawing.Point(454, 96)
            Me.Question26TextBox.Name = "Question26TextBox"
            Me.Question26TextBox.Size = New System.Drawing.Size(100, 20)
            Me.Question26TextBox.TabIndex = 40
            '
            'Question27Label
            '
            Me.Question27Label.AutoSize = True
            Me.Question27Label.Location = New System.Drawing.Point(363, 130)
            Me.Question27Label.Name = "Question27Label"
            Me.Question27Label.Size = New System.Drawing.Size(61, 13)
            Me.Question27Label.TabIndex = 41
            Me.Question27Label.Text = "Question27"
            '
            'Question27TextBox
            '
            Me.Question27TextBox.Location = New System.Drawing.Point(454, 127)
            Me.Question27TextBox.Name = "Question27TextBox"
            Me.Question27TextBox.Size = New System.Drawing.Size(100, 20)
            Me.Question27TextBox.TabIndex = 42
            '
            'Question28Label
            '
            Me.Question28Label.AutoSize = True
            Me.Question28Label.Location = New System.Drawing.Point(363, 161)
            Me.Question28Label.Name = "Question28Label"
            Me.Question28Label.Size = New System.Drawing.Size(61, 13)
            Me.Question28Label.TabIndex = 43
            Me.Question28Label.Text = "Question28"
            '
            'Question28TextBox
            '
            Me.Question28TextBox.Location = New System.Drawing.Point(454, 158)
            Me.Question28TextBox.Name = "Question28TextBox"
            Me.Question28TextBox.Size = New System.Drawing.Size(100, 20)
            Me.Question28TextBox.TabIndex = 44
            '
            'Question29Label
            '
            Me.Question29Label.AutoSize = True
            Me.Question29Label.Location = New System.Drawing.Point(363, 195)
            Me.Question29Label.Name = "Question29Label"
            Me.Question29Label.Size = New System.Drawing.Size(61, 13)
            Me.Question29Label.TabIndex = 45
            Me.Question29Label.Text = "Question29"
            '
            'Question29TextBox
            '
            Me.Question29TextBox.Location = New System.Drawing.Point(454, 192)
            Me.Question29TextBox.Name = "Question29TextBox"
            Me.Question29TextBox.Size = New System.Drawing.Size(100, 20)
            Me.Question29TextBox.TabIndex = 46
            '
            'Question3Label
            '
            Me.Question3Label.AutoSize = True
            Me.Question3Label.Location = New System.Drawing.Point(56, 161)
            Me.Question3Label.Name = "Question3Label"
            Me.Question3Label.Size = New System.Drawing.Size(55, 13)
            Me.Question3Label.TabIndex = 47
            Me.Question3Label.Text = "Question3"
            '
            'Question3TextBox
            '
            Me.Question3TextBox.Location = New System.Drawing.Point(147, 161)
            Me.Question3TextBox.Name = "Question3TextBox"
            Me.Question3TextBox.Size = New System.Drawing.Size(100, 20)
            Me.Question3TextBox.TabIndex = 48
            '
            'Question30Label
            '
            Me.Question30Label.AutoSize = True
            Me.Question30Label.Location = New System.Drawing.Point(363, 229)
            Me.Question30Label.Name = "Question30Label"
            Me.Question30Label.Size = New System.Drawing.Size(61, 13)
            Me.Question30Label.TabIndex = 49
            Me.Question30Label.Text = "Question30"
            '
            'Question30TextBox
            '
            Me.Question30TextBox.Location = New System.Drawing.Point(454, 229)
            Me.Question30TextBox.Name = "Question30TextBox"
            Me.Question30TextBox.Size = New System.Drawing.Size(100, 20)
            Me.Question30TextBox.TabIndex = 50
            '
            'Question31Label
            '
            Me.Question31Label.AutoSize = True
            Me.Question31Label.Location = New System.Drawing.Point(363, 259)
            Me.Question31Label.Name = "Question31Label"
            Me.Question31Label.Size = New System.Drawing.Size(61, 13)
            Me.Question31Label.TabIndex = 51
            Me.Question31Label.Text = "Question31"
            '
            'Question31TextBox
            '
            Me.Question31TextBox.Location = New System.Drawing.Point(454, 259)
            Me.Question31TextBox.Name = "Question31TextBox"
            Me.Question31TextBox.Size = New System.Drawing.Size(100, 20)
            Me.Question31TextBox.TabIndex = 52
            '
            'Question32Label
            '
            Me.Question32Label.AutoSize = True
            Me.Question32Label.Location = New System.Drawing.Point(363, 290)
            Me.Question32Label.Name = "Question32Label"
            Me.Question32Label.Size = New System.Drawing.Size(61, 13)
            Me.Question32Label.TabIndex = 53
            Me.Question32Label.Text = "Question32"
            '
            'Question32TextBox
            '
            Me.Question32TextBox.Location = New System.Drawing.Point(454, 287)
            Me.Question32TextBox.Name = "Question32TextBox"
            Me.Question32TextBox.Size = New System.Drawing.Size(100, 20)
            Me.Question32TextBox.TabIndex = 54
            '
            'Question33Label
            '
            Me.Question33Label.AutoSize = True
            Me.Question33Label.Location = New System.Drawing.Point(365, 319)
            Me.Question33Label.Name = "Question33Label"
            Me.Question33Label.Size = New System.Drawing.Size(61, 13)
            Me.Question33Label.TabIndex = 55
            Me.Question33Label.Text = "Question33"
            '
            'Question33TextBox
            '
            Me.Question33TextBox.Location = New System.Drawing.Point(454, 316)
            Me.Question33TextBox.Name = "Question33TextBox"
            Me.Question33TextBox.Size = New System.Drawing.Size(100, 20)
            Me.Question33TextBox.TabIndex = 56
            '
            'Question34Label
            '
            Me.Question34Label.AutoSize = True
            Me.Question34Label.Location = New System.Drawing.Point(363, 353)
            Me.Question34Label.Name = "Question34Label"
            Me.Question34Label.Size = New System.Drawing.Size(61, 13)
            Me.Question34Label.TabIndex = 57
            Me.Question34Label.Text = "Question34"
            '
            'Question34TextBox
            '
            Me.Question34TextBox.Location = New System.Drawing.Point(454, 350)
            Me.Question34TextBox.Name = "Question34TextBox"
            Me.Question34TextBox.Size = New System.Drawing.Size(100, 20)
            Me.Question34TextBox.TabIndex = 58
            '
            'Question35Label
            '
            Me.Question35Label.AutoSize = True
            Me.Question35Label.Location = New System.Drawing.Point(363, 390)
            Me.Question35Label.Name = "Question35Label"
            Me.Question35Label.Size = New System.Drawing.Size(61, 13)
            Me.Question35Label.TabIndex = 59
            Me.Question35Label.Text = "Question35"
            '
            'Question35TextBox
            '
            Me.Question35TextBox.Location = New System.Drawing.Point(454, 387)
            Me.Question35TextBox.Name = "Question35TextBox"
            Me.Question35TextBox.Size = New System.Drawing.Size(100, 20)
            Me.Question35TextBox.TabIndex = 60
            '
            'Question36Label
            '
            Me.Question36Label.AutoSize = True
            Me.Question36Label.Location = New System.Drawing.Point(363, 424)
            Me.Question36Label.Name = "Question36Label"
            Me.Question36Label.Size = New System.Drawing.Size(61, 13)
            Me.Question36Label.TabIndex = 61
            Me.Question36Label.Text = "Question36"
            '
            'Question36TextBox
            '
            Me.Question36TextBox.Location = New System.Drawing.Point(454, 421)
            Me.Question36TextBox.Name = "Question36TextBox"
            Me.Question36TextBox.Size = New System.Drawing.Size(100, 20)
            Me.Question36TextBox.TabIndex = 62
            '
            'Question37Label
            '
            Me.Question37Label.AutoSize = True
            Me.Question37Label.Location = New System.Drawing.Point(363, 454)
            Me.Question37Label.Name = "Question37Label"
            Me.Question37Label.Size = New System.Drawing.Size(61, 13)
            Me.Question37Label.TabIndex = 63
            Me.Question37Label.Text = "Question37"
            '
            'Question37TextBox
            '
            Me.Question37TextBox.Location = New System.Drawing.Point(454, 451)
            Me.Question37TextBox.Name = "Question37TextBox"
            Me.Question37TextBox.Size = New System.Drawing.Size(100, 20)
            Me.Question37TextBox.TabIndex = 64
            '
            'Question38Label
            '
            Me.Question38Label.AutoSize = True
            Me.Question38Label.Location = New System.Drawing.Point(363, 485)
            Me.Question38Label.Name = "Question38Label"
            Me.Question38Label.Size = New System.Drawing.Size(61, 13)
            Me.Question38Label.TabIndex = 65
            Me.Question38Label.Text = "Question38"
            '
            'Question38TextBox
            '
            Me.Question38TextBox.Location = New System.Drawing.Point(454, 482)
            Me.Question38TextBox.Name = "Question38TextBox"
            Me.Question38TextBox.Size = New System.Drawing.Size(100, 20)
            Me.Question38TextBox.TabIndex = 66
            '
            'Question39Label
            '
            Me.Question39Label.AutoSize = True
            Me.Question39Label.Location = New System.Drawing.Point(363, 519)
            Me.Question39Label.Name = "Question39Label"
            Me.Question39Label.Size = New System.Drawing.Size(61, 13)
            Me.Question39Label.TabIndex = 67
            Me.Question39Label.Text = "Question39"
            '
            'Question39TextBox
            '
            Me.Question39TextBox.Location = New System.Drawing.Point(454, 519)
            Me.Question39TextBox.Name = "Question39TextBox"
            Me.Question39TextBox.Size = New System.Drawing.Size(100, 20)
            Me.Question39TextBox.TabIndex = 68
            '
            'Question4Label
            '
            Me.Question4Label.AutoSize = True
            Me.Question4Label.Location = New System.Drawing.Point(56, 195)
            Me.Question4Label.Name = "Question4Label"
            Me.Question4Label.Size = New System.Drawing.Size(55, 13)
            Me.Question4Label.TabIndex = 69
            Me.Question4Label.Text = "Question4"
            '
            'Question4TextBox
            '
            Me.Question4TextBox.Location = New System.Drawing.Point(147, 287)
            Me.Question4TextBox.Name = "Question4TextBox"
            Me.Question4TextBox.Size = New System.Drawing.Size(100, 20)
            Me.Question4TextBox.TabIndex = 70
            '
            'Question40Label
            '
            Me.Question40Label.AutoSize = True
            Me.Question40Label.Location = New System.Drawing.Point(363, 551)
            Me.Question40Label.Name = "Question40Label"
            Me.Question40Label.Size = New System.Drawing.Size(61, 13)
            Me.Question40Label.TabIndex = 71
            Me.Question40Label.Text = "Question40"
            '
            'Question40TextBox
            '
            Me.Question40TextBox.Location = New System.Drawing.Point(454, 548)
            Me.Question40TextBox.Name = "Question40TextBox"
            Me.Question40TextBox.Size = New System.Drawing.Size(100, 20)
            Me.Question40TextBox.TabIndex = 72
            '
            'Question41Label
            '
            Me.Question41Label.AutoSize = True
            Me.Question41Label.Location = New System.Drawing.Point(363, 582)
            Me.Question41Label.Name = "Question41Label"
            Me.Question41Label.Size = New System.Drawing.Size(61, 13)
            Me.Question41Label.TabIndex = 73
            Me.Question41Label.Text = "Question41"
            '
            'Question41TextBox
            '
            Me.Question41TextBox.Location = New System.Drawing.Point(454, 579)
            Me.Question41TextBox.Name = "Question41TextBox"
            Me.Question41TextBox.Size = New System.Drawing.Size(100, 20)
            Me.Question41TextBox.TabIndex = 74
            '
            'Question42Label
            '
            Me.Question42Label.AutoSize = True
            Me.Question42Label.Location = New System.Drawing.Point(363, 616)
            Me.Question42Label.Name = "Question42Label"
            Me.Question42Label.Size = New System.Drawing.Size(61, 13)
            Me.Question42Label.TabIndex = 75
            Me.Question42Label.Text = "Question42"
            '
            'Question42TextBox
            '
            Me.Question42TextBox.Location = New System.Drawing.Point(454, 613)
            Me.Question42TextBox.Name = "Question42TextBox"
            Me.Question42TextBox.Size = New System.Drawing.Size(100, 20)
            Me.Question42TextBox.TabIndex = 76
            '
            'Question43Label
            '
            Me.Question43Label.AutoSize = True
            Me.Question43Label.Location = New System.Drawing.Point(363, 650)
            Me.Question43Label.Name = "Question43Label"
            Me.Question43Label.Size = New System.Drawing.Size(61, 13)
            Me.Question43Label.TabIndex = 77
            Me.Question43Label.Text = "Question43"
            '
            'Question43TextBox
            '
            Me.Question43TextBox.Location = New System.Drawing.Point(454, 650)
            Me.Question43TextBox.Name = "Question43TextBox"
            Me.Question43TextBox.Size = New System.Drawing.Size(100, 20)
            Me.Question43TextBox.TabIndex = 78
            '
            'Question44Label
            '
            Me.Question44Label.AutoSize = True
            Me.Question44Label.Location = New System.Drawing.Point(363, 684)
            Me.Question44Label.Name = "Question44Label"
            Me.Question44Label.Size = New System.Drawing.Size(61, 13)
            Me.Question44Label.TabIndex = 79
            Me.Question44Label.Text = "Question44"
            '
            'Question44TextBox
            '
            Me.Question44TextBox.Location = New System.Drawing.Point(454, 684)
            Me.Question44TextBox.Name = "Question44TextBox"
            Me.Question44TextBox.Size = New System.Drawing.Size(100, 20)
            Me.Question44TextBox.TabIndex = 80
            '
            'Question45Label
            '
            Me.Question45Label.AutoSize = True
            Me.Question45Label.Location = New System.Drawing.Point(363, 723)
            Me.Question45Label.Name = "Question45Label"
            Me.Question45Label.Size = New System.Drawing.Size(61, 13)
            Me.Question45Label.TabIndex = 81
            Me.Question45Label.Text = "Question45"
            '
            'Question45TextBox
            '
            Me.Question45TextBox.Location = New System.Drawing.Point(454, 723)
            Me.Question45TextBox.Name = "Question45TextBox"
            Me.Question45TextBox.Size = New System.Drawing.Size(100, 20)
            Me.Question45TextBox.TabIndex = 82
            '
            'Question46Label
            '
            Me.Question46Label.AutoSize = True
            Me.Question46Label.Location = New System.Drawing.Point(364, 757)
            Me.Question46Label.Name = "Question46Label"
            Me.Question46Label.Size = New System.Drawing.Size(61, 13)
            Me.Question46Label.TabIndex = 83
            Me.Question46Label.Text = "Question46"
            '
            'Question46TextBox
            '
            Me.Question46TextBox.Location = New System.Drawing.Point(454, 757)
            Me.Question46TextBox.Name = "Question46TextBox"
            Me.Question46TextBox.Size = New System.Drawing.Size(100, 20)
            Me.Question46TextBox.TabIndex = 84
            '
            'Question47Label
            '
            Me.Question47Label.AutoSize = True
            Me.Question47Label.Location = New System.Drawing.Point(363, 791)
            Me.Question47Label.Name = "Question47Label"
            Me.Question47Label.Size = New System.Drawing.Size(61, 13)
            Me.Question47Label.TabIndex = 85
            Me.Question47Label.Text = "Question47"
            '
            'Question47TextBox
            '
            Me.Question47TextBox.Location = New System.Drawing.Point(454, 791)
            Me.Question47TextBox.Name = "Question47TextBox"
            Me.Question47TextBox.Size = New System.Drawing.Size(100, 20)
            Me.Question47TextBox.TabIndex = 86
            '
            'Question48Label
            '
            Me.Question48Label.AutoSize = True
            Me.Question48Label.Location = New System.Drawing.Point(364, 825)
            Me.Question48Label.Name = "Question48Label"
            Me.Question48Label.Size = New System.Drawing.Size(61, 13)
            Me.Question48Label.TabIndex = 87
            Me.Question48Label.Text = "Question48"
            '
            'Question48TextBox
            '
            Me.Question48TextBox.Location = New System.Drawing.Point(454, 825)
            Me.Question48TextBox.Name = "Question48TextBox"
            Me.Question48TextBox.Size = New System.Drawing.Size(100, 20)
            Me.Question48TextBox.TabIndex = 88
            '
            'Question49Label
            '
            Me.Question49Label.AutoSize = True
            Me.Question49Label.Location = New System.Drawing.Point(363, 862)
            Me.Question49Label.Name = "Question49Label"
            Me.Question49Label.Size = New System.Drawing.Size(61, 13)
            Me.Question49Label.TabIndex = 89
            Me.Question49Label.Text = "Question49"
            '
            'Question49TextBox
            '
            Me.Question49TextBox.Location = New System.Drawing.Point(454, 856)
            Me.Question49TextBox.Name = "Question49TextBox"
            Me.Question49TextBox.Size = New System.Drawing.Size(100, 20)
            Me.Question49TextBox.TabIndex = 90
            '
            'Question5Label
            '
            Me.Question5Label.AutoSize = True
            Me.Question5Label.Location = New System.Drawing.Point(56, 229)
            Me.Question5Label.Name = "Question5Label"
            Me.Question5Label.Size = New System.Drawing.Size(55, 13)
            Me.Question5Label.TabIndex = 91
            Me.Question5Label.Text = "Question5"
            '
            'Question5TextBox
            '
            Me.Question5TextBox.Location = New System.Drawing.Point(147, 196)
            Me.Question5TextBox.Name = "Question5TextBox"
            Me.Question5TextBox.Size = New System.Drawing.Size(100, 20)
            Me.Question5TextBox.TabIndex = 92
            '
            'Question50Label
            '
            Me.Question50Label.AutoSize = True
            Me.Question50Label.Location = New System.Drawing.Point(363, 893)
            Me.Question50Label.Name = "Question50Label"
            Me.Question50Label.Size = New System.Drawing.Size(61, 13)
            Me.Question50Label.TabIndex = 93
            Me.Question50Label.Text = "Question50"
            '
            'Question50TextBox
            '
            Me.Question50TextBox.Location = New System.Drawing.Point(454, 893)
            Me.Question50TextBox.Name = "Question50TextBox"
            Me.Question50TextBox.Size = New System.Drawing.Size(100, 20)
            Me.Question50TextBox.TabIndex = 94
            '
            'Question6Label
            '
            Me.Question6Label.AutoSize = True
            Me.Question6Label.Location = New System.Drawing.Point(56, 259)
            Me.Question6Label.Name = "Question6Label"
            Me.Question6Label.Size = New System.Drawing.Size(55, 13)
            Me.Question6Label.TabIndex = 95
            Me.Question6Label.Text = "Question6"
            '
            'Question6TextBox
            '
            Me.Question6TextBox.Location = New System.Drawing.Point(147, 346)
            Me.Question6TextBox.Name = "Question6TextBox"
            Me.Question6TextBox.Size = New System.Drawing.Size(100, 20)
            Me.Question6TextBox.TabIndex = 96
            '
            'Question7Label
            '
            Me.Question7Label.AutoSize = True
            Me.Question7Label.Location = New System.Drawing.Point(56, 290)
            Me.Question7Label.Name = "Question7Label"
            Me.Question7Label.Size = New System.Drawing.Size(55, 13)
            Me.Question7Label.TabIndex = 97
            Me.Question7Label.Text = "Question7"
            '
            'Question7TextBox
            '
            Me.Question7TextBox.Location = New System.Drawing.Point(147, 229)
            Me.Question7TextBox.Name = "Question7TextBox"
            Me.Question7TextBox.Size = New System.Drawing.Size(100, 20)
            Me.Question7TextBox.TabIndex = 98
            '
            'Question8Label
            '
            Me.Question8Label.AutoSize = True
            Me.Question8Label.Location = New System.Drawing.Point(56, 319)
            Me.Question8Label.Name = "Question8Label"
            Me.Question8Label.Size = New System.Drawing.Size(55, 13)
            Me.Question8Label.TabIndex = 99
            Me.Question8Label.Text = "Question8"
            '
            'Question8TextBox
            '
            Me.Question8TextBox.Location = New System.Drawing.Point(147, 259)
            Me.Question8TextBox.Name = "Question8TextBox"
            Me.Question8TextBox.Size = New System.Drawing.Size(100, 20)
            Me.Question8TextBox.TabIndex = 100
            '
            'Question9Label
            '
            Me.Question9Label.AutoSize = True
            Me.Question9Label.Location = New System.Drawing.Point(56, 353)
            Me.Question9Label.Name = "Question9Label"
            Me.Question9Label.Size = New System.Drawing.Size(55, 13)
            Me.Question9Label.TabIndex = 101
            Me.Question9Label.Text = "Question9"
            '
            'Question9TextBox
            '
            Me.Question9TextBox.Location = New System.Drawing.Point(147, 316)
            Me.Question9TextBox.Name = "Question9TextBox"
            Me.Question9TextBox.Size = New System.Drawing.Size(100, 20)
            Me.Question9TextBox.TabIndex = 102
            '
            'QuestionFileLabel
            '
            Me.QuestionFileLabel.AutoSize = True
            Me.QuestionFileLabel.Location = New System.Drawing.Point(590, 202)
            Me.QuestionFileLabel.Name = "QuestionFileLabel"
            Me.QuestionFileLabel.Size = New System.Drawing.Size(68, 13)
            Me.QuestionFileLabel.TabIndex = 103
            Me.QuestionFileLabel.Text = "Question File"
            '
            'QuestionFileTextBox
            '
            Me.QuestionFileTextBox.Location = New System.Drawing.Point(690, 195)
            Me.QuestionFileTextBox.Name = "QuestionFileTextBox"
            Me.QuestionFileTextBox.Size = New System.Drawing.Size(100, 20)
            Me.QuestionFileTextBox.TabIndex = 104
            '
            'QuestionNum1Label
            '
            Me.QuestionNum1Label.AutoSize = True
            Me.QuestionNum1Label.Location = New System.Drawing.Point(578, 229)
            Me.QuestionNum1Label.Name = "QuestionNum1Label"
            Me.QuestionNum1Label.Size = New System.Drawing.Size(80, 13)
            Me.QuestionNum1Label.TabIndex = 105
            Me.QuestionNum1Label.Text = "Question Num1"
            '
            'QuestionNum1TextBox
            '
            Me.QuestionNum1TextBox.Location = New System.Drawing.Point(690, 229)
            Me.QuestionNum1TextBox.Name = "QuestionNum1TextBox"
            Me.QuestionNum1TextBox.Size = New System.Drawing.Size(100, 20)
            Me.QuestionNum1TextBox.TabIndex = 106
            '
            'QuestionNum2Label
            '
            Me.QuestionNum2Label.AutoSize = True
            Me.QuestionNum2Label.Location = New System.Drawing.Point(578, 263)
            Me.QuestionNum2Label.Name = "QuestionNum2Label"
            Me.QuestionNum2Label.Size = New System.Drawing.Size(80, 13)
            Me.QuestionNum2Label.TabIndex = 107
            Me.QuestionNum2Label.Text = "Question Num2"
            '
            'QuestionNum2TextBox
            '
            Me.QuestionNum2TextBox.Location = New System.Drawing.Point(690, 263)
            Me.QuestionNum2TextBox.Name = "QuestionNum2TextBox"
            Me.QuestionNum2TextBox.Size = New System.Drawing.Size(100, 20)
            Me.QuestionNum2TextBox.TabIndex = 108
            '
            'QuestionNum3Label
            '
            Me.QuestionNum3Label.AutoSize = True
            Me.QuestionNum3Label.Location = New System.Drawing.Point(578, 297)
            Me.QuestionNum3Label.Name = "QuestionNum3Label"
            Me.QuestionNum3Label.Size = New System.Drawing.Size(80, 13)
            Me.QuestionNum3Label.TabIndex = 109
            Me.QuestionNum3Label.Text = "Question Num3"
            '
            'QuestionNum3TextBox
            '
            Me.QuestionNum3TextBox.Location = New System.Drawing.Point(690, 297)
            Me.QuestionNum3TextBox.Name = "QuestionNum3TextBox"
            Me.QuestionNum3TextBox.Size = New System.Drawing.Size(100, 20)
            Me.QuestionNum3TextBox.TabIndex = 110
            '
            'QuestionNum4Label
            '
            Me.QuestionNum4Label.AutoSize = True
            Me.QuestionNum4Label.Location = New System.Drawing.Point(578, 331)
            Me.QuestionNum4Label.Name = "QuestionNum4Label"
            Me.QuestionNum4Label.Size = New System.Drawing.Size(80, 13)
            Me.QuestionNum4Label.TabIndex = 111
            Me.QuestionNum4Label.Text = "Question Num4"
            '
            'QuestionNum4TextBox
            '
            Me.QuestionNum4TextBox.Location = New System.Drawing.Point(690, 331)
            Me.QuestionNum4TextBox.Name = "QuestionNum4TextBox"
            Me.QuestionNum4TextBox.Size = New System.Drawing.Size(100, 20)
            Me.QuestionNum4TextBox.TabIndex = 112
            '
            'QuestionNum5Label
            '
            Me.QuestionNum5Label.AutoSize = True
            Me.QuestionNum5Label.Location = New System.Drawing.Point(578, 365)
            Me.QuestionNum5Label.Name = "QuestionNum5Label"
            Me.QuestionNum5Label.Size = New System.Drawing.Size(80, 13)
            Me.QuestionNum5Label.TabIndex = 113
            Me.QuestionNum5Label.Text = "Question Num5"
            '
            'QuestionNum5TextBox
            '
            Me.QuestionNum5TextBox.Location = New System.Drawing.Point(690, 365)
            Me.QuestionNum5TextBox.Name = "QuestionNum5TextBox"
            Me.QuestionNum5TextBox.Size = New System.Drawing.Size(100, 20)
            Me.QuestionNum5TextBox.TabIndex = 114
            '
            'SurveyIDLabel
            '
            Me.SurveyIDLabel.AutoSize = True
            Me.SurveyIDLabel.Location = New System.Drawing.Point(599, 133)
            Me.SurveyIDLabel.Name = "SurveyIDLabel"
            Me.SurveyIDLabel.Size = New System.Drawing.Size(51, 13)
            Me.SurveyIDLabel.TabIndex = 115
            Me.SurveyIDLabel.Text = "SurveyID"
            '
            'SurveyIDTextBox
            '
            Me.SurveyIDTextBox.Location = New System.Drawing.Point(690, 133)
            Me.SurveyIDTextBox.Name = "SurveyIDTextBox"
            Me.SurveyIDTextBox.Size = New System.Drawing.Size(100, 20)
            Me.SurveyIDTextBox.TabIndex = 116
            '
            'SurveyNameLabel
            '
            Me.SurveyNameLabel.AutoSize = True
            Me.SurveyNameLabel.Location = New System.Drawing.Point(586, 167)
            Me.SurveyNameLabel.Name = "SurveyNameLabel"
            Me.SurveyNameLabel.Size = New System.Drawing.Size(71, 13)
            Me.SurveyNameLabel.TabIndex = 117
            Me.SurveyNameLabel.Text = "Survey Name"
            '
            'SurveyNameTextBox
            '
            Me.SurveyNameTextBox.Location = New System.Drawing.Point(690, 164)
            Me.SurveyNameTextBox.Name = "SurveyNameTextBox"
            Me.SurveyNameTextBox.Size = New System.Drawing.Size(100, 20)
            Me.SurveyNameTextBox.TabIndex = 118
            '
            'panel3
            '
            Me.panel3.Controls.Add(Me.Panel1)
            Me.panel3.Controls.Add(Me.panel4)
            Me.panel3.Controls.Add(Me.panel5)
            Me.panel3.Controls.Add(Me.panel6)
            Me.panel3.Dock = System.Windows.Forms.DockStyle.Fill
            Me.panel3.Location = New System.Drawing.Point(0, 27)
            Me.panel3.Name = "panel3"
            Me.panel3.Size = New System.Drawing.Size(842, 582)
            Me.panel3.TabIndex = 19
            '
            'panel4
            '
            Me.panel4.Dock = System.Windows.Forms.DockStyle.Right
            Me.panel4.Location = New System.Drawing.Point(832, 0)
            Me.panel4.Name = "panel4"
            Me.panel4.Size = New System.Drawing.Size(10, 572)
            Me.panel4.TabIndex = 3
            '
            'panel5
            '
            Me.panel5.Dock = System.Windows.Forms.DockStyle.Left
            Me.panel5.Location = New System.Drawing.Point(0, 0)
            Me.panel5.Name = "panel5"
            Me.panel5.Size = New System.Drawing.Size(10, 572)
            Me.panel5.TabIndex = 5
            '
            'panel6
            '
            Me.panel6.Dock = System.Windows.Forms.DockStyle.Bottom
            Me.panel6.Location = New System.Drawing.Point(0, 572)
            Me.panel6.Name = "panel6"
            Me.panel6.Size = New System.Drawing.Size(842, 10)
            Me.panel6.TabIndex = 6
            '
            'Label1
            '
            Me.Label1.AutoSize = True
            Me.Label1.ForeColor = System.Drawing.SystemColors.Control
            Me.Label1.Location = New System.Drawing.Point(68, 50)
            Me.Label1.Name = "Label1"
            Me.Label1.Size = New System.Drawing.Size(77, 13)
            Me.Label1.TabIndex = 120
            Me.Label1.Text = "Survey Creator"
            '
            'frmsurvey
            '
            Me.AutoScaleDimensions = New System.Drawing.SizeF(6.0!, 13.0!)
            Me.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font
            Me.ClientSize = New System.Drawing.Size(842, 609)
            Me.Controls.Add(Me.panel3)
            Me.Controls.Add(Me.BindingNavigator1)
            Me.Name = "frmsurvey"
            Me.Text = "Survey"
            CType(Me.BindingNavigator1, System.ComponentModel.ISupportInitialize).EndInit()
            Me.BindingNavigator1.ResumeLayout(False)
            Me.BindingNavigator1.PerformLayout()
            CType(Me.surveyBindingSource, System.ComponentModel.ISupportInitialize).EndInit()
            CType(Me.ErrorProvider1, System.ComponentModel.ISupportInitialize).EndInit()
            Me.Panel1.ResumeLayout(False)
            Me.Panel1.PerformLayout()
            CType(Me.PictureBox1, System.ComponentModel.ISupportInitialize).EndInit()
            Me.panel3.ResumeLayout(False)
            Me.panel3.PerformLayout()
            Me.ResumeLayout(False)
            Me.PerformLayout()

        End Sub
        Friend WithEvents BindingNavigator1 As System.Windows.Forms.BindingNavigator
		Friend WithEvents BindingNavigatorAddNewItem As System.Windows.Forms.ToolStripButton
		Friend WithEvents BindingNavigatorCountItem As System.Windows.Forms.ToolStripLabel
		Friend WithEvents BindingNavigatorDeleteItem As System.Windows.Forms.ToolStripButton
		Friend WithEvents BindingNavigatorMoveFirstItem As System.Windows.Forms.ToolStripButton
		Friend WithEvents BindingNavigatorMovePreviousItem As System.Windows.Forms.ToolStripButton
		Friend WithEvents BindingNavigatorSeparator As System.Windows.Forms.ToolStripSeparator
		Friend WithEvents BindingNavigatorPositionItem As System.Windows.Forms.ToolStripTextBox
		Friend WithEvents BindingNavigatorSeparator1 As System.Windows.Forms.ToolStripSeparator
		Friend WithEvents BindingNavigatorMoveNextItem As System.Windows.Forms.ToolStripButton
		Friend WithEvents BindingNavigatorMoveLastItem As System.Windows.Forms.ToolStripButton
		Friend WithEvents BindingNavigatorSeparator2 As System.Windows.Forms.ToolStripSeparator
		Friend WithEvents ToolStripButton1 As System.Windows.Forms.ToolStripButton
		Friend WithEvents ErrorProvider1 As System.Windows.Forms.ErrorProvider
		Friend WithEvents Panel1 As System.Windows.Forms.Panel
		Friend WithEvents surveyBindingSource As System.Windows.Forms.BindingSource
		Friend WithEvents NotesTextBox As System.Windows.Forms.TextBox
		Friend WithEvents NotesLabel As System.Windows.Forms.Label
		Friend WithEvents Question1TextBox As System.Windows.Forms.TextBox
		Friend WithEvents Question1Label As System.Windows.Forms.Label
		Friend WithEvents Question10TextBox As System.Windows.Forms.TextBox
		Friend WithEvents Question10Label As System.Windows.Forms.Label
		Friend WithEvents Question11TextBox As System.Windows.Forms.TextBox
		Friend WithEvents Question11Label As System.Windows.Forms.Label
		Friend WithEvents Question12TextBox As System.Windows.Forms.TextBox
		Friend WithEvents Question12Label As System.Windows.Forms.Label
		Friend WithEvents Question13TextBox As System.Windows.Forms.TextBox
		Friend WithEvents Question13Label As System.Windows.Forms.Label
		Friend WithEvents Question14TextBox As System.Windows.Forms.TextBox
		Friend WithEvents Question14Label As System.Windows.Forms.Label
		Friend WithEvents Question15TextBox As System.Windows.Forms.TextBox
		Friend WithEvents Question15Label As System.Windows.Forms.Label
		Friend WithEvents Question16TextBox As System.Windows.Forms.TextBox
		Friend WithEvents Question16Label As System.Windows.Forms.Label
		Friend WithEvents Question17TextBox As System.Windows.Forms.TextBox
		Friend WithEvents Question17Label As System.Windows.Forms.Label
		Friend WithEvents Question18TextBox As System.Windows.Forms.TextBox
		Friend WithEvents Question18Label As System.Windows.Forms.Label
		Friend WithEvents Question19TextBox As System.Windows.Forms.TextBox
		Friend WithEvents Question19Label As System.Windows.Forms.Label
		Friend WithEvents Question2TextBox As System.Windows.Forms.TextBox
		Friend WithEvents Question2Label As System.Windows.Forms.Label
		Friend WithEvents Question20TextBox As System.Windows.Forms.TextBox
		Friend WithEvents Question20Label As System.Windows.Forms.Label
		Friend WithEvents Question21TextBox As System.Windows.Forms.TextBox
		Friend WithEvents Question21Label As System.Windows.Forms.Label
		Friend WithEvents Question22TextBox As System.Windows.Forms.TextBox
		Friend WithEvents Question22Label As System.Windows.Forms.Label
		Friend WithEvents Question23TextBox As System.Windows.Forms.TextBox
		Friend WithEvents Question23Label As System.Windows.Forms.Label
		Friend WithEvents Question24TextBox As System.Windows.Forms.TextBox
		Friend WithEvents Question24Label As System.Windows.Forms.Label
		Friend WithEvents Question25TextBox As System.Windows.Forms.TextBox
		Friend WithEvents Question25Label As System.Windows.Forms.Label
		Friend WithEvents Question26TextBox As System.Windows.Forms.TextBox
		Friend WithEvents Question26Label As System.Windows.Forms.Label
		Friend WithEvents Question27TextBox As System.Windows.Forms.TextBox
		Friend WithEvents Question27Label As System.Windows.Forms.Label
		Friend WithEvents Question28TextBox As System.Windows.Forms.TextBox
		Friend WithEvents Question28Label As System.Windows.Forms.Label
		Friend WithEvents Question29TextBox As System.Windows.Forms.TextBox
		Friend WithEvents Question29Label As System.Windows.Forms.Label
		Friend WithEvents Question3TextBox As System.Windows.Forms.TextBox
		Friend WithEvents Question3Label As System.Windows.Forms.Label
		Friend WithEvents Question30TextBox As System.Windows.Forms.TextBox
		Friend WithEvents Question30Label As System.Windows.Forms.Label
		Friend WithEvents Question31TextBox As System.Windows.Forms.TextBox
		Friend WithEvents Question31Label As System.Windows.Forms.Label
		Friend WithEvents Question32TextBox As System.Windows.Forms.TextBox
		Friend WithEvents Question32Label As System.Windows.Forms.Label
		Friend WithEvents Question33TextBox As System.Windows.Forms.TextBox
		Friend WithEvents Question33Label As System.Windows.Forms.Label
		Friend WithEvents Question34TextBox As System.Windows.Forms.TextBox
		Friend WithEvents Question34Label As System.Windows.Forms.Label
		Friend WithEvents Question35TextBox As System.Windows.Forms.TextBox
		Friend WithEvents Question35Label As System.Windows.Forms.Label
		Friend WithEvents Question36TextBox As System.Windows.Forms.TextBox
		Friend WithEvents Question36Label As System.Windows.Forms.Label
		Friend WithEvents Question37TextBox As System.Windows.Forms.TextBox
		Friend WithEvents Question37Label As System.Windows.Forms.Label
		Friend WithEvents Question38TextBox As System.Windows.Forms.TextBox
		Friend WithEvents Question38Label As System.Windows.Forms.Label
		Friend WithEvents Question39TextBox As System.Windows.Forms.TextBox
		Friend WithEvents Question39Label As System.Windows.Forms.Label
		Friend WithEvents Question4TextBox As System.Windows.Forms.TextBox
		Friend WithEvents Question4Label As System.Windows.Forms.Label
		Friend WithEvents Question40TextBox As System.Windows.Forms.TextBox
		Friend WithEvents Question40Label As System.Windows.Forms.Label
		Friend WithEvents Question41TextBox As System.Windows.Forms.TextBox
		Friend WithEvents Question41Label As System.Windows.Forms.Label
		Friend WithEvents Question42TextBox As System.Windows.Forms.TextBox
		Friend WithEvents Question42Label As System.Windows.Forms.Label
		Friend WithEvents Question43TextBox As System.Windows.Forms.TextBox
		Friend WithEvents Question43Label As System.Windows.Forms.Label
		Friend WithEvents Question44TextBox As System.Windows.Forms.TextBox
		Friend WithEvents Question44Label As System.Windows.Forms.Label
		Friend WithEvents Question45TextBox As System.Windows.Forms.TextBox
		Friend WithEvents Question45Label As System.Windows.Forms.Label
		Friend WithEvents Question46TextBox As System.Windows.Forms.TextBox
		Friend WithEvents Question46Label As System.Windows.Forms.Label
		Friend WithEvents Question47TextBox As System.Windows.Forms.TextBox
		Friend WithEvents Question47Label As System.Windows.Forms.Label
		Friend WithEvents Question48TextBox As System.Windows.Forms.TextBox
		Friend WithEvents Question48Label As System.Windows.Forms.Label
		Friend WithEvents Question49TextBox As System.Windows.Forms.TextBox
		Friend WithEvents Question49Label As System.Windows.Forms.Label
		Friend WithEvents Question5TextBox As System.Windows.Forms.TextBox
		Friend WithEvents Question5Label As System.Windows.Forms.Label
		Friend WithEvents Question50TextBox As System.Windows.Forms.TextBox
		Friend WithEvents Question50Label As System.Windows.Forms.Label
		Friend WithEvents Question6TextBox As System.Windows.Forms.TextBox
		Friend WithEvents Question6Label As System.Windows.Forms.Label
		Friend WithEvents Question7TextBox As System.Windows.Forms.TextBox
		Friend WithEvents Question7Label As System.Windows.Forms.Label
		Friend WithEvents Question8TextBox As System.Windows.Forms.TextBox
		Friend WithEvents Question8Label As System.Windows.Forms.Label
		Friend WithEvents Question9TextBox As System.Windows.Forms.TextBox
		Friend WithEvents Question9Label As System.Windows.Forms.Label
		Friend WithEvents QuestionFileTextBox As System.Windows.Forms.TextBox
		Friend WithEvents QuestionFileLabel As System.Windows.Forms.Label
		Friend WithEvents QuestionNum1TextBox As System.Windows.Forms.TextBox
		Friend WithEvents QuestionNum1Label As System.Windows.Forms.Label
		Friend WithEvents QuestionNum2TextBox As System.Windows.Forms.TextBox
		Friend WithEvents QuestionNum2Label As System.Windows.Forms.Label
		Friend WithEvents QuestionNum3TextBox As System.Windows.Forms.TextBox
		Friend WithEvents QuestionNum3Label As System.Windows.Forms.Label
		Friend WithEvents QuestionNum4TextBox As System.Windows.Forms.TextBox
		Friend WithEvents QuestionNum4Label As System.Windows.Forms.Label
		Friend WithEvents QuestionNum5TextBox As System.Windows.Forms.TextBox
		Friend WithEvents QuestionNum5Label As System.Windows.Forms.Label
		Friend WithEvents SurveyIDTextBox As System.Windows.Forms.TextBox
		Friend WithEvents SurveyIDLabel As System.Windows.Forms.Label
		Friend WithEvents SurveyNameTextBox As System.Windows.Forms.TextBox
		Friend WithEvents SurveyNameLabel As System.Windows.Forms.Label
		Friend WithEvents panel3 As System.Windows.Forms.Panel
		Friend WithEvents panel4 As System.Windows.Forms.Panel
		Friend WithEvents panel5 As System.Windows.Forms.Panel
		Friend WithEvents panel6 As System.Windows.Forms.Panel
        Friend WithEvents PictureBox1 As PictureBox
        Friend WithEvents Label1 As Label
    End Class

End Namespace
