' ++++++++++++++++++++++++++++++++++++++++++++++++++
' This code is generated by a tool and is provided "as is", without warranty of any kind,
' express or implied, including but not limited to the warranties of merchantability,
' fitness for a particular purpose and non-infringement.
' In no event shall the authors or copyright holders be liable for any claim, damages or
' other liability, whether in an action of contract, tort or otherwise, arising from,
' out of or in connection with the software or the use or other dealings in the software.
' ++++++++++++++++++++++++++++++++++++++++++++++++++
'

Imports System.ComponentModel
Imports System.Data.Entity.Core.Objects
Imports System.Data.Entity

Namespace DatabaseTestApplication2
	
	Public Class frmuser

		Private ctx As mydbEntities1

		Private Sub Form1_Load(sender As System.Object, e As System.EventArgs) Handles MyBase.Load
			ctx = New mydbEntities1()
			ctx.users.Load()
			Dim _entities As BindingList(Of user) = ctx.users.Local.ToBindingList()
			userBindingSource.DataSource = _entities
			Me.usernameTextBox.DataBindings.Add(New System.Windows.Forms.Binding("Text", Me.userBindingSource, "username", True ))
			Me.passwordTextBox.DataBindings.Add(New System.Windows.Forms.Binding("Text", Me.userBindingSource, "password", True))
		End Sub
		
		Private Sub ToolStripButton1_Click(sender As System.Object, e As System.EventArgs) Handles ToolStripButton1.Click
			If Not Me.Validate() Then
				Return
			End If
			userBindingSource.EndEdit()
			ctx.SaveChanges()
		End Sub
		
		Private Sub Form1_FormClosing(sender As System.Object, e As System.Windows.Forms.FormClosingEventArgs) Handles MyBase.FormClosing
			e.Cancel = False
		End Sub
		
		Private Sub usernameTextBox_Validating(sender As Object, e As CancelEventArgs) Handles usernameTextBox.Validating
			
			e.Cancel = False
			If String.IsNullOrEmpty( usernameTextBox.Text ) Then 
				e.Cancel = True
				errorProvider1.SetError( usernameTextBox, "The field username is required" ) 
			End If
			If Not e.Cancel Then
				errorProvider1.SetError( usernameTextBox, "" )
			End If
		End Sub
		
		Private Sub passwordTextBox_Validating(sender As Object, e As CancelEventArgs) Handles passwordTextBox.Validating
			
			e.Cancel = False
			If String.IsNullOrEmpty( passwordTextBox.Text ) Then 
				e.Cancel = True
				errorProvider1.SetError( passwordTextBox, "The field password is required" ) 
			End If
			If Not e.Cancel Then
				errorProvider1.SetError( passwordTextBox, "" )
			End If
		End Sub
		
		
		Private Sub bindingNavigatorAddNewItem_Click(sender As System.Object, e As System.EventArgs) Handles BindingNavigatorAddNewItem.Click
			userBindingSource.AddNew()
		End Sub

		Private Sub Button1_Click(sender As Object, e As EventArgs) Handles Button1.Click
			If TextBox1.Text = passwordTextBox.Text Then
				If TextBox2.Text = TextBox3.Text Then
					passwordTextBox.Text = TextBox3.Text

				Else Messagebox.Show("Passwords Do Not Match.")
				End If

			Else MessageBox.Show("Incorrect Password.")
			End If



		End Sub
	End Class
	
End Namespace
