'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Namespace DatabaseTestApplication2

    Partial Public Class homeownership
        Public Property applicantInfoMeeting As Nullable(Of Date)
        Public Property applicationChecklist1 As Nullable(Of Date)
        Public Property applicationChecklist2 As Nullable(Of Date)
        Public Property employmentVerified As Nullable(Of SByte)
        Public Property landlordReference As Nullable(Of SByte)
        Public Property previousLandlordReference As Nullable(Of SByte)
        Public Property backgroundCheck As Nullable(Of SByte)
        Public Property CCCBudget As Nullable(Of SByte)
        Public Property creditReportRun As Nullable(Of SByte)
        Public Property homeVisit As Nullable(Of Date)
        Public Property committeeDecision As Nullable(Of Date)
        Public Property committeeAccepted As Nullable(Of SByte)
        Public Property committeeReason As String
        Public Property boardVote As Nullable(Of Date)
        Public Property boardAccepted As Nullable(Of SByte)
        Public Property boardReason As String
        Public Property handbookReview As Nullable(Of Date)
        Public Property general_UID As Integer
    
        Public Overridable Property general As general
    
    End Class

End Namespace
