'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Namespace DatabaseTestApplication2

    Partial Public Class tracking
        Public Property sweatEquityDate As Nullable(Of Date)
        Public Property sweatEquityAmount As Nullable(Of Integer)
        Public Property monthlyDepositDate As Nullable(Of Date)
        Public Property monthlyDepositAmount As Nullable(Of Double)
        Public Property HUDHoursDate As Nullable(Of Date)
        Public Property HUDHoursComplete As Nullable(Of SByte)
        Public Property financeClassesDate As Nullable(Of Date)
        Public Property financeClassesComplete As Nullable(Of SByte)
        Public Property homebuyerEducationDate As Nullable(Of Date)
        Public Property homebuyerEducationAmount As Nullable(Of SByte)
        Public Property mortgage1Price As Nullable(Of Double)
        Public Property mortgage1Bank As String
        Public Property mortgage1Forgivable As Nullable(Of SByte)
        Public Property mortgage1OriginalBalance As Nullable(Of Double)
        Public Property mortgage1NumberOfYears As Nullable(Of Integer)
        Public Property general_UID As Integer
        Public Property mortgage2Price As Nullable(Of Double)
        Public Property mortgage2Bank As String
        Public Property mortgage2Forgivable As Nullable(Of SByte)
        Public Property mortgage2OriginalBalance As Nullable(Of Double)
        Public Property morgage2NumberOfYears As Nullable(Of Integer)
        Public Property mortgage3Price As Nullable(Of Double)
        Public Property mortgage3Bank As String
        Public Property mortgage3Forgivable As Nullable(Of SByte)
        Public Property mortgage3OriginalBalance As Nullable(Of Double)
        Public Property mortgage3NumberOfYears As Nullable(Of Integer)
        Public Property mortgage4Price As Nullable(Of Double)
        Public Property mortgage4Bank As String
        Public Property mortgage4Forgivable As Nullable(Of SByte)
        Public Property mortgage4OriginalBalance As Nullable(Of Double)
        Public Property mortgage4NumberOfYears As Nullable(Of Integer)
        Public Property mortgage5Price As Nullable(Of Double)
        Public Property mortgage5Bank As String
        Public Property mortgage5Forgivable As Nullable(Of SByte)
        Public Property mortgage5OriginalBalance As Nullable(Of Double)
        Public Property mortgage5NumberOfYears As Nullable(Of Integer)
        Public Property mortgage6Price As Nullable(Of Double)
        Public Property mortgage6Bank As String
        Public Property mortgage6Forgivable As Nullable(Of SByte)
        Public Property mortgage6OriginalBalance As Nullable(Of Double)
        Public Property mortgage6NumberOfYears As Nullable(Of Integer)
    
        Public Overridable Property general As general
    
    End Class

End Namespace
